### PR TITLE
Add OpenCV 3.4.1. Update config.

### PR DESCRIPTION
**Pull request by xsacha**
* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "Some broken":

  * https://ci.appveyor.com/project/xsacha/hunter-h4uji
  * https://travis-ci.org/xsacha/hunter/builds/347083570

* This update will break few old toolchains.
  They are excluded in this pull request: https://github.com/ingenue/hunter/pull/199

### CODE REVIEW

**Comment by ruslo** [comment]
Please fill `PULL_REQUEST_TEMPLATE.md`:
* https://raw.githubusercontent.com/ruslo/hunter/master/.github/PULL_REQUEST_TEMPLATE.md

This part:
```
<!--- Use this part of template if you're updating existing package. Remove the rest. -->
<!--- BEGIN -->
...
<!--- END -->
```

**Comment by xsacha** [comment]
Done :)

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3382
* https://travis-ci.org/ingenue/hunter/builds/348029871?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3383
* https://travis-ci.org/ingenue/hunter/builds/348095417?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.20.14

**Pull request merged**
