### PR TITLE
support MSVC 19.12

### PR DESCRIPTION
**Pull request by dvirtz**
MSVC 15.5 Preview has compiler version 19.12

### CODE REVIEW

**Comment by dvirtz** [comment]
Maybe it will be better to just use "191[0-9]" as the regex instead of updating this every compiler version change?

**Comment by ruslo** [comment]
> Maybe it will be better to just use "191[0-9]" as the regex instead of updating this every compiler version change?

I guess so. Also I don't understand why this is changing. Previous versions looks stable.

**Comment by dvirtz** [comment]
Found [this](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/visual-c-compiler-version/) blog post which explains the versioning changes.

**Comment by ruslo** [comment]
Looks good, thanks.

**Pull request merged**
