### PR TITLE
Added package MySQL-client

### PR DESCRIPTION
**Pull request by pretyman**
Left name as MySQL-client for the MySQL C Connector because of the name of library file.

MySQL provides a C++ Connector which has the `libcppcon` library file name, which depends on this C connector. If anyone would add the C++ connector in the future, I guess they could name the Hunter package `MySQL-cppcon` and create a target name `MySQL::cppcon` because this seems to be the vocabulary used for the library filename in the build instructions for the C++ Connector.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://travis-ci.org/ingenue/hunter/builds/105852301
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.43

**Comment by ruslo** [comment]
> https://ci.appveyor.com/project/ingenue/hunter/build/1.0.43

All windows tests failed

**Comment by ruslo** [comment]
> https://travis-ci.org/ingenue/hunter/builds/105852301

Some tests failed here. I will disable them, please check that there is no useful information will be left:
* [Android](https://travis-ci.org/ingenue/hunter/jobs/105852305)
* [iOS](https://travis-ci.org/ingenue/hunter/jobs/105852316)
* [Analyze](https://travis-ci.org/ingenue/hunter/jobs/105852306)

Sanitizers:
* [Thread](https://travis-ci.org/ingenue/hunter/jobs/105852309)
* [Leak](https://travis-ci.org/ingenue/hunter/jobs/105852308)
* [Address](https://travis-ci.org/ingenue/hunter/jobs/105852307)

**Comment by pretyman** [comment]
> All windows tests failed

Ouch, I've only tested on OSX to tell you the truth. I've checked the logs and it seems that MySQL did not compile at all with this tar ball. 

I went to the MySQL site and they seem to provide a separate zip file for windows ( https://dev.mysql.com/downloads/connector/c/ - `Select Platform -> Source Code` ), so I guess we'll have to use that.

I don't have access to a Windows machine at the moment and am tight on time, but I think next week I should be able to setup a Windows VM with VS 2015 and try out that zip package for windows.

Let's leave this pull request on hold until then.

**Comment by pretyman** [comment]
I setup a Windows 10 machine with Visual Studio 2015, used the MySQL windows source that comes in a zip file (the MySQL download site says the source is architecture independent, so the windows version should be just newline characters with carriage returns).

I tried to compile the example and same errors happened: https://gist.github.com/pretyman/1f37ce0c18d782a54213 

Searching I found the following stackoverflow post: http://stackoverflow.com/questions/34091321/compiling-mysql-connector-with-visual-studio-2015-win64
 
> I'll close this issue, managed to compile the source with an older ,VS2013 x64, version of Visual Studio, and CMake 4.3.1 ...

>It seems, the new changes in Visual Studio 2015 are breaking the C connector source code, I hope that MySQL team will fix this in a future release.

@ruslo , how should I proceed in this scenario?

**Comment by ruslo** [comment]
> how should I proceed in this scenario

Just exclude all broken tests. If there is no toolchains that are working on windows use toolchain `dummy`.

**Comment by pretyman** [comment]
Can you give me directions on how to do that? I've tried searching around, looked at https://github.com/ruslo/hunter/blob/master/jenkins.py#L54 and saw how to skip the tests:

```python
  if (project_dir == 'examples/MySQL-client') and (toolchain == 'default'):
    print('Skip (https://github.com/ruslo/hunter/pull/316)')
    sys.exit(0)
```

The toolchain `default` I took from the appveyor log.

However I could not find out how to assign the dummy toolchain. 

Thanks

**Comment by ruslo** [comment]
> However I could not find out how to assign the dummy toolchain

This is only for `pkg.*` testing branches:
* https://github.com/ingenue/hunter/blob/33a7a8d46806f55cf80e02587522cccb0d76bba5/jenkins.py#L75

Example of `dummy` toolchain:

https://github.com/ingenue/hunter/blob/a422478456a6be8467857ec5afe9873750984c5d/.travis.yml#L30

**Comment by pretyman** [comment]
Good god, I feel very stupid, let me see if I understood this: I should edit appveyor.yml with:

```yml
  - PROJECT_DIR: examples\MySQL-client
    TOOLCHAIN: dummy
```

and add it to this pull request? Since the jenkins.py script you linked skips toolchain dummy then the test would be skipped in appveyor?

There is so many repos and branches about hunter testing, I don't follow how they all work, hence my doubts.

Thanks

**Comment by ruslo** [comment]
> and add it to this pull request?

Yes, send PR to the `pkg.mysqlclient` branch. Also I think it will be useful to save the links to the broken builds for the easy failures investigation in future, like this: https://github.com/ingenue/hunter/commit/fee2b4fcd7728b93e14b4c6231d934810de526d9

> Since the jenkins.py script you linked skips toolchain dummy then the test would be skipped in appveyor?

Yes.

> There is so many repos and branches about hunter testing, I don't follow how they all work, hence my doubts.

This is design I've figured out so far. We need to use different branches for different packages (otherwise we will have zillion variants in one .travis.yml). Updates flow is `develop` -> `pkg.template` -> `pkg.*`. Any package updates go to `develop`, per package .travis.yml/appveyor.yml goes to `pkg.*`. Let me know if you have any better ideas/suggestions.

**Comment by pretyman** [comment]
I don't know of a better design, I just got confused because я дурак. Also on the front page of https://github.com/ingenue/hunter it says to contribute here, but it is more clear now. I see you merged the removal of the tests, is there anyway to trigger the tests again in this pull request?

**Comment by ruslo** [comment]
>  Also on the front page of https://github.com/ingenue/hunter it says to contribute here

Updated, hope makes it more clear now.

> I see you merged the removal of the tests, is there anyway to trigger the tests again in this pull request?

Done: https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=pr-316

**Comment by ruslo** [comment]
> Done

Linux/OSX failed list: https://travis-ci.org/ingenue/hunter/builds/112505601

**Comment by pretyman** [comment]
Ok, I removed them.

The `sanitize-*` tests are all failing to link, but the library links successfully with other toolchains, could it by an error in the toolchain configuration?

**Comment by ruslo** [comment]
> The sanitize-* tests are all failing to link, but the library links successfully with other toolchains, could it by an error in the toolchain configuration?

I see `-fsanitize=address` flag passed to compiler so it's not a toolchain bug, but it may be:
* Hunter bug: flag is not passed to compiler while doing custom build scheme configuration
* Package bug: if some dependency is not hunterized and picked from system (which is not "instrumented" i.e. not compiled with `-fsanitize`)

**Comment by ruslo** [comment]
New wiki page: https://github.com/ruslo/hunter/wiki/pkg.mysql.client

**Pull request merged**
