### PR TITLE
Enable cache on odb packages

### PR DESCRIPTION
**Pull request by pretyman**

### CODE REVIEW

**Comment by ruslo** [comment]
`odb-boost` doesn't looks good:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.288
* https://travis-ci.org/ingenue/hunter/builds/116995531

We need to make it "green" first. Feel free to exclude broken tests.

**Comment by pretyman** [comment]
All AppVeyor tests failed because `odb` has only `autotools` integration and VisualStudio does not integrate with `autotools`.

Package `odb` has also VisualStudio solution/projects which I would guess it can be compiled by `msbuild`. 

Would be cool if we had some generic `msbuild` integration, following for example the scheme contributed by @Cyberunner23 (under https://github.com/ruslo/hunter/blob/master/cmake/projects/libsodium/schemes/url_sha1_libsodium_msbuild.cmake.in). Something like we have for `url_sha1_autotools`.

I'll leave this pull request open for a bit, so when I setup a windows box, I'll see if this default `msbuild` scheme can be done. I just don't want to disable the windows tests and have to enable them again later on as I have limited time.

Or... we could open an issue and wait for @Cyberunner23 to volunteer ;-)

**Comment by Cyberunner23** [comment]
> I'll see if this default `msbuild` scheme can be done.

It could be done, however we'll need to do something like the `hunter_autotools_project` and add a bunch more options given how msbuild is much and perhaps annoyingly more configurable. For example we'll need to add an `INSTALL_COMMAND` argument as some msbuild buildsystems dont copy the headers to the install directory... Perhaps have arguments for the `Release`, `ReleaseDLL`, `Debug` and `DebugDLL` because apparently they can be renamed, removed, have other targets and so on. I mean its possible but we have to think of all the possible tweaks we need to be able to handle.

**Comment by ruslo** [comment]
> I mean its possible but we have to think of all the possible tweaks we need to be able to handle.

We can start with what we need now and add features step-by-step.

**Comment by pretyman** [comment]
To be solved first: https://github.com/ruslo/hunter/issues/218

**Comment by pretyman** [comment]
Actually, can we merge this? It will help to do some public relations here: [[odb-users] Custom ODB compiler build rule on OSX](http://codesynthesis.com/pipermail/odb-users/2016-August/003418.html)

**Comment by ruslo** [comment]
> Actually, can we merge this?

-

> Solve #218 before merging this

Bug is still open, I guess some toolchains will not work. Is it okay?

**Comment by pretyman** [comment]
I've already commented out ios toolchain, all tests should pass 👍

**Comment by ruslo** [comment]
odb-boost:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.848
* https://travis-ci.org/ingenue/hunter/builds/155248453

**Comment by ruslo** [comment]
odb.mysql:
* https://travis-ci.org/ingenue/hunter/builds/155248453
* https://travis-ci.org/ingenue/hunter/builds/155249479

**Comment by ruslo** [comment]
odb.pgsql:
* https://travis-ci.org/ingenue/hunter/builds/155250502

**Comment by ruslo** [comment]
odb.sqlite:
* https://travis-ci.org/ingenue/hunter/builds/155250855

**Comment by ruslo** [comment]
odb:
* https://travis-ci.org/ingenue/hunter/builds/155251917

**Comment by ruslo** [comment]
Let me know if you think that we should do any other tests.

**Comment by ruslo** [comment]
Uploading: https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=upload.odb

**Comment by ruslo** [comment]
> Uploading

Failed: https://travis-ci.org/ingenue/hunter/jobs/155255076

There is a test after upload that all packages can be downloaded from server on next build. Such test is not passed because `odb-compiler` is missing. Need to make it cacheable.

**Comment by pretyman** [comment]
> Need to make it cacheable.

Hum, in the past I recall reading through the code somewhere that when using scheme `url_sha1_unpack_install` it would be implicitly cacheable, but obviously something has changed.

Do I just add `hunter_cacheable(odb-compiler)` and *that's it*?

**Comment by ruslo** [comment]
> Do I just add hunter_cacheable(odb-compiler) and that's it?

No no need, I think this is a Hunter issue. I'll take a look.

**Comment by ruslo** [comment]
While testing I've noticed that generated files put into source-tree instead of build-tree. Consider following [out-of-source](http://cgold.readthedocs.io/en/latest/tutorials/out-of-source.html#other-notes) approach and keep all autogenerated stuff in temporary folders.

**Comment by ruslo** [comment]
> I'll take a look

Fix: https://github.com/ruslo/hunter/commit/a28656387c056c160ba411718e27d2ce8c64ecb1?diff=unified

Testing:
* https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=upload.odb

Details:
* https://docs.hunter.sh/en/latest/reference/internal-variables/hunter_package_scheme.html

**Comment by ruslo** [comment]
`odb-mysql` failed:
* https://travis-ci.org/ingenue/hunter/builds/155893928

Package `MySQL-client` should be cacheable.

**Comment by ruslo** [comment]
> odb-mysql failed

Testing new updates: https://travis-ci.org/ingenue/hunter/builds/156127016

**Comment by ruslo** [comment]
Now OSX is broken: https://travis-ci.org/ingenue/hunter/builds/156129547

```
configure: error: in `/Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/dc1cb1f/cef4daf/6217056/Build/odb-mysql/Source':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make[2]: *** [odb-mysql-prefix/src/odb-mysql-stamp/odb-mysql-configure] Error 1
make[1]: *** [CMakeFiles/odb-mysql.dir/all] Error 2
make: *** [all] Error 2
```

since the last change was about cacheable version I can guess full path stuck somewhere (RPATH? *.pc?)

**Pull request merged**
