### PR TITLE
Add gflags v2.2.1 and make it new default, update example

### PR DESCRIPTION
**Pull request by schuhschuh**
Finally released gflags 2.2.1 and updated the previous PR (#601).

### CODE REVIEW

**Comment by schuhschuh** [comment]
Damn, sorry... forgot to update the version information when tagging the release.

**Comment by schuhschuh** [comment]
Ok, I've fixed the release and updated the SHA. Should be good to go now.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1942
* https://travis-ci.org/ingenue/hunter/builds/252885489?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1944
* https://travis-ci.org/ingenue/hunter/builds/252944377?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released https://github.com/ruslo/hunter/releases/tag/v0.19.30

**Pull request merged**
