### PR TITLE
Update RapidJSON to v1.1.0

### PR DESCRIPTION
**Pull request by caseymcc**
Will update pkg.rapidjson in a few

### CODE REVIEW

**Comment by ruslo** [comment]
You mean you want to exclude some toolchains? I've pushed latest environment to pkg.rapidjson:
* https://github.com/ingenue/hunter/tree/pkg.rapidjson

**Comment by caseymcc** [comment]
No, was just going to change the osx version, but since you already have no need. Thanks.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3116
* https://travis-ci.org/ingenue/hunter/builds/319603827?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3117
* https://travis-ci.org/ingenue/hunter/builds/319612909?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.208

**Pull request merged**
