### PR TITLE
Upgrades yaml-cpp to v0.6.2.

### PR DESCRIPTION
**Pull request by olliwang**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://travis-ci.com/olliwang/hunter/builds/102698463

### CODE REVIEW

**Comment by olliwang** [comment]
The build passed here. Do I need to use my own account to do it again?

**Comment by ruslo** [comment]
> https://travis-ci.org/ruslo/hunter/builds/499838502
> The build passed here. Do I need to use my own account to do it again?

It's not a package test, it's a documentation build test:
- https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#pull-requests

> I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html) step by step carefully. **[Yes]**

Please read it again.

**Comment by olliwang** [comment]
Thanks. It seems something's going wrong about the `analyze-cxx17` toolchain. Not sure what causes this. https://travis-ci.com/olliwang/hunter/builds/102679531

**Comment by ruslo** [comment]
> It seems something's going wrong about the `analyze-cxx17` toolchain. Not sure what causes this.

You're using wrong toolchain set, `analyze-cxx17` already excluded from `yaml-cpp` testing. See `pkg.yaml-cpp` branch:
- https://github.com/ingenue/hunter/blob/pkg.yaml-cpp/.travis.yml#L51-L55

**Comment by olliwang** [comment]
You are right. I was confused between creating a new package and updating an existing package. Now it passes. https://travis-ci.com/olliwang/hunter/builds/102691209

**Comment by ruslo** [comment]
>  Now it passes. https://travis-ci.com/olliwang/hunter/builds/102691209

Still something wrong:
```
-- Using src='https://github.com/hunter-packages/yaml-cpp/archive/v0.5.3-p4.zip'
-- verifying file...
       file='/home/travis/build/olliwang/hunter/_testing/Hunter/_Base/Download/yaml-cpp/0.5.3-p4/b8de749/v0.5.3-p4.zip'
-- Downloading... done
```

I do expect to see new 0.6.2 version here.

**Comment by olliwang** [comment]
Sorry. Just fixed it. https://travis-ci.com/olliwang/hunter/builds/102698463

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22726988
- https://travis-ci.org/ingenue/hunter/builds/499948132?utm_source=github_status&utm_medium=notification

**Comment by olliwang** [comment]
Thank you. :)

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22727549
- https://travis-ci.org/ingenue/hunter/builds/499957438?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.123

**Pull request merged**
