### PR TITLE
update 'glm' to 0.9.8.5

### PR DESCRIPTION
**Pull request by headupinclouds**
`TOOLCHAIN=default PROJECT_DIR=examples/glm ./jenkins.py --verbose`
```
Generate: 0:00:24.882442s
Build: 0:00:02.273495s
Total: 0:00:27.156409s
SUCCESS
```

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1769
* https://travis-ci.org/ingenue/hunter/builds/239699120?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1773
* https://travis-ci.org/ingenue/hunter/builds/239715105?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Thanks.

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.3

**Pull request merged**
