### PR TITLE
Avoid dropping compiler flags on iOS

### PR DESCRIPTION
**Pull request by jdonald**
The hunter_dump_cmake_flags() function has behavior specific to iOS where it unintentionally flushes compiler flags. Furthermore, on top of being specific to iOS this bug typically manifests with a small number of libraries including Boost, OpenBLAS, and OpenSSL which make use of hunter_dump_cmake_flags() in their schemes.

The has gone largely unnoticed because it does not result in a build failure or runtime error, but larger binaries.

Testing with `ios-nocodesign-hid-sections.cmake`:
```
-- [polly] Used toolchain: iOS 12.1 Universal (iphoneos + iphonesimulator) / clang / No code sign / \
 function-sections / data-sections / hidden visibility / c++11 support
```

Current behavior:
```
Performing build step for 'Boost-chrono-ios'
cd /Users/jdonald/.hunter/_Base/6db0cd0/1360802/3cdad54/Build/Boost/__chrono/Source && ./b2 "-d+2 --debug-configuration" toolset=darwin-iphoneos target-os=iphone architecture=arm instruction-set=armv7 -a link=static threading=multi variant=release,debug define=BOOST_SP_NO_SYNC --layout=tagged --user-config=\"/Users/jdonald/.hunter/_Base/6db0cd0/1360802/3cdad54/Build/Boost/__chrono/Build/boost.user.jam\" \
"cxxflags=-miphoneos-version-min=8.0 -std=c++11" -j 8
```
where above it's missing requested flags. Compare that to running with this fix:
```
Performing build step for 'Boost-chrono-ios'
cd /Users/jdonald/.hunter/_Base/b4930e9/1360802/41c4d88/Build/Boost/__chrono/Source && ./b2 "-d+2 --debug-configuration" toolset=darwin-iphoneos target-os=iphone architecture=arm instruction-set=armv7 -a link=static threading=multi variant=release,debug define=BOOST_SP_NO_SYNC --layout=tagged --user-config=\"/Users/jdonald/.hunter/_Base/b4930e9/1360802/41c4d88/Build/Boost/__chrono/Build/boost.user.jam\" \
"cxxflags=-fdata-sections -ffunction-sections -fvisibility-inlines-hidden -fvisibility=hidden -std=c++11 -miphoneos-version-min=8.0 -std=c++11" -j 8
```

* **I've tested this package.** Travis's default builds include configurations such as `ios-nocodesign-11-3-dep-9-3-arm64.cmake`, but these do not contain additional flags to exhibit the problem when building Boost. We had to run a targeted test using `ios-nocodesign-hid-sections.cmake` from polly.
---

* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **Yes**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **Yes**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **Yes**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **Yes**

---

### CODE REVIEW

**Comment by ruslo** [comment]
Testing.

odb-boost:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22535249
- https://travis-ci.org/ingenue/hunter/builds/496348822?utm_source=github_status&utm_medium=notification

libxml2:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22535276
- https://travis-ci.org/ingenue/hunter/builds/496349383?utm_source=github_status&utm_medium=notification

OpenSSL:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22535292
- https://travis-ci.org/ingenue/hunter/builds/496349685?utm_source=github_status&utm_medium=notification

Boost:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22535321
- https://travis-ci.org/ingenue/hunter/builds/496350121?utm_source=github_status&utm_medium=notification

**Comment by jdonald** [comment]
Good catch from Travis. Looks like the reason ios-nocodesign-hid-sections is able to pass while ios-nocodesign-11-4-dep-9-3 is that OpenSSL's Configure will pass down flags beginning with `-f`. 

As for why Travis isn't seeing the same problem on macOS--which follows very similar logic, I traced the difference down to this workaround in the OpenSSL scheme:
```
cmake/projects/OpenSSL/schemes/url_sha1_openssl_macos.cmake.in:string(REGEX REPLACE "^ " "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
```
so I'll put in the appropriate minimal fix of adding the same line to url_sha1_openssl_ios.cmake.in

**Comment by ruslo** [comment]
Testing.

OpenSSL:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22566885
- https://travis-ci.org/ingenue/hunter/builds/496905505?utm_source=github_status&utm_medium=notification

odb-boost:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22566907
- https://travis-ci.org/ingenue/hunter/builds/496906063?utm_source=github_status&utm_medium=notification

libxml2:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22566917
- https://travis-ci.org/ingenue/hunter/builds/496906262?utm_source=github_status&utm_medium=notification

Boost:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22566923
- https://travis-ci.org/ingenue/hunter/builds/496906390?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading.

OpenSSL:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22573670
- https://travis-ci.org/ingenue/hunter/builds/497028652?utm_source=github_status&utm_medium=notification

odb-boost:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22573679
- https://travis-ci.org/ingenue/hunter/builds/497028819?utm_source=github_status&utm_medium=notification

libxml2:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22573694
- https://travis-ci.org/ingenue/hunter/builds/497029196?utm_source=github_status&utm_medium=notification

Boost:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22573705
- https://travis-ci.org/ingenue/hunter/builds/497029298?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Thanks for the fix, released: https://github.com/ruslo/hunter/releases/tag/v0.23.114

**Pull request merged**
