### PR TITLE
Add 'units' package

### PR DESCRIPTION
**Pull request by achary**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/achary/hunter/builds/19834503
  * https://travis-ci.com/achary/hunter/builds/89358544

* I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch,
  see this merged pull request https://github.com/ingenue/hunter/pull/283

---

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/builds/19881052
* https://travis-ci.org/ingenue/hunter/builds/447818005?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/builds/19881505
* https://travis-ci.org/ingenue/hunter/builds/447824486?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.40

**Comment by kaihowl** [comment]
This adds an alpha version of the library while properly release libraries are available. Should we add the properly released library and make that the default instead?

**Comment by ruslo** [comment]
> Should we add the properly released library version and make that the default instead?

Feel free to open a pull request for a discussion with the version that you think is more appropriate to have.

**Pull request merged**
