### PR TITLE
Updated OpenCV to 3.1.0

### PR DESCRIPTION
**Pull request by pretyman**

### CODE REVIEW

**Comment by ruslo** [comment]
Haven't tried OpenCV CI testing yet. Let's see what happens:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.248
* https://travis-ci.org/ingenue/hunter/builds/116174575

**Comment by pretyman** [comment]
Many tests failed. I have the Qt backend working locally on my machine in OSX which I can already use for a presentation this Friday for Computer Vision class. I'll have to look at it on the weekend.

**Comment by ruslo** [comment]
> Many tests failed

I've cancelled the build :) Linux tests failed because of some part of OpenCV use shared libraries but most of the 3rd party is static without PIC. I've added `gcc-4-8-pic` to Polly, testing now, will update matrix. Also I've realized that it's possible to build Release + Debug so have to update matrix too. Will leave a note about new testing.

**Comment by ruslo** [comment]
> I've added gcc-4-8-pic to Polly

Remove modules with shared libraries instead: https://github.com/ruslo/hunter/commit/f87b8d301fdcc6cd8cd08b34f7102b1134235c0e

Will run new tests. Building dependencies for upload for now.

**Comment by ruslo** [comment]
> Will run new tests. Building dependencies for upload for now

Just for your information windows toolchains:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.281

`ios` toolchain on Travis hit timeout (5 archs - 5 times slower):
* https://travis-ci.org/ingenue/hunter/jobs/116842925

Planing to do upload from local machine.

The rest works fine:
* https://travis-ci.org/ingenue/hunter/builds/116842915

**Comment by ruslo** [comment]
New testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.283
* https://travis-ci.org/ingenue/hunter/builds/116902041

**Comment by ruslo** [comment]
> New testing

Passed. @pretyman Thank you!

**Comment by pretyman** [comment]
Nice, no thank you for letting us to contribute to your project! :+1:

**Pull request merged**
