### PR TITLE
Add dlib 19.4-3 and dlib 19.6-0

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2267
* https://travis-ci.org/ingenue/hunter/builds/269594044?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

Android failed, was working before:
* https://travis-ci.org/ingenue/hunter/builds/269634166?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
> error: 'round' is not a member of 'std'
>              return centered_rect(rect, (long)std::round(rect.width()*scale), (long)std::round(rect.height()*scale));

This is an issue on old NDKs it seems. I can add some code to make it work on older versions.

**Comment by ruslo** [comment]
> This is an issue on old NDKs it seems. I can add some code to make it work on older versions

Okay. Also you can exclude this toolchain if problem is not in Hunter/Polly.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2292
* https://travis-ci.org/ingenue/hunter/builds/270363933?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2296
* https://travis-ci.org/ingenue/hunter/builds/270391181?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.90

**Pull request merged**
