### PR TITLE
update eigen3-nnls

### PR DESCRIPTION
**Pull request by headupinclouds**
Fix `_P` namespace conflict for android/gcc.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2604
* https://travis-ci.org/ingenue/hunter/builds/291192887?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2606
* https://travis-ci.org/ingenue/hunter/builds/291203428?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.131

**Comment by headupinclouds** [comment]
Tests == 👍

**Pull request merged**
