### PR TITLE
Add dlib 19.10-p4

### PR DESCRIPTION
**Pull request by xsacha**
* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/xsacha/hunter-h4uji/build/1.0.10
  * https://travis-ci.org/xsacha/hunter/builds/381299184

---

Fifth time lucky. This one fixes an issue when CUDA was enabled.
It was actually broken upstream in this release

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3976
* https://travis-ci.org/ingenue/hunter/builds/381600263?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
GCC sometimes gets an ICE on this build. I got it too and did a rebuild and it worked.

**Comment by ruslo** [comment]
> gcc-7-cxx17 sometimes gets an ICE on this build

`HUNTER_JOBS_NUMBER=1` added to stabilize it:
* https://travis-ci.org/ingenue/hunter/builds/381645756

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3978
* https://travis-ci.org/ingenue/hunter/builds/381655603?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.21.7

**Pull request merged**
