### PR TITLE
Add Tesseract project and example.

### PR DESCRIPTION
**Pull request by xsacha**
Should be ready to go! :)

### CODE REVIEW

**Comment by ruslo** [comment]
https://github.com/hunter-packages/tesseract

**Comment by xsacha** [comment]
Changed to hunter-packages.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1853
* https://travis-ci.org/ingenue/hunter/builds/243145777?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
some toolchains failed

**Comment by xsacha** [comment]
A lot of the failures look related to OpenCL, which isn't actually used. If it does get used, however, what is the best way of adding it so it does not stop platforms from working?

**Comment by ruslo** [comment]
> A lot of the failures look related to OpenCL, which isn't actually used

If it's not used then it should be removed, no? If it's optional then it should be protected by `if(FOO_WITH_OPENCL)`.

> what is the best way of adding it so it does not stop platforms from working?

Toolchains supported by OpenCL can be found in CI, see pkg.opencl:
* https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=pkg.opencl

Investigate fixes, apply, update OpenCL, back to this pull request.

> but some other platforms potentially have it inbuilt

Is a part of compiler or installed in system? If in system then it should be duplicated by Hunter, see details:
* https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

**Comment by xsacha** [comment]
There is just a define that needs to be enabled to use OpenCL that isn't being used right now.
On some platforms (macOS and Android), the OpenCL headers and libraries come with th development tools so they can be expected to always exist.
I think I should be able to do find_package without a hunter_add_package in that situation?

**Comment by ruslo** [comment]
> come with the development tools so they can be expected to always exist

"Comes with development tools" and "always exist" is a kind of different I think :)

> I think I should be able to do find_package without a hunter_add_package in that situation?

Such approach can be used as a workarund if it's not clear what to do.

**Comment by xsacha** [comment]
Can test this please? I think I need to remove some MSVC versions but not sure which ones.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1864
* https://travis-ci.org/ingenue/hunter/builds/246195798?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

Everything failed. We need `find_dependency(OpenCL CONFIG)`/`find_package(OpenCL CONFIG REQUIRED)` in `TesseractConfig.cmake` module.

**Comment by xsacha** [comment]
Ah :( Alright.

**Comment by xsacha** [comment]
Now the only build with issues should be some old MSVC versions hopefully!

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1866
* https://travis-ci.org/ingenue/hunter/builds/246996381?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

Some tests failed

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1871
* https://travis-ci.org/ingenue/hunter/builds/247416686?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1877
* https://travis-ci.org/ingenue/hunter/builds/247492098?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.20

**Pull request merged**
