### PR TITLE
add highwayhash + test

### PR DESCRIPTION
**Pull request by headupinclouds**
Add highwayhash package w/ commit taken from tensorflow 

https://github.com/tensorflow/tensorflow/blob/7f84d88d39f236e5c0cea492a2248782e696c972/tensorflow/contrib/cmake/external/highwayhash.cmake#L18-L19

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/external/highwayhash.cmake
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/patches/highwayhash/CMakeLists.txt

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2711
* https://travis-ci.org/ingenue/hunter/builds/299725874?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2722
* https://travis-ci.org/ingenue/hunter/builds/299895979?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Thanks

**Comment by ruslo** [comment]
Follow-up: https://github.com/ruslo/hunter/commit/38a255d5b5db1af8d10d558fc10b8e2238263e43

Released: https://github.com/ruslo/hunter/releases/tag/v0.19.145

**Pull request merged**
