### PR TITLE
Provide "gcc" as argument to Boost's bootstrap.bat when using MinGW

### PR DESCRIPTION
**Pull request by Osse**
There is a long standing bug in Boost where people may experience the
following when running bootstrap.bat:

Building Boost.Build engine
*****\*  B A T C H   R E C U R S I O N  exceeds STACK limits ******
Recursion Count=593, Stack Usage=90 percent
*****\*       B A T C H   PROCESSING IS   A B O R T E D      ******

This occurs when bootstrap.bat is unable to find a compiler toolchain.
In the case of MinGW we can pass gcc as the toolchain name instead of
relying on autodetection.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.806
* https://travis-ci.org/ingenue/hunter/builds/152897250

**Comment by Osse** [comment]
By the way, is there a way for contributors to use the CI for testing without having to submit a formal pull request?

**Comment by ruslo** [comment]
> By the way, is there a way for contributors to use the CI for testing without having to submit a formal pull request?

Sure, also it's preferably for me to have already working state than do "merge -> please fix -> update -> merge" cycle. Just fetch the branch you're interested in from the testing repo: https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=pkg. The only diff between `develop` and those branches is about `.travis.yml`/`appveyor.yml`.

**Comment by ruslo** [comment]
> Testing

Result of testing is inadequate because I forgot about cache :) No builds triggered in fact. Usually it solved by updating [INTERNAL_DEPS_ID](https://github.com/ruslo/hunter/wiki/dev.modules#hunter_download) variable.

It doesn't work on my local machine and here is a test on Windows:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.814

```
    "."  rc "bin.v2\libs\system\build\gcc\release\link-static\threading-multi\libboost_system-mt.a" "bin.v2\libs\system\build\gcc\release\link-static\threading-multi\error_code.o"
    "." "bin.v2\libs\system\build\gcc\release\link-static\threading-multi\libboost_system-mt.a"
'"."' is not recognized as an internal or external command,
operable program or batch file.
'"."' is not recognized as an internal or external command,
operable program or batch file.
...skipped <pstage\lib>libboost_system-mt.a for lack of <pbin.v2\libs\system\build\gcc\release\link-static\threading-multi>libboost_system-mt.a...
```

**Comment by Osse** [comment]
I have looked into it some more today. Using the latest HunterGate, latest Hunter and now Boost 1.6.2 still gives me the above error. Applying my proposed fix still solves the problem... I don't really know where to go from here.  The error you get on windows seems irrelevant; in managed to build the b2 bootstrapper.

**Comment by ruslo** [comment]
> The error you get on windows seems irrelevant; in managed to build the b2 bootstrapper.

The previous configuration works fine on AppVeyor, and the current patch doesn't work on AppVeyor. Why do you think it's irrelevant?

**Comment by Osse** [comment]
Assuming AppVeyor is perfect it is of course relevant. I said it _seems_ irrelevant because the errors appear elsewhere in the build process and I am annoyed :( I have finally my own testing environment now and will try to figure it out.

**Comment by ruslo** [comment]
> Assuming AppVeyor is perfect it is of course relevant

It's not perfect testing service but it's perfect common denominator all of us can use. Also as far as I remember I got the same error on my local machine.

> I have finally my own testing environment now and will try to figure it out

Okay, thanks.

**Comment by ruslo** [comment]
I figured out why current bootstrap works fine on my local machine and on AppVeyor. It seems that it uses `cl.exe` from Visual Studio. I've tested current bootstrap on machine without Visual Studio installed and bootstrap failed... It seems that fix is to add `gcc`. I'm trying [fix similar to yours](https://github.com/ruslo/hunter/pull/753/commits/44117e095a9c24959b6e715ad27e284067224f45) now:
* https://github.com/ruslo/hunter/pull/753

It does work on my local machine, let's see what will happen on AppVeyor. Don't know why it wasn't working before, may be the problem is about Boost version (I see in logs that it's 1.61, now it's 1.63). Not sure.

**Comment by Osse** [comment]
Hi,

Thanks for looking at this. Yes, Boost uses `cl.exe` if it can find it. Tthe presence of Visual Studio is how we discovered this recursion bug. Or rather, once we uninstalled Visual Studio we noticed it. I'm very sorry that I didn't mention that the first time, but then I somehow thought it was irrelevant.

**Pull request closed without merging**
