### PR TITLE
add ogles_gpgpu v0.1.4

### PR DESCRIPTION
**Pull request by headupinclouds**
This provides a OGLES_GPGPU_VERBOSE option to toggle per filter logging (non error)

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://travis-ci.org/ingenue/hunter/builds/173598248
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1155

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1157
* https://travis-ci.org/ingenue/hunter/builds/173600908

**Comment by ruslo** [comment]
Released https://github.com/ruslo/hunter/releases/tag/v0.16.24

**Comment by headupinclouds** [comment]
Thanks!

**Pull request merged**
