### PR TITLE
Add latest GTest release.

### PR DESCRIPTION
**Pull request by Knitschi**

### CODE REVIEW

**Comment by Knitschi** [comment]
Fixed it

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2655
* https://travis-ci.org/ingenue/hunter/builds/293633701?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2656
* https://travis-ci.org/ingenue/hunter/builds/293660275?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.137

**Comment by headupinclouds** [comment]
https://github.com/ruslo/hunter/issues/1105 😏 

> cmake/configs/default.cmake part is missing:

I made this mistake recently as well.  @Knitschi and I are both hunter users and simply forgot.  There is some value to having this information in your face with a PR template.  It would also be nice to present some direct links to the testing documentation -- I always have to chase down the docs on how to run the local jenkins tests, for example.  I can take a stab at it this weekend to facilitate discussion at least.

**Pull request merged**
