### PR TITLE
Add dlib 19.4-p1 package.

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1641
* https://travis-ci.org/ingenue/hunter/builds/227839859?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
/Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/7a23b3a/0f1551d/3ede738/Install/include/dlib/map/../serialize.h:150:10: fatal error: 'array' file not found
#include <array>

Is this a new error? Doesn't occur the same with 19.2?

**Comment by ruslo** [comment]
> Is this a new error? Doesn't occur the same with 19.2?

CI testing on Linux migrated to `trusty` version of Ubuntu. Feel free to exclude, branch [pkg.dlib](https://github.com/ingenue/hunter/tree/pkg.dlib).

**Comment by ruslo** [comment]
Tesitng:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1645
* https://travis-ci.org/ingenue/hunter/builds/227871487?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.18.47

**Pull request merged**
