### PR TITLE
Visual Studio 2017: "Unknown compiler version"

### PR DESCRIPTION
**Pull request by Dargun**
I am using the latest Visual Studio 2017 build and when I compile with Boost libraries I get a lot of the same warning. ("Unknown compiler version - please run the configure tests and report the results")
The latest version 1.65.1 resolves this issue.

### CODE REVIEW

**Review by ruslo — CHANGES_REQUESTED** [review]
> The latest version 1.65.1 resolves this issue

Doesn't work for me:
```
Performing install step for 'Boost'
CMake Error at C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message):
  Command failed: 1
   'C:/.../cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake'
  See also
    C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-*.log
```

From `Boost-install-err.log`:
```
CMake Error at C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake:9 (message):
  Command failed (1):

   'b2' '--layout=tagged' '-d0' 'install' '--without-atomic' '--without-chrono' '--without-container' '--without-context' '--without-coroutine' '--without-date_time' '--without-exception' '--without-fiber' '--without-filesystem' '--without-graph' '--without-graph_parallel' '--without-iostreams' '--without-locale' '--without-log' '--without-math' '--without-metaparse' '--without-mpi' '--without-program_options' '--without-python' '--without-random' '--without-regex' '--without-serialization' '--without-signals' '--without-stacktrace' '--without-system' '--without-test' '--without-thread' '--without-timer' '--without-type_erasure' '--without-wave' '--prefix=C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Install' '--ignore-site-config'
```

From `Boost-install-out.log`:
```
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/tools\msvc.jam:1266: in default-path
*** argument error
* rule path.exists ( location )
* called with: (  )
* missing argument location
(builtin):see definition of rule 'path.exists' being called
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/tools\msvc.jam:735: in auto-detect-toolset-versions
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/tools\msvc.jam:1710: in load
C:\...\hunter\_testing\Hunter\_Base\81ef1a7\3be1296\83deb53\Build\Boost\Source\tools\build\src/kernel\modules.jam:295: in import
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/build\toolset.jam:41: in toolset.using
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/build\project.jam:1052: in using
project-config.jam:3: in modules.load
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src\build-system.jam:249: in load-config
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src\build-system.jam:412: in load-configuration-files
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src\build-system.jam:524: in load
C:\...\hunter\_testing\Hunter\_Base\81ef1a7\3be1296\83deb53\Build\Boost\Source\tools\build\src/kernel\modules.jam:295: in import
C:\...\hunter\_testing\Hunter\_Base\81ef1a7\3be1296\83deb53\Build\Boost\Source\tools\build\src/kernel/bootstrap.jam:139: in boost-build
C:\...\hunter\_testing\Hunter\_Base\81ef1a7\3be1296\83deb53\Build\Boost\Source\boost-build.jam:17: in module scope
```

**Comment by Dargun** [comment]
[#745](https://github.com/ruslo/hunter/issues/745) existing problem and solution.
i'am automate it "as quick fix" in my config for windows like this:
if (EXISTS "${HOME}/Source")
    hunter_status_debug("Delete folder '${HOME}/Source'!")
    file(REMOVE_RECURSE "${HOME}/Source")
 endif()
i can also add it to the hunter config.cmake?

**Comment by ruslo** [comment]
> #745 existing problem and solution.

It's not my case. There is already checker that will return error if this directory is in system:
https://github.com/ruslo/hunter/blob/1d320a0d3179e05a410b7d77c24dfc88d99640ed/cmake/projects/Boost/schemes/url_sha1_boost.cmake.in#L37-L47

> if (EXISTS "${HOME}/Source")

As far as I can see it's `$ENV{USERPROFILE}/Source`.

**Comment by Dargun** [comment]
this i don't understand.
i got only this error if i had this "$ENV{USERPROFILE}/Source" folder existing.
if i deleted that folder it works for me?
have you checked that the directory realy exists?
i don't realized before that there a check already exists :)

**Comment by ruslo** [comment]
> have you checked that the directory realy exists?

`$ENV{USERPROFILE}/Source` directory doesn't exist on my local machine. Not sure I understand the rest of the questions.

As a summary current version from `master` works fine for me and your patch doesn't work because of the error I've posted.

**Comment by Dargun** [comment]
Problem1:
The problem with that check is it doesn't help me with automated builds.
If i remove my small code that removes automaticly this /source folder i get allways the error
[hunter ** FATAL ERROR **] Please remove directory 'C:\Users\johndoe/source' (see https://github.com/ruslo/hunter/issues/745#issuecomment-316629752)

Problem2:
With the master version you can build boost without any direct problems, but if you link against this libs you get this warnings.

**Comment by ruslo** [comment]
> If i remove my small code that removes automaticly this /source folder i get allways the error

It's a check, I don't think Hunter should remove `%USERPROFILE%/Source`. Doesn't sound like a "nice benavior". Also this is a workaround, I guess solution is to add `VSCMD_START_DIR`.

> With the master version you can build boost without any direct problems, but if you link against this libs you get this warnings.

Have no idea what it is about. Pull request with fixes are welcome though.

**Comment by Ubiquite** [comment]
Actually I created PR https://github.com/ruslo/hunter/pull/1145 because I'm using VS2017

**Comment by Predelnik** [comment]
Since boost now 1.66 this PR could be closed. Though there's a chance that for newer VS updates Boost will still give this warning.

**Comment by ruslo** [comment]
> Since boost now 1.66 this PR could be closed

**Pull request closed without merging**
