### PR TITLE
Fix “—sysroot” for Android Studio.

### PR DESCRIPTION
**Pull request by olliwang**
This commit fixes https://github.com/hunter-packages/libxml2/issues/2.

### CODE REVIEW

**Comment by olliwang** [comment]
Done.

**Comment by olliwang** [comment]
Sure. It's done.

**Comment by ruslo** [comment]
Testing.

Boost:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4296
* https://travis-ci.org/ingenue/hunter/builds/412088070?utm_source=github_status&utm_medium=notification

libxml2:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4293
* https://travis-ci.org/ingenue/hunter/builds/412086098?utm_source=github_status&utm_medium=notification

OpenSSL:
* https://travis-ci.org/ingenue/hunter/builds/412086592?utm_source=github_status&utm_medium=notification
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4294

odb-boost:
* https://travis-ci.org/ingenue/hunter/builds/412087226?utm_source=github_status&utm_medium=notification
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4295

**Comment by ruslo** [comment]
Uploading.

odb-boost:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4298
* https://travis-ci.org/ingenue/hunter/builds/412121003?utm_source=github_status&utm_medium=notification

OpenSSL:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4299
* https://travis-ci.org/ingenue/hunter/builds/412121213?utm_source=github_status&utm_medium=notification

libxml2:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4300
* https://travis-ci.org/ingenue/hunter/builds/412121272?utm_source=github_status&utm_medium=notification

Boost:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4301
* https://travis-ci.org/ingenue/hunter/builds/412121366?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.10

**Pull request merged**
