### PR TITLE
Add minizip v1.0.1-p3. Update example.

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3250
* https://travis-ci.org/ingenue/hunter/builds/333121170?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Clang based toolchains stop working on Linux:
* https://travis-ci.org/ingenue/hunter/builds/333121170

Previous version was working fine:
* https://travis-ci.org/ingenue/hunter/builds/333193129

Please do the fix or exclude broken toolchains from testing.

**Comment by xsacha** [comment]
OK,

I just need to disable AES.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3292
* https://travis-ci.org/ingenue/hunter/builds/336484177?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Some toolchains failed, I think reason is the same:
* https://travis-ci.org/ingenue/hunter/builds/336484177?utm_source=github_status&utm_medium=notification

Note that you can test this change remotely yourself, see:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#ci-testing

**Comment by xsacha** [comment]
Argh. Yeah I tested this but pasted wrong name in here. Sorry.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3301
* https://travis-ci.org/ingenue/hunter/builds/336646304?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
Hmm, I don't understand why it still says AES is on. I'll run tests again later.

**Comment by xsacha** [comment]
OK, managed to reproduce and fix that.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3313
* https://travis-ci.org/ingenue/hunter/builds/337425586?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3314
* https://travis-ci.org/ingenue/hunter/builds/337428766?utm_source=github_status&utm_medium=notification

**Pull request merged**
