### PR TITLE
Make wxWidgets cacheable.

### PR DESCRIPTION
**Pull request by alamaison**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.382
* https://travis-ci.org/ingenue/hunter/builds/123198672

**Comment by ruslo** [comment]
Updated branch (without this patch) fails:
* https://travis-ci.org/ingenue/hunter/builds/123198645

This is because of adding custom `FindJPEG.cmake` module that override CMake's version:
* https://github.com/ruslo/hunter/blob/master/cmake/find/FindJPEG.cmake

Looks like current wxWIdgets build try to find libs from system. Need to hunterize this part.

**Comment by ruslo** [comment]
> This is because of adding custom FindJPEG.cmake module that override CMake's version

Okay, looks like it's fixed in new version:
* https://travis-ci.org/ingenue/hunter/builds/123198672

Some Windows builds fail because of `expat` dependency:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.382

`vs-10-2010`, `vs-11-2012` and `vs-9-2008` excluded from `expat` testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.347

Also just for your information `ICE`, `SM`, `X11`, `Xext` is part of the Hunter now (see branch `develop`).

**Comment by alamaison** [comment]
I've created a PR on ingenue to disable the toolchains that Expat breaks: https://github.com/ingenue/hunter/pull/11

**Comment by ruslo** [comment]
> I've created a PR on ingenue to disable the toolchains

Thanks, updated:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.385
* https://travis-ci.org/ingenue/hunter/builds/123304925

**Comment by ruslo** [comment]
> updated

Looks good, merging

**Comment by ruslo** [comment]
Cache uploaded:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.388
* https://travis-ci.org/ingenue/hunter/builds/123392261

Released:
* https://github.com/ruslo/hunter/releases/tag/v0.14.12

**Pull request merged**
