### PR TITLE
add vim modeline to all modules

### PR DESCRIPTION
**Pull request by NeroBurner**
adds modeline to all hunter modules with tabstopwith information (make tabs 2 spaces wide and expand tabulators to spaces)

### CODE REVIEW

**Comment by ruslo** [comment]
I don't think editor specific information should be saved in file. What is the point of this? Why you can't just save this settings globally if you want? (I'm a Vim user by the way)

**Comment by NeroBurner** [comment]
you could save it locally, but then every txt file would have tabwidth 2 with expandtab. With the modeline could work on two projects with CMakefiles, which have different style guidelines

**Comment by ruslo** [comment]
> With the modeline could work on two projects with CMakefiles, which have different style guidelines

Still something that should be done globally on user side, not per CMake file in the world.

**Comment by NeroBurner** [comment]
closing, because not wanted

**Pull request closed without merging**
