### PR TITLE
Added libpng.

### PR DESCRIPTION
**Pull request by alamaison**
Usage:
```cmake
  hunter_add_package(PNG)

  find_package(PNG REQUIRED)

  add_executable(foo main.cpp)
  target_compile_definitions(foo PRIVATE ${PNG_DEFINITIONS})
  target_include_directories(foo PRIVATE ${PNG_INCLUDE_DIRS})
  target_link_libraries(foo PRIVATE ${PNG_LIBRARIES})
```

Unfortunately, the FindPNG.cmake shipped with CMake does not include the _static prefix in the name options, so doesn't find the static library.  The version included here makes that simple change.

### CODE REVIEW

**Comment by alamaison** [comment]
I'm confused why it's failing now: https://travis-ci.org/alamaison/hunter/jobs/56735330.

When I had `hunter_add_package(ZLIB)` in `cmake/projects/PNG/hunter.cmake` it worked fine, except fot a libpng issue on iOS.  I fixed the iOS issue in a fork of libpng and, at the same time, moved the call to `hunter_add_package(ZLIB)` into libpng's CMakeLists.txt.  Now it can't find ZLIB.  Am I doing something really stupid?

**Comment by ruslo** [comment]
zlib installed to:
```bash
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/travis/build/ruslo/hunter/_Base/Install/default/lib/libz.a
```

instead of "_testing" directory:
```bash
-- Installing: /Users/travis/build/ruslo/hunter/_testing/Base/Install/default/lib/libpng.a
-- Installing: /Users/travis/build/ruslo/hunter/_testing/Base/Install/default/include/png.h
-- Installing: /Users/travis/build/ruslo/hunter/_testing/Base/Install/default/include/pngconf.h
-- Installing: /Users/travis/build/ruslo/hunter/_testing/Base/Install/default/include/pnglibconf.h
```

this is because HunterGate module do not respect `HUNTER_BASE` variable. It is an old error which is fixed in last version. See [update](https://github.com/alamaison/libpng/pull/1)

**Comment by alamaison** [comment]
Thanks!  I'm not sure where I got that old HunterGate from.  Was sure I had the latest.  Anyway, your update fixes it.

**Comment by ruslo** [comment]
I've tried to install png locally but it seems there are some broken links:
```
> ls -la _install/libcxx/lib/
libpng.a@ -> $<TARGET_FILE:png16_static>
libpng.dylib@ -> $<TARGET_FILE:png16>
```

OS X, CMake 3.2.1, branch `libpng-hunter`, commit `f161a9c`

**Comment by alamaison** [comment]
I had changed how libpng symlinked its libs, because the way it did it wasn't permitted anymore in CMake 3.  But I messed it up.  Should be better now.  Tested on Linux and Windows.

**Comment by alamaison** [comment]
Could you bump the two PNG-related failed tests?  They didn't run because of the OSX flakiness on Travis.

https://travis-ci.org/ruslo/hunter/jobs/57658074
https://travis-ci.org/ruslo/hunter/jobs/57658078

**Comment by ruslo** [comment]
> Could you bump the two PNG-related failed tests?

done

**Comment by alamaison** [comment]
This looks good to merge, despite the failure

**Comment by ruslo** [comment]
Yep, PNG tests work fine. Thanks!

**Pull request merged**
