### PR TITLE
Add dlib 19.10

### PR DESCRIPTION
**Pull request by xsacha**
* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/xsacha/hunter-h4uji
  * https://travis-ci.org/xsacha/hunter/builds/357186104

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3499
* https://travis-ci.org/ingenue/hunter/builds/357273181?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3501
* https://travis-ci.org/ingenue/hunter/builds/357287078?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.20.25

**Comment by xsacha** [comment]
Strange, I now try to use this in my project and get an error:
Unknown CMake command "check_required_components".

**Comment by ruslo** [comment]
```cmake
configure_file(cmake_utils/dlibConfig.cmake.in "${CMAKE_CURRENT_BINARY_DIR}/config/dlibConfig.cmake" @ONLY)
```

@xsacha Should be `configure_package_config_file` , not just `configure_file`. I think that current testing use all dependencies and `check_required_components` loaded from one of the `find_package` calls from Config.cmake.in. I guess you have minimal configuration without dependencies.

**Comment by xsacha** [comment]
That's true, we configure without any dependencies but I didn't have any issues on 19.8.
It's very confusing because dlib previously didn't have a configure/install and has just added it in 19.10.
I tried to keep as much the same from upstream as possible but enough from Hunter so it works fine with Hunter.

**Comment by ruslo** [comment]
> I tried to keep as much the same from upstream as possible but enough from Hunter so it works fine with Hunter.

This change is not Hunter related, it's worth adding it upstream.

**Pull request merged**
