### PR TITLE
Update lmdb to add dependency on Threads

### PR DESCRIPTION
**Pull request by isaachier**

### CODE REVIEW

**Comment by isaachier** [comment]
Seem to build fine (not 100% done yet):
https://travis-ci.org/isaachier/hunter/builds/313241623
https://ci.appveyor.com/project/isaachier/hunter/build/1.0.311

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2947
* https://travis-ci.org/ingenue/hunter/builds/313245420?utm_source=github_status&utm_medium=notification

> not 100% done yet

Yep, still 800+ jobs backlog for OSX machines on Travis...

**Comment by isaachier** [comment]
OK I'll cancel mine in that case to save some time.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2948
* https://travis-ci.org/ingenue/hunter/builds/313282923?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.185

**Pull request merged**
