### PR TITLE
Add OpenCV 3.2.0-p1 package

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by xsacha** [comment]
Done. Thanks for quick response :)

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1518
* https://travis-ci.org/ingenue/hunter/builds/218335235

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1519
* https://travis-ci.org/ingenue/hunter/builds/218360906

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.18.36

**Pull request merged**
