### PR TITLE
OpenCV-Extra: 3.2.0 + examples

### PR DESCRIPTION
**Pull request by ikliashchou**

### CODE REVIEW

**Comment by ikliashchou** [comment]
I've asked already [here](https://github.com/ruslo/hunter/issues/840) but just to check once again: should I make PR wth travis/appveyor changes to pkg.opencv or you will add extra testing branch pkg.opencv-extra?

**Comment by ruslo** [comment]
>  should I make PR wth travis/appveyor changes to pkg.opencv or you will add extra testing branch pkg.opencv-extra?

I will add pkg.opencv-extra

Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2146
* https://travis-ci.org/ingenue/hunter/builds/263971372?utm_source=github_status&utm_medium=notification

**Comment by ikliashchou** [comment]
I see some tests are failing. Like Android build is failed on Linux while correctly build on OS X. 
Also some issues on older MSCV.
OSX and iOS are failed as well, but I know that they are building no problem , as I use them in the project with this 3.2 version.

What do we do next? On some builds the log is truncated and I don't see the reason why it actually failed.

**Comment by ruslo** [comment]
I'm testing it in different branch, I will add details when finish.

**Comment by ruslo** [comment]
Passed:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2163
* https://travis-ci.org/ingenue/hunter/builds/264628853?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2165
* https://travis-ci.org/ingenue/hunter/builds/264653221?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.70

**Pull request merged**
