### PR TITLE
add gemmlowp + test

### PR DESCRIPTION
**Pull request by headupinclouds**
* header only interface
* needs C++11

Note: Won't be merged until after 11/9
@xsacha, @d4nst, @roscopecoltran : for tensorflow

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2709
* https://travis-ci.org/ingenue/hunter/builds/299722918?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2720
* https://travis-ci.org/ingenue/hunter/builds/299845480?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Thanks

**Comment by ruslo** [comment]
Follow-up: https://github.com/ruslo/hunter/commit/8df5394679af3c1461b3492c10e07c6497ee5322

Released: https://github.com/ruslo/hunter/releases/tag/v0.19.145

**Pull request merged**
