### PR TITLE
Add sleef 3.3.1

### PR DESCRIPTION
**Pull request by xsacha**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/xsacha/hunter-h4uji/builds/23059109
  * https://travis-ci.org/xsacha/hunter/builds/506059371

* I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch,
  see this merged pull request https://github.com/ingenue/hunter/pull/342

* My change will resolve this "New package" request: https://github.com/ruslo/hunter/issues/1763

### CODE REVIEW

**Comment by xsacha** [comment]
There's the docs :) Didn't realise we need to add this now. I should probably add docs for some older packages?

**Comment by ruslo** [comment]
> I have a feeling the docs are something that should be automated upon merge considering they need PR# too.

As I said [here](https://github.com/ingenue/hunter/pull/341#issuecomment-471931691) already, feel free to work on it.

> There's the docs :) Didn't realise we need to add this now.

Commit Sep 18, 2017, "Add documentation" part: https://github.com/ruslo/hunter/commit/024440ebbd0f79b199df4f9214cfb6d928d9e5f5?diff=unified

> I should probably add docs for some older packages?

I don't see any packages added by you from scratch. You were sending updates or fixes usually. On updates there is no need to touch documentation or example. However if you see "This page is a template and contains no real information" warning (like https://docs.hunter.sh/en/latest/packages/pkg/CLAPACK.html) feel free to fix it.

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/23119983
- https://travis-ci.org/ingenue/hunter/builds/507123461?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/23120083
- https://travis-ci.org/ingenue/hunter/builds/507126936?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> I don't see any packages added by you from scratch. You were sending updates or fixes usually

I found this (was not using search correctly):
- https://github.com/ruslo/hunter/pull/830 (docs fixes https://github.com/ruslo/hunter/commit/11ffb5c0c9a0136ca5209895b633b66e205f1aa2)
- https://github.com/ruslo/hunter/pull/828 (need to adapt to [this](https://raw.githubusercontent.com/ruslo/hunter/master/docs/packages/pkg/foo.rst) template)
- https://github.com/ruslo/hunter/pull/815 (docs fixes https://github.com/ruslo/hunter/commit/20db4840ed9462bf8f9dd16b24386812560fc322)

**Comment by xsacha** [comment]
Yeah they weren't tagged back then.
Things like libxml: https://github.com/ruslo/hunter/pull/676/files

**Comment by ruslo** [comment]
Docs: https://docs.hunter.sh/en/latest/packages/pkg/sleef.html

Released: https://github.com/ruslo/hunter/releases/tag/v0.23.133

**Pull request merged**
