### PR TITLE
create github release for latest thread-pool-cpp

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2151
* https://travis-ci.org/ingenue/hunter/builds/264239670?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Thanks.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2155
* https://travis-ci.org/ingenue/hunter/builds/264331701?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.69

**Pull request merged**
