### PR TITLE
updated cxxopts to 1.4.3

### PR DESCRIPTION
**Pull request by kumaakh**

### CODE REVIEW

**Comment by headupinclouds** [comment]
@kumaakh : Sorry to miss this one.  If the upstream release has no dependencies and has a full package config installation, then you can use it directly.  In many cases, the CMake needs to be updated for one of these two reasons, in which case a forks is typically added under hunter-packages.

You can check the commit history in the fork to see the changes that were required:

https://github.com/hunter-packages/cxxopts/commits/hunter

In this case a PR with the upstream code should be merged into the fork, and then a new release can be made and the URL + SHA1 can be added to the hunter recipe.

**Comment by headupinclouds** [comment]
This link provides some details for testing that the local hunter example will compile with the new package version: https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally

**Comment by ruslo** [comment]
Closing inactive pull request.

**Comment by hubert-lee** [comment]
@ruslo 
hello!!
I need latest version of cxxopts packages.
so, I test this issue(commit is ```cd22591```)
I have completed testing based on the information in this link.
(https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally)

I think, cxxopts 1.4.3 version perfectly was hunterized.
so, I hope this pull-request will merge to master branch.
Is it possible?

**Comment by ruslo** [comment]
> Is it possible?

@hubert-lee Of course, please open new pull request.

**Pull request closed without merging**
