### PR TITLE
update EOS package (Eigen -> Eigen3)

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1404
* https://travis-ci.org/ingenue/hunter/builds/207714563

**Comment by ruslo** [comment]
Sync `.travis.yml` with OpenCV dependency to fix build timeout:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1406
* https://travis-ci.org/ingenue/hunter/builds/207763467

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1408
* https://travis-ci.org/ingenue/hunter/builds/207826458

**Comment by headupinclouds** [comment]
Thanks

**Comment by ruslo** [comment]
Released https://github.com/ruslo/hunter/releases/tag/v0.18.11

**Pull request merged**
