### PR TITLE
Added wxWidgets.

### PR DESCRIPTION
**Pull request by alamaison**
Usage:
    hunter_add_package(wxWidgets)
    find_package(wxWidgets REQUIRED core base)
    include(${wxWidgets_USE_FILE})
    add_executable(foo foo.cpp)
    target_link_libraries(foo ${wxWidgets_LIBRARIES})

Depends on GTK and OpenGL (GL and GLU) on Linux.  GTK and OpenGL aren't in Hunter.

### CODE REVIEW

**Comment by ruslo** [comment]
Nice :)

**Comment by alamaison** [comment]
This doesn't Mac because the CMakeified wxWidgets hasn't had its OSX Bakefiles ported (we don't have Macs to test the result).  It may work if GTK is present, but that hasn't been tested.

**Comment by ruslo** [comment]
New page: https://github.com/ruslo/hunter/wiki/pkg.wxwidgets

**Comment by ruslo** [comment]
> Depends on GTK and OpenGL (GL and GLU) on Linux. GTK and OpenGL aren't in Hunter.

* https://github.com/ruslo/hunter/issues/119
* https://github.com/ruslo/hunter/issues/120

**Comment by ruslo** [comment]
> It may work if GTK is present, but that hasn't been tested.

I saved the note: https://github.com/ruslo/hunter/wiki/pkg.wxwidgets#issues

**Pull request merged**
