### PR TITLE
Update lehrfempp to 0.7.19

### PR DESCRIPTION
**Pull request by craffael**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/craffael/hunter/builds/23785368
  * https://travis-ci.org/craffael/hunter/builds/518969922

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/23794614
- https://travis-ci.org/ingenue/hunter/builds/519133683?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/23795429
- https://travis-ci.org/ingenue/hunter/builds/519144902?utm_source=github_status&utm_medium=notification

**Comment by craffael** [comment]
Thanks for the fast PR Review! Do you know when you will make the next release?

**Comment by ruslo** [comment]
> Do you know when you will make the next release?

I want to make it with Boost. Currently waiting for CI:
- https://ci.appveyor.com/project/ingenue/hunter/builds/23804112

Just for your info, you can always use any commit from history as URL in HunterGate without release:

```cmake
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/c51ec4864a8ec9d6776285c6498c25f752206b74.zip"
    SHA1 "c1ac2d7ae35fb02c9821d5e653cdd8ff618e6e5b"
)
```

**Comment by craffael** [comment]
Perfect, Thanks for the info!

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.153

**Pull request merged**
