### PR TITLE
Added SDL2 library

### PR DESCRIPTION
**Pull request by Cyberunner23**
Reference: #336 
New pull request for SDL2, moved SDL2 to new branch to prevent further issues when branching off to work on other packages.
SDL2 requested in: #280

### CODE REVIEW

**Comment by ruslo** [comment]
new testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.489
* https://travis-ci.org/ingenue/hunter/builds/137520250

**Comment by ruslo** [comment]
> new testing:

@Cyberunner23 some tests failed: https://travis-ci.org/ingenue/hunter/builds/137520250

**Comment by Cyberunner23** [comment]
There are talks upstream about refactoring the CMake build system, I'm currently working on some bits that will include the patch to make it produce the config files for find_package(CONFIG) to hopefully push it upstream.

**Comment by Cyberunner23** [comment]
Merged?

**Comment by ruslo** [comment]
> Merged?

Hm... what a heck...

**Comment by ruslo** [comment]
> Hm... what a heck...

Probably this is because you have `3d08788` in https://github.com/ruslo/hunter/pull/440 so there is no sense to keep this pull request openned so it was closed automatically.

**Comment by ruslo** [comment]
> it was closed automatically

Just to clarify: from the git point of view this patches already contain in #440, git doesn't care that you removed SDL2 updates. You have to create new history.

**Comment by Cyberunner23** [comment]
ohh ok I see, I'll fix it somehow

**Pull request merged**
