### PR TITLE
Add BUILD_SHARED_LIBS support to OpenSSL 1.1+ Windows

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by xsacha** [comment]
Updated.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2730
* https://travis-ci.org/ingenue/hunter/builds/300068201?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2733
* https://travis-ci.org/ingenue/hunter/builds/300124728?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.147

**Pull request merged**
