### PR TITLE
Add jaegertracing package

### PR DESCRIPTION
**Pull request by isaachier**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/isaachier/hunter/build/1.0.501
  * https://travis-ci.org/isaachier/hunter/builds/382440239

* I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch,
  see this merged pull request https://github.com/ingenue/hunter/pull/259

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4013
* https://travis-ci.org/ingenue/hunter/builds/382571326?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4014
* https://travis-ci.org/ingenue/hunter/builds/382587749?utm_source=github_status&utm_medium=notification

**Comment by isaachier** [comment]
Awesome thanks!

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.21.12

**Pull request merged**
