### PR TITLE
Add ceres-solver with SuiteSparse

### PR DESCRIPTION
**Pull request by NeroBurner**
adds ceres-solver `1.12.0-p1` which has the ability to use hunter's SuiteSparse

as stated in the example just set the CMake flag `SUITESPARSE` in `config.cmake`. The example explicitly uses a sparse solver. If a ceres-solver is used without Sparse support an error will be thrown at runtime.

because of the dependency on `LAPACK` the using Project needs to define either `enable_language(Fortran)` or build `LAPACK` as shared library by adding to `config.cmake`
```
hunter_config(LAPACK
  VERSION ${HUNTER_LAPACK_VERSION}
  CMAKE_ARGS BUILD_SHARED_LIBS=ON
)
```

finishes issue #855

### CODE REVIEW

**Comment by ruslo** [comment]
Testing `ceres-solver`:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2004
* https://travis-ci.org/ingenue/hunter/builds/256857168?utm_source=github_status&utm_medium=notification

I've created `ceres-solver-suitesparse` with the same set of toolchains. Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2005
* https://travis-ci.org/ingenue/hunter/builds/256858305?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing ceres-solver

All toolchains failed because of Fortran compiler requirement. Previous version was working without Fortran:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2007
* https://travis-ci.org/ingenue/hunter/builds/256859598?utm_source=github_status&utm_medium=notification

**Comment by NeroBurner** [comment]
pushed a fix

the CMake flags `LAPACK` and `SUITESPARSE` both default to `ON`. I forgot to disable `LAPACK`

To build ceres-solver with sparse support both `LAPACK` and `SUITESPARSE` flags need to be set

**Comment by NeroBurner** [comment]
ceres-solver with suitesparse examples won't build on windows. There is no mingw compiler for ceres-solver, but we need mingw because of the gfortran dependency
I think mingw is disabled because glog was not compilable with mingw, but the current version (in hunter) should be

**Comment by ruslo** [comment]
> we need mingw because of the gfortran dependency

I'm pretty sure that Fortran compiler from MinGW is not compatible with Visual Studio.

> I think mingw is disabled because glog was not compilable with mingw, but the current version (in hunter) should be

You can send pull request to pkg.ceres-solver-suitesparse branch to enable it after this pull request will be merged.

ceres-solver:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2012
* https://travis-ci.org/ingenue/hunter/builds/256903926?utm_source=github_status&utm_medium=notification

ceres-solver-suitesparse:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2013
* https://travis-ci.org/ingenue/hunter/builds/256904282?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
`ceres-solver` looks good now. `ceres-solver-suitesparse` failed on all windows toolchains (should use `dummy` in `appveyor.yml`), `clang-libstdcxx` failed on Linux (don't know why), `osx-10-11` failed on OSX (don't know why too, strange that `libcxx` is working).

**Comment by NeroBurner** [comment]
for `osx-10-11` the fortran compiler was not fount (most likely not installed/specified in toolchain)
https://travis-ci.org/ingenue/hunter/jobs/256904309#L752

for `clang-libstdcxx` the fortran compiler is broken, I have no Idea why that is
https://travis-ci.org/ingenue/hunter/jobs/256904291#L1100

**Comment by NeroBurner** [comment]
osx build disabled
https://github.com/ingenue/hunter/pull/96

**Comment by NeroBurner** [comment]
> for clang-libstdcxx the fortran compiler is broken, I have no Idea why that is
https://travis-ci.org/ingenue/hunter/jobs/256904291#L1100

It seems we have to set `CMAKE_Fortran_COMPILER` to gfortran, otherwise cmake tries to use /usr/bin/f95` which is not working
https://stackoverflow.com/a/25504388

**Comment by ruslo** [comment]
For reference, depends on https://github.com/ruslo/polly/pull/163

**Comment by ruslo** [comment]
ceres-solver:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2019
* https://travis-ci.org/ingenue/hunter/builds/257290771?utm_source=github_status&utm_medium=notification

ceres-solver-suitesparse:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2020
* https://travis-ci.org/ingenue/hunter/builds/257290909?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> For reference, depends on ruslo/polly#163

Doesn't work, reverted.

`ceres-solver` works, some `ceres-solver-suitesparse` failed. My suggestion:
* exclude all windows toolchains, leave only `dummy` toolchain
* exclude `clang-libstdcxx` on Linux

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2026
* https://travis-ci.org/ingenue/hunter/builds/257349117?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Package is not cacheable - no upload step. Released: https://github.com/ruslo/hunter/releases/tag/v0.19.40

**Pull request merged**
