### PR TITLE
Add: cpp_redis

### PR DESCRIPTION
**Pull request by szatan**
Adds cpp_redis, a Redis client from https://github.com/Cylix/cpp_redis

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1684
* https://travis-ci.org/ingenue/hunter/builds/230748653?utm_source=github_status&utm_medium=notification

**Comment by szatan** [comment]
Most of the tests in https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1684 fail, but I have no idea why. Most of the time the output just says that the build failed without providing any further explanation.

I'd rather have passing tests than exclude/disable them, but I don't know how to approach it.
Could you point me in the right direction?

**Comment by ruslo** [comment]
> the output just says that the build failed without providing any further explanation

I guess they are executed in parallel and you have to move a little bit upper. First toolchain that failed on Windows:
```
tcp_client_iface.hpp(41) : error C2039: 'uint32_t' : is not a member of 'std'
```

It's missing `#include <cstdint>` I think:
* http://en.cppreference.com/w/cpp/types/integer

**Comment by ruslo** [comment]
I guess if you want to debug toolchains you can comment out all tests except one in your fork and run tests one by one. Some hints can be found in this comment:
* https://github.com/ruslo/hunter/pull/742#issuecomment-293812754

**Comment by szatan** [comment]
This looks like something that should be fixed in the cpp_redis upstream.
I think the best course of action would be to exclude the tests for now, and bug the upstream guys to fix it.
Then, once it's handled, I'll just update the hunterized version of cpp_redis.

Would that be ok with you?

**Comment by ruslo** [comment]
> Would that be ok with you?

Sure, no problems.

**Comment by szatan** [comment]
ok. I pushed the exclusion PR: https://github.com/ingenue/hunter/pull/71

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1688
* https://travis-ci.org/ingenue/hunter/builds/230785934?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1689
* https://travis-ci.org/ingenue/hunter/builds/231064316?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released:
* https://github.com/ruslo/hunter/releases/tag/v0.18.51

**Pull request merged**
