### PR TITLE
Fixed race condition in libsodium's build schemes.

### PR DESCRIPTION
**Pull request by Cyberunner23**

### CODE REVIEW

**Comment by ruslo** [comment]
I think that same protection should be added to `url_sha1_libsodium_autogen_autotools.cmake.in` too

**Comment by Cyberunner23** [comment]
Indeed, give me a second.

**Comment by ruslo** [comment]
Testing only Ninja: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.571

**Comment by Cyberunner23** [comment]
Test passed

**Comment by ruslo** [comment]
> Test passed

Cool. Let's do full testing now:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.572
* https://travis-ci.org/ingenue/hunter/builds/138757343

**Comment by Cyberunner23** [comment]
All tests passed, we're good to go.

**Comment by ruslo** [comment]
Uploading binaries:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.573 (almost all uploaded in fact, run ninja upload)
* https://travis-ci.org/ingenue/hunter/builds/138765077 (all uploaded in fact, just check)

**Comment by ruslo** [comment]
> Uploading binaries

Done. Released: https://github.com/ruslo/hunter/releases/tag/v0.14.27

**Pull request merged**
