### PR TITLE
Update 'Assimp' to 5.0.0-07779a7a

### PR DESCRIPTION
**Pull request by rbsheth**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/rbsheth/hunter/builds/25599494
  * https://travis-ci.com/rbsheth/hunter/builds/117221059

* This update will break few old toolchains but fix others.
  Updated in this pull request: https://github.com/ingenue/hunter/pull/377

@ruslo Updated to new version here, then we can merge testing changes.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/25674613
- https://travis-ci.org/ingenue/hunter/builds/552984728?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.198

**Comment by NukeBird** [comment]
@rbsheth THANK YOU SO MUCH!
I wasn't able to use assimp at Win64, and now everything fixed. Amazing!

**Comment by rbsheth** [comment]
@NukeBird Haha, thanks! Happy to help out. :)

**Pull request merged**
