### PR TITLE
Added package glfw

### PR DESCRIPTION
**Pull request by pretyman**
Not ready yet. 

Facing problem when building `glfw-Release`. Извините, голова плохо работает, can't figure it out myself.

Building with CMake 3.5 from your docker environment gives: 
```
-- Using X11 for window creation
-- [hunter *** DEBUG *** 2016-07-26T05:11:14] Single-configuration generator
-- [hunter *** DEBUG *** 2016-07-26T05:11:14] List of cache servers:
-- [hunter *** DEBUG *** 2016-07-26T05:11:14]   * https://github.com/ingenue/hunter-cache
-- [hunter *** DEBUG *** 2016-07-26T05:11:14] Settings (finalize):
-- [hunter *** DEBUG *** 2016-07-26T05:11:14]   HunterGate done (YES)
-- [hunter *** DEBUG *** 2016-07-26T05:11:14]   Cache init (YES)
-- [hunter *** DEBUG *** 2016-07-26T05:11:14] Reuse cached values
-- [hunter] HUNTER_ROOT: /home/travis/hunter/_testing/Hunter
-- [hunter *** DEBUG *** 2016-07-26T05:11:14] HUNTER_TOOLCHAIN_ID_PATH: /home/travis/hunter/_testing/Hunter/_Base/d76160c/6c9a4aa/8928885
-- [hunter *** DEBUG *** 2016-07-26T05:11:14] HUNTER_CONFIGURATION_TYPES: Release;Debug
-- [hunter] [ Hunter-ID: d76160c | Config-ID: 6c9a4aa | Toolchain-ID: 8928885 ]
CMake Error at /home/travis/hunter/_testing/Hunter/_Base/d76160c/6c9a4aa/config.cmake:1 (include):
  include could not find load file:

    hunter_config
Call Stack (most recent call first):
  /home/travis/hunter/_testing/Hunter/_Base/Download/Hunter/unknown/d76160c/Unpacked/cmake/modules/hunter_finalize.cmake:128 (include)
  /home/travis/hunter/_testing/Hunter/_Base/Download/Hunter/unknown/d76160c/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:196 (hunter_add_package)


CMake Error at /home/travis/hunter/_testing/Hunter/_Base/d76160c/6c9a4aa/config.cmake:2 (hunter_config):
  Unknown CMake command "hunter_config".
Call Stack (most recent call first):
  /home/travis/hunter/_testing/Hunter/_Base/Download/Hunter/unknown/d76160c/Unpacked/cmake/modules/hunter_finalize.cmake:128 (include)
  /home/travis/hunter/_testing/Hunter/_Base/Download/Hunter/unknown/d76160c/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:196 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/home/travis/hunter/_testing/Hunter/_Base/d76160c/6c9a4aa/8928885/Build/glfw/Build/glfw-Release-prefix/src/glfw-Release-build/CMakeFiles/CMakeOutput.log".
See also "/home/travis/hunter/_testing/Hunter/_Base/d76160c/6c9a4aa/8928885/Build/glfw/Build/glfw-Release-prefix/src/glfw-Release-build/CMakeFiles/CMakeError.log".
make[2]: Leaving directory `/home/travis/hunter/_testing/Hunter/_Base/d76160c/6c9a4aa/8928885/Build/glfw/Build'
```

Would you be so kind to check out this branch and have a look?

The hunterized `glfw` being built is at: https://github.com/pretyman/glfw - maybe I did something silly, but I started it from scratch because it was giving the same error previously.

Thanks

### CODE REVIEW

**Comment by ruslo** [comment]
The reason is about modification of `CMAKE_MODULE_PATH`. This is kind of scenario describled here: http://cgold.readthedocs.io/en/latest/tutorials/cmake-sources.html#modify-incorrect. Fix: http://cgold.readthedocs.io/en/latest/tutorials/cmake-sources.html#modify-correct. Under the hood `HunterGate` modify `CMAKE_MODULE_PATH` so we can do load custom modules, hence if user modify such path ignoring current value we will have a problems.

Also I noticed `set(CMAKE_LEGACY_CYGWIN_WIN32 OFF)`. It's not needed since minimum versoin is higher than `2.8.4` but `cmake_minimum_required` is not the first command so we have to use such variable. It should be fixed, see http://cgold.readthedocs.io/en/latest/tutorials/version-policies.html#cmake-minimum-required

**Comment by pretyman** [comment]
Thanks Ruslan!! Oh my god, that was so basic, I really need to fire myself, but I yet haven't figured out how to...

Tonight I'll continue this package

**Comment by pretyman** [comment]
Update this pr. I haven't created a tag yet in https://github.com/hunter-packages/glfw , but is it possible to run AppVeyor tests on this pr? I can't test on Windows at the moment and would like to see if it compiles at least before tagging..

**Comment by pretyman** [comment]
In Linux, all dependencies build statically except for OpenGL package. Can be installed on fedora with `sudo dnf install mesa-libGL-devel`, but it brings all X11 dependencies building dynamically to them. I wonder if something will explode on glfw since it links statically to `x11` packages and dynamically to `libGL` which in turn links to the dynamic libraries of the system's `X11`.

**Comment by ruslo** [comment]
> but is it possible to run AppVeyor tests on this pr?

Sure, let's run all of them and see what will happen:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.755
* https://travis-ci.org/ingenue/hunter/builds/149738798

> I wonder if something will explode on glfw since it links statically to x11 packages and dynamically to libGL which in turn links to the dynamic libraries of the system's X11

It's not good but works fine the last time I've checked - we have same problem with Qt.

> Can be installed on fedora with sudo dnf install mesa-libGL-devel

As far as I remember Fedora and Ubuntu have different path to OpenGL libraries. This one may be the problem if Toolchain-ID will match and binaries from Ubuntu server will be used on Fedora.

**Comment by pretyman** [comment]
> https://ci.appveyor.com/project/ingenue/hunter/build/1.0.755

Cool, thanks! Is `TOOLCHAIN=vs-14-2015, PROJECT_DIR=examples\glfw` a 32bit build? If so, is there a special reason to not test for 64bit build on `vs-14-2015`? I see that on exists in https://github.com/ruslo/polly under `vs-14-2015-win64.cmake`, I guess I can just open a pull request for the appveyor.yml adding a toolchain `vs-14-2015-win64` if there are no restrictions to it.

> As far as I remember Fedora and Ubuntu have different path to OpenGL libraries. This one may be the problem if Toolchain-ID will match and binaries from Ubuntu server will be used on Fedora.

Hum.. should we disable caching of this package then?

**Comment by ruslo** [comment]
>  guess I can just open a pull request for the appveyor.yml adding a toolchain vs-14-2015-win64 if there are no restrictions to it

Merged.

> Hum.. should we disable caching of this package then?

It will make impossible to set dependent package as cacheable. In means we have to mark package like Qt uncacheable then. Let it be so for now, the right fix is to add mesa OpenGL libraries to Hunter.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.762
* https://travis-ci.org/ingenue/hunter/builds/149982629

**Comment by ruslo** [comment]
> Testing

Looks great! Please create a glfw release and I will merge it.

**Comment by pretyman** [comment]
> In means we have to mark package like Qt uncacheable then. 

What about using `HUNTER_USE_CACHE_SERVERS=NO` when using this package? So it is built and cached locally.

**Comment by ruslo** [comment]
> What about using HUNTER_USE_CACHE_SERVERS=NO when using this package? So it is built and cached locally

Well I do want to have Qt cache on server so I can test packages using CI services.

**Comment by pretyman** [comment]
> Looks great! Please create a glfw release and I will merge it. 

Done, thanks. Updated this pr, let's see how the tests go because I updated `PACKAGE_UNRELOCATABLE_TEXT_FILES`

**Comment by pretyman** [comment]
Oh noooooooooooooo, I just noticed I opened this pr against the `master`, let me open against the `develop` branch

**Comment by ruslo** [comment]
> let's see how the tests go

* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.764
* https://travis-ci.org/ingenue/hunter/builds/150065601

**Pull request closed without merging**
