### PR TITLE
register Poco release 1.7.6-p0

### PR DESCRIPTION
**Pull request by Ubiquite**
hunterized Poco release

### CODE REVIEW

**Comment by ruslo** [comment]
You have to update `cmake/configs/default.cmake` too.

**Comment by Ubiquite** [comment]
is it ok ?

**Comment by ruslo** [comment]
> is it ok ?

You mean I can test it now? :) Please leave an explicit comment about the fact that update ready to be tested, since I don't know if the new commits have work-in-progress status/ready status (or even accidentally pushed).

* https://travis-ci.org/ingenue/hunter/builds/177100993
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1184

**Comment by Ubiquite** [comment]
Okey, for information we already use it throught a temporary release made from my clone.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1186
* https://travis-ci.org/ingenue/hunter/builds/177148744

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.16.31

**Pull request merged**
