### PR TITLE
Update fmt to 4.0.0

### PR DESCRIPTION
**Pull request by ikliashchou**
fmtlib 4.0.0 [release notes](https://github.com/fmtlib/fmt/releases/tag/4.0.0)

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1914
* https://travis-ci.org/ingenue/hunter/builds/250314495?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

One toolchain failed. Feel free to exclude it from `.travis.yml`. Send pull request to [pkg.fmt](https://github.com/ingenue/hunter/tree/pkg.fmt) in this case.

**Comment by ruslo** [comment]
> revert set (CMAKE_CXX_STANDARD 11)

Do you want me to retest this version?

**Comment by ikliashchou** [comment]
I submitted pull request as you suggested to [pkg.fmt](https://github.com/ingenue/hunter/pull/88).

Please retest

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1932
* https://travis-ci.org/ingenue/hunter/builds/251443738?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1933
* https://travis-ci.org/ingenue/hunter/builds/251456441?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.25

**Pull request merged**
