### PR TITLE
Update ceres-solver to 1.14.0

### PR DESCRIPTION
**Pull request by NeroBurner**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/NeroBurner/hunter/builds/20954214
  * https://travis-ci.org/NeroBurner/hunter/builds/466489924

---

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/builds/20955793
* https://travis-ci.org/ingenue/hunter/builds/466991121?utm_source=github_status&utm_medium=notification

**Comment by NeroBurner** [comment]
testing finished :)

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/builds/20960105
* https://travis-ci.org/ingenue/hunter/builds/467061962?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.72

**Comment by ruslo** [comment]
Got problem with `ceres-solver-suitesparse` example:
* https://travis-ci.org/ingenue/hunter/jobs/467488050

```
make[2]: *** No rule to make target '/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/80a87a0/239e635/2dfe9e9/Install/lib/libcxsparse.a', needed by 'foo'.  Stop.
```

Dependent `suitesparse` libraries not handled correctly (full path used instead of imported libraries):

```
> wget https://github.com/ingenue/hunter-cache/releases/download/cache-1d5d63e/1d5d63e52120183d95d4e194a2b07525ec3b5851.tar.bz2
> tar xf 1d5d63e52120183d95d4e194a2b07525ec3b5851.tar.bz2
> grep -IR _Base lib/cmake

lib/cmake/Ceres/CeresTargets-debug.cmake:  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "glog::glog;SuiteSparse::spqr;SuiteSparse::cholmod;SuiteSparse::ccolamd;SuiteSparse::camd;SuiteSparse::colamd;SuiteSparse::amd;/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/80a87a0/239e635/2dfe9e9/Install/lib/libcxsparse.a;lapack;gomp"
lib/cmake/Ceres/CeresTargets-release.cmake:  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "glog::glog;SuiteSparse::spqr;SuiteSparse::cholmod;SuiteSparse::ccolamd;SuiteSparse::camd;SuiteSparse::colamd;SuiteSparse::amd;/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/80a87a0/239e635/2dfe9e9/Install/lib/libcxsparse.a;lapack;gomp"
```

I will exclude `ceres-solver-suitesparse` example from testing for now: https://github.com/ingenue/hunter/commit/9a31b47053900c720d0847ebb5d1f7933ddaca53 feel free to enable it back after fix.

**Pull request merged**
