### PR TITLE
Added package odb-boost

### PR DESCRIPTION
**Pull request by pretyman**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.192
* https://travis-ci.org/ingenue/hunter/builds/114990294

**Comment by pretyman** [comment]
Not sure you realized that you merged before testing finished.

Appveyor jobs have been taking 12 hours to kick in, though.

**Comment by ruslo** [comment]
> Not sure you realized that you merged before testing finished

Yep, trying new policy. Since it's new package then passed/failed tests will show nothing, so I'm just merging first.

**Comment by pretyman** [comment]
I will remove the broken tests this weekend, ok? Busy with deadlines until Saturday.

**Comment by ruslo** [comment]
> I will remove the broken tests this weekend, ok?

Sure, no problems

**Comment by pretyman** [comment]
I removed the tests for appveyor, can you re-run the tests? I want to know what will fail in travis after the SQLite3 fix

**Comment by pretyman** [comment]
OSX libstdcxx is failing with 
```
libtool: compile:  /usr/bin/clang++ -DHAVE_CONFIG_H -I.. -I.. -DLIBODB_DYNAMIC_LIB -std=c++11 -stdlib=libstdc++ -D_THREAD_SAFE -MT database.lo -MD -MP -MF .deps/database.Tpo -c database.cxx -o database.o

In file included from database.cxx:5:

../odb/database.hxx:20:12: fatal error: 'type_traits' file not found

#  include <type_traits> // std::enable_if, std::is_convertible
```
No clue why

**Comment by ruslo** [comment]
> can you re-run the tests?

Done: https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=odb-boost

**Comment by ruslo** [comment]
> OSX libstdcxx is failing with

It would be nice to create SSCCE to prove that this stuff is broken on Travis OSX instances and there is no easy way to apply workaround (like just run `brew update && brew upgrade`). Also it would be useful to check when/either it fixed. I have a bunch of repos for such job:
* https://github.com/travis-ci-tester

But waiting for start like a day already, see [comment](https://github.com/ruslo/hunter/pull/352#issuecomment-196124238).

**Comment by ruslo** [comment]
Failed stuff on Travis ready:
* https://travis-ci.org/ingenue/hunter/builds/115865239

**Comment by pretyman** [comment]
clang-analyze fails for every `autotools` based project:
```
[ 62%] Performing configure step for 'odb'
cd /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/3cf0a6a/c2dfc9b/6b1dade/Build/odb/Source && . /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/Download/Hunter/unknown/3cf0a6a/Unpacked/scripts/clear-all.sh && AR=/usr/bin/ar ./configure AR=/usr/bin/ar LD=/usr/bin/ld NM=/usr/bin/nm OBJCOPY=/usr/bin/objcopy OBJDUMP=/usr/bin/objdump RANLIB=/usr/bin/ranlib STRIP=/usr/bin/strip CC=/home/travis/build/ingenue/hunter/polly-master/scripts/clang-analyze.sh CXX=/home/travis/build/ingenue/hunter/polly-master/scripts/clangxx-analyze.sh CXXFLAGS=-std=c++11 --disable-shared --enable-static --prefix=/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/3cf0a6a/c2dfc9b/6b1dade/Install
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking for style of include used by make... GNU
checking for gcc... /home/travis/build/ingenue/hunter/polly-master/scripts/clang-analyze.sh
checking whether the C compiler works... no
configure: error: in `/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/3cf0a6a/c2dfc9b/6b1dade/Build/odb/Source':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[2]: Leaving directory `/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/3cf0a6a/c2dfc9b/6b1dade/Build/odb/Build'
make[2]: *** [odb-prefix/src/odb-stamp/odb-configure] Error 77
make[1]: *** [CMakeFiles/odb.dir/all] Error 2
make[1]: Leaving directory `/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/3cf0a6a/c2dfc9b/6b1dade/Build/odb/Build'
make: *** [all] Error 2
```

**Comment by ruslo** [comment]
> See `config.log' for more details

I guess it need to be tried locally to see what is the problem exactly

Feel free to delete this stuff from matrix.

**Comment by pretyman** [comment]
https://github.com/ruslo/hunter/blob/master/scripts/autotools-merge-lipo.cmake.in might need some love as well. I can't look at it now, but I will surely end up looking at it on the future. It fails with:

```
echo "Performing install step for 'odb-universal'"

Performing install step for 'odb-universal'

cd /Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/2e84cf9/c2dfc9b/097785c/Build/odb/Source/universal && /Users/travis/build/ingenue/hunter/_ci/cmake/bin/cmake -P /Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/2e84cf9/c2dfc9b/097785c/Build/odb/Source/universal/autotools-merge-lipo.cmake

CMake Error at autotools-merge-lipo.cmake:234 (message):

  lipo execution failed: fatal error: lipo: can't figure out the architecture

  type of:

  /Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/2e84cf9/c2dfc9b/097785c/Build/odb/Build/multi-arch/armv7/lib/pkgconfig/libodb.pc









make: *** [/Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/2e84cf9/c2dfc9b/097785c/Build/odb/Build/odb-universal-prefix/src/odb-universal-stamp/Debug-iphoneos/odb-universal-install] Error 1

Command /bin/sh failed with exit code 2



** BUILD FAILED **
```

**Comment by ruslo** [comment]
> might need some love as well

Already have discussed this issue, can't find where...

**Comment by ruslo** [comment]
> OSX libstdcxx is failing with ... No clue why

Lack of `c++11`:
* https://github.com/travis-ci-tester/travis-test-clang-mac-cxx-11
* https://travis-ci.org/travis-ci-tester/travis-test-clang-mac-cxx-11/builds/116384451

Feel free to remove

**Pull request merged**
