### PR TITLE
udpate dlib to 19.2-p1

### PR DESCRIPTION
**Pull request by headupinclouds**
* resubmit earlier hunter PR from @xsacha
* use 19.2-p1 instead of v19.2-p1 to match earlier syntax

### CODE REVIEW

**Comment by xsacha** [comment]
Thanks :)

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1293
* https://travis-ci.org/ingenue/hunter/builds/188517426

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1294
* https://travis-ci.org/ingenue/hunter/builds/188529085

**Comment by ruslo** [comment]
Released:
* https://github.com/ruslo/hunter/releases/tag/v0.17.12

**Pull request merged**
