### PR TITLE
Add Beast package and example.

### PR DESCRIPTION
**Pull request by xsacha**
Ready to merge.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1816
* https://travis-ci.org/ingenue/hunter/builds/240850836?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
I've also hunterised b50 but it is very different to b32 so I think it should have its own branch: hunter-packages/Beast:hunter-b50

**Comment by xsacha** [comment]
Is there an easy way to restrict ingenue to only test platforms Boost compiles on?

**Comment by ruslo** [comment]
As usual, send pull request with excluded toolchains to ingenue/hunter@pkg.beast

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1822
* https://travis-ci.org/ingenue/hunter/builds/241169461?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
Looks like only vs2015 for this project.
Linux needs to be told to use c++11 somewhere.

**Comment by ruslo** [comment]
> Linux needs to be told to use c++11 somewhere

If you're talking about `default` toolchain then just exclude it. This toolchain designed to be used without any extra flags.

> Looks like only vs2015 for this project

Excluding it will be the easiest solution. You can always fix issues later.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1828
* https://travis-ci.org/ingenue/hunter/builds/241192431?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
I excluded it and all working but a bit curious about default toolchain. If the toolchain is designed to be used without flags but a package requires a certain flag, shouldn't that package add that flag to its own build?

**Comment by ruslo** [comment]
> shouldn't that package add that flag to its target?

Global entities should go to global places. In this case it should be toolchain.
Take a look at this example:
* http://cgold.readthedocs.io/en/latest/tutorials/libraries/symbols/odr-global.html

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1833
* https://travis-ci.org/ingenue/hunter/builds/241513110?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.9

**Pull request merged**
