### PR TITLE
Update SDL2 to 2.0.7.

### PR DESCRIPTION
**Pull request by Predelnik**

### CODE REVIEW

**Comment by ruslo** [comment]
SDL2 testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3120
* https://travis-ci.org/ingenue/hunter/builds/319861192?utm_source=github_status&utm_medium=notification

Urho3D testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3121
* https://travis-ci.org/ingenue/hunter/builds/319861312?utm_source=github_status&utm_medium=notification

**Comment by Predelnik** [comment]
So it looks like MSVC gives error due to not finding SDL2Config.cmake, it was disabled for win32 but ias I tested it's needed for MinGW compilation. I could disable it for MSVC only but locally it seems to use that config fine.

**Comment by Predelnik** [comment]
Updated to p1.

**Comment by ruslo** [comment]
SDL2 testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3127
* https://travis-ci.org/ingenue/hunter/builds/320686524?utm_source=github_status&utm_medium=notification

Urho3D testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3128
* https://travis-ci.org/ingenue/hunter/builds/320686677?utm_source=github_status&utm_medium=notification

**Comment by Predelnik** [comment]
Did this one failed because log is too big?
https://travis-ci.org/ingenue/hunter/jobs/320686678

**Comment by ruslo** [comment]
> Did this one failed because log is too big?

Yes, and it's big because we got cache miss, e.g. with Boost:
* https://travis-ci.org/ingenue/hunter/jobs/320686678#L1655

Looks like these extra packages affect `Toolchain-ID` value of `clang-libstdcxx` toolchain:
* https://github.com/ingenue/hunter/blob/14757cc2922e85ae3cf83dec364f5bd60347fc3f/.travis.yml#L21-L22

Which is a cause of cache miss. It have to be improved but not related to new version of SDL2.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3129
* https://travis-ci.org/ingenue/hunter/builds/320701619?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.210

**Pull request merged**
