### PR TITLE
glog: update to version 0.3.5-p1

### PR DESCRIPTION
**Pull request by NeroBurner**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2298
* https://travis-ci.org/ingenue/hunter/builds/270771404?utm_source=github_status&utm_medium=notification

**Comment by NeroBurner** [comment]
three Apple builds are failing. They all have been terminated

**Comment by ruslo** [comment]
> Testing

Some windows tests failed.

> three Apple builds are failing. They all have been terminated

It's unit-tests, nothing bad.

**Comment by NeroBurner** [comment]
all windows tests below vs-14 2015 are failing with an error like this
```
C:\projects\hunter\_testing\Hunter\_Base\50c7ee6\0cc91fa\7ededb5\Build\glog\Source\src\logging.cc(1154) : error C2483: 'thread_msg_data' : object with constructor or destructor cannot be declared 'thread'
```

corresponting source code
https://github.com/hunter-packages/glog/blob/hunter_v0.3.5/src/logging.cc#L1154
```cpp
// Static log data space to avoid alloc failures in a LOG(FATAL)
//
// Since multiple threads may call LOG(FATAL), and we want to preserve
// the data from the first call, we allocate two sets of space.  One
// for exclusive use by the first thread, and one for shared use by
// all other threads.
static Mutex fatal_msg_lock;
static CrashReason crash_reason;
static bool fatal_msg_exclusive = true;
static LogMessage::LogMessageData fatal_msg_data_exclusive;
static LogMessage::LogMessageData fatal_msg_data_shared;

#ifdef GLOG_THREAD_LOCAL_STORAGE
// Static thread-local log data space to use, because typically at most one
// LogMessageData object exists (in this case glog makes zero heap memory
// allocations).
static GLOG_THREAD_LOCAL_STORAGE bool thread_data_available = true;
static GLOG_THREAD_LOCAL_STORAGE LogMessage::LogMessageData thread_msg_data;
#endif // defined(GLOG_THREAD_LOCAL_STORAGE)
```

is thread maybe a new feature? I don't know enough to fix this

**Comment by ruslo** [comment]
> is thread maybe a new feature? I don't know enough to fix this

I guess it's some new C++11 feature which is implemented in `vs-14-2015` and not available for versions before. Feel free to exclude.

**Comment by NeroBurner** [comment]
PR excluding: https://github.com/ingenue/hunter/pull/121

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2314
* https://travis-ci.org/ingenue/hunter/builds/270827299?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2317
* https://travis-ci.org/ingenue/hunter/builds/271127417?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.91

**Comment by headupinclouds** [comment]
https://github.com/google/glog/blob/40fc21467abb4516976ea2aa586bd206d0b86d20/CMakeLists.txt#L195-L218

C++11 supports `thread_local` storage, and various compilers before this have supported approximations of it in the past.  glog does try to `check_cxx_source_compiles()` to find backups:

```
check_cxx_source_compiles ("
__declspec(thread) int tls;
int main() { }
" HAVE_MSVC_TLS)

check_cxx_source_compiles ("
thread_local int tls;
int main() { }
" HAVE_CXX11_TLS)

check_cxx_source_compiles ("
__attribute__((thread)) int tls;
int main() { }
" HAVE_CYGWIN_TLS)

if (WITH_TLS)
  if (HAVE_CYGWIN_TLS)
    set (GLOG_THREAD_LOCAL_STORAGE "__attribute__((thread))")
  elseif (HAVE_MSVC_TLS)
    set (GLOG_THREAD_LOCAL_STORAGE "__declspec(thread)")
  elseif (HAVE_CXX11_TLS)
    set (GLOG_THREAD_LOCAL_STORAGE thread_local)
  endif (HAVE_CYGWIN_TLS)
endif (WITH_TLS)
```

**Comment by NeroBurner** [comment]
glog checks availablility, but why does it fail on older vs compilers? Are the flag-tests wrong, are the flags not properly used in code or do older vs-compilers just don't support TLS?

**Pull request merged**
