### PR TITLE
Make libssh2 cacheable.

### PR DESCRIPTION
**Pull request by alamaison**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.802
* https://travis-ci.org/ingenue/hunter/builds/152804616

**Comment by ruslo** [comment]
> Testing

Something went wrong on Windows already.

**Comment by alamaison** [comment]
Sorry for the long delay.  I've pushed a fix that hopefully solves the issue

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1154
* https://travis-ci.org/ingenue/hunter/builds/173597080

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1156
* https://travis-ci.org/ingenue/hunter/builds/173600812

**Comment by ruslo** [comment]
Released https://github.com/ruslo/hunter/releases/tag/v0.16.24

**Pull request merged**
