### PR TITLE
Add CMake-based termcolor header to Hunter

### PR DESCRIPTION
**Pull request by norbertwenzel**
This adds termcolor v1.0.0 to Hunter. Tag has been specifically created for Hunter (see https://github.com/ikalnytskyi/termcolor/issues/24).

* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html) step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the <del>Travis/</del>AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/NeroBurner/hunter/builds/19857237

* I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch,
  see this merged pull request https://github.com/ingenue/hunter/pull/284

* My change will resolve this "New package" request: https://github.com/ruslo/hunter/issues/1482

---

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/builds/19876953
* https://travis-ci.org/ingenue/hunter/builds/447751783?utm_source=github_status&utm_medium=notification

**Comment by norbertwenzel** [comment]
@ruslo Since you have already approved this PR, does that mean adding the PR number to the documentation is not required anymore? Or should this still be added?

**Comment by ruslo** [comment]
> does that mean adding the PR number to the documentation is not required anymore? Or should this still be added?

This part is kind of optional, so if contributor don't want to be mentioned then I don't mind. Since you removed the line I was thinking that it's the case. If you want to add the line let's do it as a follow-up in another pull request, tests already running, don't want to stop/rerun.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/builds/19877450
* https://travis-ci.org/ingenue/hunter/builds/447758672?utm_source=github_status&utm_medium=notification

**Comment by norbertwenzel** [comment]
> > does that mean adding the PR number to the documentation is not required anymore? Or should this still be added?
> 
> This part is kind of optional, so if contributor don't want to be mentioned then I don't mind. Since you removed the line I was thinking that it's the case. If you want to add the line let's do it as a follow-up in another pull request, tests already running, don't want to stop/rerun.

No need for doing that. The documentation is fine as it is imo. 

Thanks for swift merge.

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.39

**Pull request merged**
