### PR TITLE
Make libjson-rpc-cpp cacheable

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1711
* https://travis-ci.org/ingenue/hunter/builds/232460928?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1712
* https://travis-ci.org/ingenue/hunter/builds/232475205?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Dependencies should be cacheable too, for now:
```
Cache miss (entry for package: jsoncpp/)
```

**Comment by chfast** [comment]
Here you go: https://github.com/ruslo/hunter/pull/797.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1717
* https://travis-ci.org/ingenue/hunter/builds/232519030?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Uploading

Done, released: https://github.com/ruslo/hunter/releases/tag/v0.18.57

**Pull request merged**
