### PR TITLE
Update 'thrift' to v0.12.0-p0

### PR DESCRIPTION
**Pull request by JochenGuck**
Update 'thrift' to v0.12.0-p0

Travis Ci passed
appveyor is not working

error msg:
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

### CODE REVIEW

**Comment by JochenGuck** [comment]
Ok appveyor is now up and running.

i discovered that the original thrift 0.12 library will not compile with cxx17 since it relies on std::random_shuffle which is no longer supported. 
How do i handle such an Issue?
https://ci.appveyor.com/project/JochenGuck/hunter/builds/25660219

I also wonder which tool chains should be tested? Is there any list?
Thins thrift is boost based should i simply try the ones from  boost project?
https://github.com/ingenue/hunter/blob/add60d558463dfece5ae7f1a8ccdd7ed78ebfcb4/appveyor.yml#L21-L27

**Comment by ruslo** [comment]
>  How do i handle such an Issue?

Disable broken toolchains:
- https://docs.hunter.sh/en/latest/creating-new/update.html#remove-toolchains
- https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#excluding-tests

> I also wonder which tool chains should be tested? Is there any list?

You can find the default list of toolchains in `pkg.template` branch:
- https://github.com/ingenue/hunter/blob/pkg.template/appveyor.yml
- https://github.com/ingenue/hunter/blob/pkg.template/.travis.yml
- https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#ci-testing

>  Thins thrift is boost based should i simply try the ones from boost project?

Yes, if Thrift depends on Boost and some toolchain is not working with Boost, you should exclude it for Thrift too.

**Comment by JochenGuck** [comment]
I changed the tool chains to cxx14 and removed ninja, nmake and msys.

So now the AppVeyor tests are also ran successfully:
https://ci.appveyor.com/project/JochenGuck/hunter/builds/25664478

**Comment by ruslo** [comment]
> I changed the tool chains to cxx14 and removed ninja, nmake and msys.

Please send pull request with updates to https://github.com/ingenue/hunter to branch `pkg.thrift`:
- https://github.com/ingenue/hunter/tree/pkg.thrift

**Comment by JochenGuck** [comment]
I have created the pull request.

Travis Ci Results:
https://travis-ci.com/JochenGuck/hunter/builds/117607196

Appveyor Results:
https://ci.appveyor.com/project/JochenGuck/hunter/builds/25682201

**Comment by ruslo** [comment]
> I have created the pull request.

Well, that's precisely the same set of toolchains that are used in `pkg.thrift` already:
- https://ci.appveyor.com/project/ingenue/hunter/builds/25666269
- https://travis-ci.org/ingenue/hunter/builds/552823566?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/25686277
- https://travis-ci.org/ingenue/hunter/builds/553191803?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.198

**Pull request merged**
