### PR TITLE
websocketpp addition

### PR DESCRIPTION
**Pull request by tatraian**
I added websocketpp to hunter together a simple example.

You can see the ci results [here](https://travis-ci.org/tatraian/hunter_test/builds/124765516) and [here](https://ci.appveyor.com/project/tatraian/hunter-test).

(see issue: #398)

### CODE REVIEW

**Comment by tatraian** [comment]
Ups. I see that currently I only install the includes (this is an include only library). But It has ZLIB, OpenSSL and Boost dependency. They were used only during example building, but in philosophy of hunter I think it should be better to add these libraries as linked libraries to the interface target. In this it will be enought to link the final code only to websocketpp.

So I think you can wait for this fix in the hunter-package/websocketpp package.

**Comment by ruslo** [comment]
New wiki page: https://github.com/ruslo/hunter/wiki/pkg.websocketpp

**Comment by ruslo** [comment]
> But It has ZLIB, OpenSSL and Boost dependency. They were used only during example building, but in philosophy of hunter I think it should be better to add these libraries as linked libraries to the interface target

Does websocketpp itself depends on these libraries or the examples depends on them? If just examples then you should add something like `WEBSOCKETPP_BUILD_EXAMPLES=OFF`.

**Comment by ruslo** [comment]
New CI branch:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.400
* https://travis-ci.org/ingenue/hunter/builds/124876307

**Pull request merged**
