### PR TITLE
Add OpenCV 3.4.0

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by xsacha** [comment]
I'll add that version to config when  #1305 is merged

**Comment by xsacha** [comment]
Anything wrong with this?

**Comment by ruslo** [comment]
No, everything looks good:

image

Need to update CI for OpenCV, waiting for Travis OSX machines.

**Comment by ruslo** [comment]
Still waiting for dependencies...

Related: https://github.com/travis-ci/travis-ci/issues/9075

I think they have added few extra machines recently:
image

**Comment by ruslo** [comment]
https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

**Comment by ruslo** [comment]
https://www.traviscistatus.com/incidents/mc9x2wmpnvhg

**Comment by xsacha** [comment]
The incident looks like it is resolved. Backlog is down to 1400.

**Comment by ruslo** [comment]
> The incident looks like it is resolved. Backlog is down to 1400.

I see that incident have been resolved https://www.traviscistatus.com/incidents/mc9x2wmpnvhg and graph looks better https://www.traviscistatus.com/ but I see no progress so far on OSX jobs I was waiting:
* https://travis-ci.org/ingenue/hunter/builds/330205753?utm_source=github_status&utm_medium=notification (OpenCV dependency)
* https://travis-ci.org/ingenue/hunter/builds/329865567?utm_source=github_status&utm_medium=notification (Testing of pull request)

**Comment by xsacha** [comment]
Looks like first one was cancelled and second one built

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3249
* https://travis-ci.org/ingenue/hunter/builds/332352679?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3249

Seems that OpenCV-extra build failed because of lack of C++11 support in Visual Studio 2013. Visual Studio 2015 works fine. I will remove broken Visual Studio 2013 toolchains.

**Comment by xsacha** [comment]
Thanks

**Comment by ruslo** [comment]
https://www.traviscistatus.com/incidents/1p7kw5hl4n1g

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3252
* https://travis-ci.org/ingenue/hunter/builds/333123963?utm_source=github_status&utm_medium=notification

**Pull request merged**
