### PR TITLE
add xgboost v0.40-p9

### PR DESCRIPTION
**Pull request by headupinclouds**
* remove boost serialization in favor of cereal serialization
* minor cleanups for cereal serialization

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2150
* https://travis-ci.org/ingenue/hunter/builds/264238923?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
All of these errors seem to stem from ANDROID related `strto*` patches.  I had added some `try_compile` CMake logic to attempt to determine when those patches were needed, which doesn't seem to be working in some cases.  I will take a look.
```
error: declaration conflicts with target of using declaration already in scope
inline long double strtold(const char* str, char** str_end)
```

**Comment by headupinclouds** [comment]
clang-libstdcxx: should be removed since xgboost uses `std::function<>`

**Comment by headupinclouds** [comment]
Added v0.40-p7 to fix cmake `std::to_string()` test and logic.  Independent tests pass.  Resubmitting here.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2158
* https://travis-ci.org/ingenue/hunter/builds/264403915?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
I think `find_package(half CONFIG REQUIRED)` is missing in `*Config.cmake`:
```
CMake Error at C:/projects/hunter/_testing/Hunter/_Base/aacb49d/326fee5/7b5625d/Install/lib/cmake/xgboost/xgboostConfig.cmake:28 (find_package):
  Could not find a package configuration file provided by "half" with any of
  the following names:
    halfConfig.cmake
    half-config.cmake
```

**Comment by headupinclouds** [comment]
The to_string compile test needs to be adjusted for the gnu libs:
```
/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d7481d4/743ebbd/f8edcf6/Build/xgboost/Source/src/gbm/../utils/to_string.h:43:20: error: declaration conflicts with target of using declaration already in scope
inline long double strtold(const char* str, char** str_end)
                   ^
/usr/include/stdlib.h:175:20: note: target of using declaration
extern long double strtold (const char *__restrict __nptr,
                   ^
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdlib:253:22: note: using declaration
  using ::__gnu_cxx::strtold;
                     ^
inline long double strtold(const char* str, char** str_end)
                   ^
/usr/include/stdlib.h:175:20: note: target of using declaration
extern long double strtold (const char *__restrict __nptr,
                   ^
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdlib:253:22: note: using declaration
  using ::__gnu_cxx::strtold;
```

**Comment by headupinclouds** [comment]
> I think find_package(half CONFIG REQUIRED) is missing in *Config.cmake:

Thanks.  I'll add it.

**Comment by headupinclouds** [comment]
Updated: https://github.com/hunter-packages/xgboost/pull/8
Testing as GIT_SUBMODULE here: https://github.com/elucideye/xgboostcpp/pull/12

**Comment by headupinclouds** [comment]
```
polly.py --toolchain android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections --install --verbose --reconfig
...
SUCCESS
```
```
polly.py --toolchain gcc --install --verbose --reconfig
...
SUCCESS
```

This one doesn't seem to support `std::function<>`.  I've added `#include <functional>` in these cases but it still dies.
```
polly.py --toolchain clang-libstdcxx --install --verbose --reconfig
```
```
xgboost/src/gbm/../utils/../sync/../../subtree/rabit/include/rabit.h:163:28: error: no type named 'function' in namespace 'std'
                      std::function<void()> prepare_fun);
```

**Comment by headupinclouds** [comment]
I've sent a pr to ingenue remove non c++11 toolchains: https://github.com/ingenue/hunter/pull/112

**Comment by headupinclouds** [comment]
xgboostcpp tests passed.  pushed v0.40-p8 update.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2161
* https://travis-ci.org/ingenue/hunter/builds/264473701?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
```
foo.cpp(1): fatal error C1083: Cannot open include file: 'xgboost/src/learner/dmatrix.h': No such file or directory
```

**Comment by headupinclouds** [comment]
```
cd hunter
TOOLCHAIN=default PROJECT_DIR=examples/xgboost ./jenkins.py --verbose
```
```
/Applications/develop/ide/xcode/8.1/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -isystem /Users/dhirvonen/devel/hunter/_testing/Hunter/_Base/4f89bf4/a0156ed/c029df5/Install/include/xgboost  -O3 -DNDEBUG   -o CMakeFiles/foo.dir/foo.cpp.o -c /Users/dhirvonen/devel/hunter/examples/xgboost/foo.cpp
/Users/dhirvonen/devel/hunter/examples/xgboost/foo.cpp:1:10: fatal error: 'xgboost/src/learner/dmatrix.h' file not found
#include <xgboost/src/learner/dmatrix.h>
```

It is passing`-isystem /Users/.../Install/include/xgboost` when we want `-isystem /Users/.../Install/include/`

**Comment by headupinclouds** [comment]
Fixed.  Resubmitted.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2164
* https://travis-ci.org/ingenue/hunter/builds/264651983?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2166
* https://travis-ci.org/ingenue/hunter/builds/264655066?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Thanks.

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.70

**Pull request merged**
