### PR TITLE
add jemalloc + test

### PR DESCRIPTION
**Pull request by headupinclouds**
Based on CMake fork by @mattsta : https://github.com/mattsta/jemalloc/commits/add/cmake-flat

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2773
* https://travis-ci.org/ingenue/hunter/builds/300667168?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Thanks.

**Comment by ruslo** [comment]
> Testing

No toolchains working on Windows, is it okay?

**Comment by headupinclouds** [comment]
I'll have to fire up ye olde Windows VM for this.

**Comment by ruslo** [comment]
```
-- Performing Test HAS_FFSL
  -- Performing Test HAS_FFSL - Failed
  CMake Error at CMakeLists.txt:221 (message):
    Neither __builtin_ffs() or ffs() found!
```

It doesn't seems that `ffsl` available in Visual Studio:
* https://en.wikipedia.org/wiki/Find_first_set#Tool_and_library_support

**Comment by headupinclouds** [comment]
I fixed a few MSVC issues [here](https://github.com/hunter-packages/jemalloc/commit/7686ec88eb2353b5f8c6ba584e270970cd05779b).  I'm hitting some undefined macros in `jemalloc/include/internal/stats_structs.h`

* NSIZES
* NBINS
* NPSTATS

These are provided anywhere in the 4.2.0 branch of jemalloc that I can find, but I do see them set in the jemalloc-cmake branch (which is windows only, and AFAIK out of date) here:

https://github.com/jemalloc/jemalloc-cmake/blob/abeb19f8493feb67a2a8f121ea9bab1829f8d3fb/Utilities.cmake

It might be possible to pull in that cmake function to generate the headers automatically:

https://github.com/jemalloc/jemalloc-cmake/blob/abeb19f8493feb67a2a8f121ea9bab1829f8d3fb/Utilities.cmake#L329-L359

Based on scanning jemalloc issues/discussion, it seems they've decided to switch to CMake officially for all platforms at some point in the future, but it isn't there yet.  This may turn out to be a non-trivial effort and it is probably better to wait for it.  The `jemalloc` lib is currently an optional dependency in `tensorflow`.

**Comment by headupinclouds** [comment]
Closing for now.

**Pull request closed without merging**
