### PR TITLE
add SDL_mixer package

### PR DESCRIPTION
**Pull request by wheybags**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2094
* https://travis-ci.org/ingenue/hunter/builds/259757730?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
All Windows toolchains failed. Some OSX/Linux toolchains failed. Feel free to exclude, branch [pkg.sdl_mixer](https://github.com/ingenue/hunter/tree/pkg.sdl_mixer).

**Comment by wheybags** [comment]
Updated, should probably work now.
I was missing any actual format loading backends :(
I had hoped that SDL_mixer would handle them internally but apparently not :s
Enabled the builtin WAV handling for now, will need external libraries for the rest, but can do that later.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2096
* https://travis-ci.org/ingenue/hunter/builds/259886892?utm_source=github_status&utm_medium=notification

**Comment by wheybags** [comment]
https://github.com/ingenue/hunter/pull/103

**Comment by wheybags** [comment]
another fix, forgot about SDL's horrible SDL2main thing

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2099
* https://travis-ci.org/ingenue/hunter/builds/259898852?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Linux/OSX looks good. Few toolchains on Windows failed.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2102
* https://travis-ci.org/ingenue/hunter/builds/259951844?utm_source=github_status&utm_medium=notification

**Comment by wheybags** [comment]
Those toolchains are disabled in the SDL2 package
pr: https://github.com/ingenue/hunter/pull/104

issue: https://github.com/ruslo/hunter/issues/925

**Comment by wheybags** [comment]
ah, you got there before me :p

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2103
* https://travis-ci.org/ingenue/hunter/builds/260048811?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.56

**Pull request merged**
