### PR TITLE
Pr.cvmatio.add.istream

### PR DESCRIPTION
**Pull request by headupinclouds**
Add istream input for MatlabIO

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.817
* https://travis-ci.org/ingenue/hunter/builds/154092744

**Comment by ruslo** [comment]
Linux/OSX tests fail because of more aggressive warning policies.

OSX (toolchain=default):
```
cvmatio/Source/include/MatlabIO.hpp:87:23:
  error: in-class initialization of non-static data member is a C++11 extension [-Werror,-Wc++11-extensions]
    std::istream *is_ = nullptr;
```
Actually quite fair, default toolchain doesn't set c++11 so we can exclude this one (Linux already excluded).

Linux (clang-libstdcxx):
```
cvmatio/Source/src/MatlabIO.cpp:749:32:
  error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]
    std::cout << std::setw(flmax) << variables[n].name() << " " << variables[n].type() << "\n";
```
Same error with `sanitize-address` and `sanitize-leak` because identical compilers are used.

**Comment by headupinclouds** [comment]
@ruslo : Should be fixed in [2e8252ba2b7b16d8e99578506e1d8a8424a4632a](https://github.com/ruslo/hunter/pull/498/commits/2e8252ba2b7b16d8e99578506e1d8a8424a4632a)

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.821
* https://travis-ci.org/ingenue/hunter/builds/154187742

**Comment by headupinclouds** [comment]
The builds are passing except for the following Windows toolchains:

TOOLCHAIN=vs-12-2013-win64
TOOLCHAIN=vs-12-2013-xp

It seems to be a download error:

```
CUSTOMBUILD : error : downloading [C:\projects\hunter\_testing\Hunter\_Base\2ed58a3\cb9eb89\613f797\Build\Boost\Build\Boost.vcxproj] [C:\projects\hunter\_testing\Hunter\_Base\2ed58a3\cb9eb89\613f79
[00:09:29] 7\Build\cvmatio\Build\cvmatio-Release.vcxproj]
[00:09:29] 
[00:09:29]       'https://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.bz2'
[00:09:29] 
[00:09:29]       failed
```

**Comment by ruslo** [comment]
> It seems to be a download error

Toolchain-id calculation changed so we are not getting `Cache HIT` for some packages, I've started some `upload.*` jobs, need to wait a little bit.

> 'https://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.bz2' failed

That's a real pain :) One of the reason why I do upload sources to GitHub instead of using original. Cache is a huge time saver and stability provider here.

**Comment by headupinclouds** [comment]
> Toolchain-id calculation changed so we are not getting Cache HIT for some packages

Is this a recent hunter change? 

> That's a real pain :)

Ok.   So the boost download error seems to be an internet hiccup?  (I was able to download the link manually.)

**Comment by ruslo** [comment]
> Is this a recent hunter change? 

https://github.com/ruslo/hunter/commit/f99e31c6f9556356f059f00442698e97838e557d
Only affects windows.

> So the boost download error seems to be an internet hiccup?

I'm not sure, probably sourceforge have some kind of protection because I got massive toolchain failure usually. Things getting worse because AppVeyor doesn't allow to restart one job from build, only the whole build (all jobs at once).

**Comment by ruslo** [comment]
> I'm not sure, probably sourceforge have some kind of protection because I got massive toolchain failure usually

That may be true but also I've found a flaw in CMake code too. It is a know issue with Visual Studio: https://github.com/ruslo/hunter/blob/a74fc84308fb16a3c93dc4207c1df52cfe1b1cd6/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L325-L327 now problem reach download stage.

**Comment by headupinclouds** [comment]
I've seen some discussion about automated testing using hunter-bot, but this is not functional yet, right?  (You are still running package tests manually in the ingenue fork?)

**Comment by ruslo** [comment]
> I've seen some discussion about automated testing using hunter-bot

Development is here: https://github.com/hunter-packages/hunter-bot

> You are still running package tests manually in the ingenue fork?

Yes. Well I'm merging branches manually, Travis/AppVeyor do the tests/uploads :)

**Comment by ruslo** [comment]
> That may be true but also I've found a flaw in CMake code too

Apply workaround: https://github.com/ruslo/hunter/commit/44c133b10368785e160ae4c46e7d0f1b8cc00f86

Let's see how it will go: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.827

**Comment by ruslo** [comment]
> Let's see how it will go

Much better!

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.829
* https://travis-ci.org/ingenue/hunter/builds/154396561

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.831
* https://travis-ci.org/ingenue/hunter/builds/154405028

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.15.18

**Comment by headupinclouds** [comment]
Thanks.

**Pull request merged**
