### PR TITLE
debug_assert 1.3.2

### PR DESCRIPTION
**Pull request by dvirtz**
* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/dvirtz/hunter/build/1.0.93
  * https://travis-ci.org/dvirtz/hunter/builds/375757737

---

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3851
* https://travis-ci.org/ingenue/hunter/builds/375861495?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3854
* https://travis-ci.org/ingenue/hunter/builds/375867524?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.20.69

**Comment by dvirtz** [comment]
Thanks!

**Pull request merged**
