### PR TITLE
Fix for compiling Boost for Android on Windows.

### PR DESCRIPTION
**Pull request by xsacha**
It was complaining of conflicting address models and it was also trying to build win32 thread api.

### CODE REVIEW

**Comment by xsacha** [comment]
So many deps id. I just did: sed -i 's/"24"/"25"/' `find . | grep hunter.cmake`
Hope that worked.

**Comment by xsacha** [comment]
Thanks.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3367
* https://travis-ci.org/ingenue/hunter/builds/346342117?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3368
* https://travis-ci.org/ingenue/hunter/builds/346542361?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.20.13

**Pull request merged**
