### PR TITLE
spdlog: bump versions

### PR DESCRIPTION
**Pull request by jkoelker**
Depends on hunter-packages/spdlog/pull/3 of course ;).

### CODE REVIEW

**Comment by ruslo** [comment]
See https://github.com/hunter-packages/spdlog/releases/tag/v0.12.0-p0 and https://github.com/hunter-packages/spdlog/releases/tag/v0.13.0-p0

**Comment by jkoelker** [comment]
Excellent. The sha's in this PR are correct and line up with those tags. Please let me know if I need to do something more,or if we are just waiting on ci or something in the ingenue tests? First time and all, tried to read as much as I could on the contribution process ;).

**Comment by ruslo** [comment]
>  if we are just waiting on ci or something in the ingenue tests?

Yes, testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1695
* https://travis-ci.org/ingenue/hunter/builds/231826345?utm_source=github_status&utm_medium=notification

I was confused a little bit, how did you get the SHA1 of release archives before I've pushed the tags? :)

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1696
* https://travis-ci.org/ingenue/hunter/builds/231828132?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released:
* https://github.com/ruslo/hunter/releases/tag/v0.18.52

**Comment by jkoelker** [comment]
> I was confused a little bit, how did you get the SHA1 of release archives before I've pushed the tags? :)

Ah, I had tagged it and pushed those tags to my github fork, and then downloaded and sha'd from there.

Thanks for hunter. Its made working cross platform not suck as much.

**Pull request merged**
