### PR TITLE
Enable fiber library in boost package

### PR DESCRIPTION
**Pull request by gumb0**
Should resolve https://github.com/ruslo/hunter/issues/1111

### CODE REVIEW

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.231

**Comment by gumb0** [comment]
Thanks for quick review!

**Comment by gumb0** [comment]
@ruslo With this release I'm getting this error:
```
-- [hunter] Building Boost
-- [hunter *** DEBUG *** 2018-01-17T17:05:25] [C:/.hunter/_Base/2742c88/274849f/da3bae4/Build/Boost] > "C:/Program Files/CMake/bin/cmake.exe" "-CC:/.hunter/_Base/2742c88/274849f/da3bae4/cache.cmake" "-CC:/.hunter/_Base/2742c88/274849f/da3bae4/Build/Boost/args.cmake" "-HC:/.hunter/_Base/2742c88/274849f/da3bae4/Build/Boost" "-BC:/.hunter/_Base/2742c88/274849f/da3bae4/Build/Boost/Build" "-DCMAKE_TOOLCHAIN_FILE=C:/.hunter/_Base/2742c88/274849f/da3bae4/Build/Boost/toolchain.cmake" "-GVisual Studio 14 2015 Win64" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe"
loading initial cache file C:/.hunter/_Base/2742c88/274849f/da3bae4/cache.cmake
loading initial cache file C:/.hunter/_Base/2742c88/274849f/da3bae4/Build/Boost/args.cmake
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter *** DEBUG *** 2018-01-17T17:05:38] Scheme: url_sha1_boost

[hunter ** INTERNAL **] Unexpected empty string
[hunter ** INTERNAL **] [Directory:C:/.hunter/_Base/2742c88/274849f/da3bae4/Build/Boost]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.19.231/2742c88/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.19.231/2742c88/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.19.231/2742c88/Unpacked/cmake/modules/hunter_test_string_not_empty.cmake:9 (hunter_internal_error)
  CMakeLists.txt:37 (hunter_test_string_not_empty)
```
What could be wrong?

Full log: 
https://ci.appveyor.com/project/ethereum/cpp-ethereum/build/1.0.3357
https://circleci.com/gh/ethereum/cpp-ethereum/2403

**Comment by ruslo** [comment]
> What could be wrong?

https://github.com/ruslo/hunter/blob/master/cmake/projects/Boost/schemes/url_sha1_boost.cmake.in#L37

Update HunterGate module:
* https://github.com/hunter-packages/gate/commit/ca857cc47d514dd023bb5ce981aa47e2996ac20e

**Comment by ruslo** [comment]
I've added a checker: https://github.com/ruslo/hunter/commit/1ced5a0a633b9d65a6626be585b5f12add5cc4ab .

Released: https://github.com/ruslo/hunter/releases/tag/v0.19.232

**Comment by gumb0** [comment]
Thanks, that helped! 👍

**Pull request merged**
