### PR TITLE
websocketpp 0.7.0-p2 version addition

### PR DESCRIPTION
**Pull request by tatraian**
News:
 - websocketpp now handles its dependent libraries and export them
   as INTERFACE_LINK_LIBRARIES property

 - a new example has been added to test linking to OpenSSL (and other
   dependencies)

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.404
* https://travis-ci.org/ingenue/hunter/builds/126111928

**Comment by ruslo** [comment]
> https://travis-ci.org/ingenue/hunter/builds/126111928

Some tests failed. Feel free to do fix or exclude.

**Comment by tatraian** [comment]
Windows builds:
- As I see nmake/ninja vs2013 failed since boost build
- other earlier version doesn't talk C++11
So I think Windows is OK.

Linux build:
- Some cases (clang builds) failed with boost building (this is out of scope I think)
- clang-libstdcxx cannot compile boost
- and I have a serious problem: gcc builds:
my question is the following, why g++ doesn't link to libdl.so, if -ldl flag is active:
```
/usr/bin/g++-4.8   -std=c++11 -O3 -DNDEBUG   CMakeFiles/openssl_example.dir/echo_server_both.cpp.o  -o openssl_example -rdynamic -ldl /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libz.a /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libssl.a /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libcrypto.a /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libboost_system-mt.a /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libboost_random-mt.a /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libboost_thread-mt.a
/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x21): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x34): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3f): undefined reference to `dlclose'
/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x354): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3fb): undefined reference to `dlerror'
/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x474): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x52e): undefined reference to `dlerror'
/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x5a4): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x612): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x640): undefined reference to `dlerror'
/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x6be): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x721): undefined reference to `dlerror'
make[2]: Leaving directory `/home/travis/build/ingenue/hunter/_testing/_builds/gcc-4-8-Release'
make[1]: Leaving directory `/home/travis/build/ingenue/hunter/_testing/_builds/gcc-4-8-Release'
/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/d0510f2/e97794b/7a9f5db/Install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x77a): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [openssl_example] Error 1
make[1]: *** [CMakeFiles/openssl_example.dir/all] Error 2
make: *** [all] Error 2
Command exit with status "2": [/home/travis/build/ingenue/hunter/_testing]> "cmake" "--build" "/home/travis/build/ingenue/hunter/_testing/_builds/gcc-4-8-Release" "--config" "Release" "--"
```

Anyway I don't have more time for this so please exclude the failed cases.

**Comment by ruslo** [comment]
> Anyway I don't have more time for this so please exclude the failed cases

I'm okay with excluding. Please send pull request to branch `pkg.websocketpp` of repo https://github.com/ingenue/hunter. Leave a links to build logs and any thoughs/hints about errors in case somebody want to fix them in future ([like this](https://github.com/ingenue/hunter/blob/4c4188b3d580f0e11cbc3e4e1a54c11616e870ae/.travis.yml#L102)).

**Comment by tatraian** [comment]
Sorry, I am lame...

I cannot fork you test repo, since I have an other hunter fork... You can merge my changes through command line... Sorry...

Repo: https://github.com/tatraian/hunter_test.git
Branch: pkg.websocketpp

Or if you have other idea please share me!

**Comment by pretyman** [comment]
You can push the branch `pkg.websocketpp` into your current hunter fork and from there open the pull request to https://github.com/ingenue/hunter/ 

You can push into your fork provided it is a remote for the repository. If you did a clone from ingenue you'll have to

```
git remote add tatraian https://github.com/tatraian/hunter
git push trataian
```

Or something along those lines

**Comment by tatraian** [comment]
Thanks, thats OK. Just I get a non mergable branch. So I have to figure out where I made the things wrong. Probably my already created hunter_test repository's pkg.websocketpp was earlier created than the "official", furthermore the branch creation is duplication (@ruslo done in its repo and I done in my).  But I forget it and I tried to merge my modifications to the "official"...

**Comment by pretyman** [comment]
Fetch branch `pkg.websocketpp` from https://github.com/ingenue/hunter/ then rebase ( https://git-scm.com/docs/git-rebase ) your changes onto it. Like this you should be able open the pull request as a fast forward merge.

**Comment by tatraian** [comment]
Thanks for advices. I did it.

**Comment by ruslo** [comment]
Just for the record: https://github.com/ingenue/hunter/pull/13

**Comment by ruslo** [comment]
New testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.418
* https://travis-ci.org/ingenue/hunter/builds/128262036

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.424
* https://travis-ci.org/ingenue/hunter/builds/128350282

**Comment by ruslo** [comment]
> Uploading

Done

Released: https://github.com/ruslo/hunter/releases/tag/v0.14.19

**Pull request merged**
