### PR TITLE
Add benchmark package

### PR DESCRIPTION
**Pull request by isaachier**
Adds another dependency of grpc (#561).

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2567
* https://travis-ci.org/ingenue/hunter/builds/289989638?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

Toolchains `vs-12-2013-xp` and `mingw` failed:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2567

They are not excluded from testing:
* https://github.com/ingenue/hunter/pull/145/files

This should not happen on practice, please check workflow:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#run-remote-tests

**Comment by isaachier** [comment]
You are correct. I'm sorry. I think the Appveyor build slipped my mind before I submitted this.

**Comment by isaachier** [comment]
https://github.com/ingenue/hunter/pull/146

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2573
* https://travis-ci.org/ingenue/hunter/builds/290069784?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2578
* https://travis-ci.org/ingenue/hunter/builds/290366156?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.127

**Comment by chfast** [comment]
Thank you.

**Pull request merged**
