### PR TITLE
Add Beast b84. Update example for new API.

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1999
* https://travis-ci.org/ingenue/hunter/builds/256606494?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Some toolchain failed

**Comment by xsacha** [comment]
I can't reproduce the problem on my computer. It looks like a problem with gets not existing, which it doesn't but boost should not be using it.

**Comment by ruslo** [comment]
Since it's Linux toolchains we can use Docker magic. I can reproduce error locally, see instructions:
* https://github.com/hunter-packages/travis-linux-docker

Anyway if you have no plans to fix it, then it will be easier to exclude broken toolchains.

**Comment by xsacha** [comment]
Looks like known issue with clang 3.5 and libstdc++.
I think this is the cause:
set(CMAKE_CXX_STANDARD 14)

I suppose the toolchains don't need this?

**Comment by ruslo** [comment]
> I suppose the toolchains already set this?

Yes, current toolchain use C++11. If package require C++14 and that's the cause, then simply remove toolchain from testing.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2053
* https://travis-ci.org/ingenue/hunter/builds/257694725?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2054
* https://travis-ci.org/ingenue/hunter/builds/257700226?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.47

**Pull request merged**
