### PR TITLE
add aglet 1.2.0

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2152
* https://travis-ci.org/ingenue/hunter/builds/264240073?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Appveyor and Travis look good.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2157
* https://travis-ci.org/ingenue/hunter/builds/264333343?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.69

**Pull request merged**
