### PR TITLE
Add dlib 19.14

### PR DESCRIPTION
**Pull request by xsacha**
* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All Passed":

  * https://ci.appveyor.com/project/xsacha/hunter-h4uji/build/1.0.15
  * https://travis-ci.org/xsacha/hunter/builds/402992628

### CODE REVIEW

**Comment by ruslo** [comment]
> Here is the links to the Travis/AppVeyor with status **Passing**

Well, they all still pending.

Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4187
* https://travis-ci.org/ingenue/hunter/builds/402995717?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
Thanks. Changed to All Passed.
I don't like waiting for that OSX tool chain. Why does it take over an hour?

**Comment by ruslo** [comment]
> Why does it take over an hour?

Some dependencies are missing, I've noticed "cache miss OpenBLAS". I started OpenBLAS upload, may be there are some others:
* https://travis-ci.org/ingenue/hunter/builds/403017413?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Some dependencies are missing, I've noticed "cache miss OpenBLAS"

Actually it's because `osx-10-13-cxx14` toolchain removed:
* https://github.com/ingenue/hunter/blob/67b9a38132d45e7729f2a675078726ae2d898e20/.travis.yml#L87-L93

**Comment by ruslo** [comment]
OpenBLAS + `osx-10-13-cxx14` is still broken, just checked:
* https://travis-ci.org/ingenue/hunter/builds/403020015?utm_source=github_status&utm_medium=notification

If OpenBLAS is a dependency of dlib then `osx-10-13-cxx14` should be removed dlib from testing.

**Comment by xsacha** [comment]
It's not a hard dependency, it's optional. However, because of Hunter we assume it works and add it.

**Comment by ruslo** [comment]
You can disable it with `if(APPLE)` condition.

**Comment by ruslo** [comment]
Well, actually it's the same with old dlib version
* https://travis-ci.org/ingenue/hunter/jobs/403025865

Do you want me to remove `osx-10-13-cxx14` from dlib testing or you will add `if(APPLE)` condition?

**Comment by xsacha** [comment]
Can remove it from testing.
It compiles on OSX for me so not sure what that issue on CI is.

**Comment by ruslo** [comment]
> Can remove it from testing.

Ok, I will update `pkg.dlib` branch

> It compiles on OSX for me so not sure what that issue on CI is.

`osx-10-13-make-cxx14` toolchain use Makefile generator (passed), `osx-10-13-cxx14` use Xcode generator (failed).

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4192
* https://travis-ci.org/ingenue/hunter/builds/403110539?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4193
* https://travis-ci.org/ingenue/hunter/builds/403122813?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.22.27

**Pull request merged**
