### PR TITLE
Add LodePNG to hunter

### PR DESCRIPTION
**Pull request by bkotzz**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Not very well it seems...**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/bkotzz/hunter/builds/20747808
  * https://travis-ci.com/bkotzz/hunter/builds/93455737

Note: This is based on commenting out the clang analyze build in this PR https://github.com/ingenue/hunter/pull/301

* I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch,
  see this merged pull request https://github.com/ingenue/hunter/pull/299 **Yes**

* My change will resolve this "New package" request: https://github.com/ruslo/hunter/issues/1627

---

### CODE REVIEW

**Comment by bkotzz** [comment]
Will do, sorry. Got confused - didn't register my fork. Didn't realize the CI was run on that

**Comment by bkotzz** [comment]
Failing CI because of https://github.com/hunter-packages/lodepng/pull/2.

Will need to publish a new release, change the config here, then re-run tests

**Comment by bkotzz** [comment]
@ruslo apologies, I left stale links in the description. I needed to comment out one build - I've put up the PR to do so, and have posted the new build links, which are all passing after that change

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/builds/20748596
* https://travis-ci.org/ingenue/hunter/builds/463153339?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/builds/20748755
* https://travis-ci.org/ingenue/hunter/builds/463156868?utm_source=github_status&utm_medium=notification

**Pull request merged**
