### PR TITLE
scripts to display hunter-module dependencies

### PR DESCRIPTION
**Pull request by NeroBurner**
I've added two scripts to the modules directory

`modules2dot.sh` creates an overview over all hunter modules and how they are connected

modules

`module_dependencies2dot.sh` creates an overview over the (recursive) dependencies of a specified hunter module

dep_graph_hunter_add_package

dep_graph_hunter_finalize

dep_graph_hunter_initialize

both scripts ignore the following modules to keep the graph simple
```
	hunter_status_print
	hunter_status_debug
	hunter_user_error
	hunter_internal_error
	hunter_fatal_error
	hunter_wiki
	hunter_test_string_not_empty
```

the dependencies are determined by lines starting with `include(hunter_`

### CODE REVIEW

**Comment by ruslo** [comment]
Thanks, looks cool. Can you move them to `maintenance` directory. May be even `maintenance/graphs` (?)

**Comment by NeroBurner** [comment]
where should the *.dot and *.png files go? maybe subfolders where the scripts are called? `maintenance/graphs/dot` and `maintenance/graphs/png`?

**Comment by headupinclouds** [comment]
Very helpful.  I'm sure I'll be using this.  Thanks.

**Comment by ruslo** [comment]
> where should the *.dot and *.png files go? maybe subfolders where the scripts are called? maintenance/graphs/dot and maintenance/graphs/png?

Usually I'm using `_` for temporary folders. So I think `maintenance/graphs/_dot` and `maintenance/graphs/_png`. You can add them to `.gitignore` too.

**Comment by NeroBurner** [comment]
updated

both scripts are now in `maintenance/graphs` and create the dot-files and png-files in `<working_dir>/_dot` and `<working_dir>/_png`.

`modules2dot.sh` expects the path to the modules directory

`module_dependencies2dot.sh` expects a path to a hunter-module file

**Comment by NeroBurner** [comment]
squashed

**Pull request merged**
