### PR TITLE
Make Expat cacheable.

### PR DESCRIPTION
**Pull request by alamaison**
Also add new version 2.1.1.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.342
* https://travis-ci.org/ingenue/hunter/builds/120431864

**Comment by ruslo** [comment]
> Testing

Some toolchain failed:
* https://travis-ci.org/ingenue/hunter/builds/120431864

Was working before:
* https://travis-ci.org/ingenue/hunter/builds/105876756

**Comment by alamaison** [comment]
I think I know what went wrong.  I added a top-level CMakeLists.txt file, but that changes the value of CMAKE_BINARY_DIR so one of the include paths was wrong.  I can't test it locally though, because it worked on Linux either way :|  I think it must be finding that header in the system include path instead.

**Comment by alamaison** [comment]
P.S. I've updated this PR with the fix.  Can you run the tests again?

**Comment by ruslo** [comment]
>  I can't test it locally though, because it worked on Linux either way

Hm... yeah, you need to install package locally and run build for project usage example. I don't know how to do it nicely, though this pattern can be useful:
* https://github.com/forexample/package-example/blob/cf2ea1d6a209fb9eca2ab83fdd0ac15fe4d3e807/Boo/CMakeLists.txt#L4

**Comment by ruslo** [comment]
> Can you run the tests again?

Done:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.343
* https://travis-ci.org/ingenue/hunter/builds/120451003

**Comment by alamaison** [comment]
Thanks :+1: They look happier now

**Comment by ruslo** [comment]
> Thanks :+1: They look happier now

Great. Waiting for the Windows now: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.343

**Comment by ruslo** [comment]
Failed:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.343/job/2hooi7xkdtsia0qf

**Comment by alamaison** [comment]
Weird.  The code it's complaining about was committed in 2005.

**Comment by ruslo** [comment]
> Weird. The code it's complaining about was committed in 2005.

Up to you. Feel free send pull request with removing failed toolchains.

**Comment by alamaison** [comment]
It turns out it's a regression in 2.1.1.  Although the code the compiler complains about was committed in 2005, code was inserted above it that made the later code invalid by the C90 standard that older MS compilers adhere to.

**Comment by alamaison** [comment]
I've submitted a PR to disable the affected toolchains for now: https://github.com/ingenue/hunter/pull/10

**Comment by ruslo** [comment]
Cache uploaded:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.347
* https://travis-ci.org/ingenue/hunter/builds/120555214

New release:
* https://github.com/ruslo/hunter/releases/tag/v0.14.10

**Comment by alamaison** [comment]
Thanks!

**Pull request merged**
