### PR TITLE
eos package update 0.12.1

### PR DESCRIPTION
**Pull request by headupinclouds**
* add new  hunter_add_version( .. 0.12.1 …)
* order releases from newest (top) to oldest (bottom)
* bump default version to 0.12.1

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1779
* https://travis-ci.org/ingenue/hunter/builds/239763976?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
`*Config.cmake` is not installed:
```
CMake Error at CMakeLists.txt:13 (find_package):
  Could not find a package configuration file provided by "eos" with any of
  the following names:
    eosConfig.cmake
```

**Comment by headupinclouds** [comment]
Oops.  I don't know how I missed that.  I will add the usual install section.

**Comment by headupinclouds** [comment]
Take two.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1788
* https://travis-ci.org/ingenue/hunter/builds/239798037?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
```
CMake Error at /home/travis/build/ingenue/hunter/_ci/cmake/share/cmake-3.8/Modules/CMakeFindDependencyMacro.cmake:35 (message):
  Invalid arguments to find_dependency
Call Stack (most recent call first):
  /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/2ddd996/b1ed1e0/8456c41/Install/lib/cmake/eos/eosConfig.cmake:6 (find_dependency)
  CMakeLists.txt:13 (find_package)
```

**Comment by headupinclouds** [comment]
Line 6 in my installed `eosConfig.cmake` is `find_dependency(Boost CONFIG REQUIRED)`.  I guess this needs the list of required components.  I should probably make a local package "installation test" prior to sending the PR to catch this type of thing.

```
1	
2	
3	include(CMakeFindDependencyMacro)
4	
5	find_dependency(OpenCV REQUIRED)
6	find_dependency(Boost CONFIG REQUIRED)
7	find_dependency(Eigen3 CONFIG REQUIRED)
8	find_dependency(cereal CONFIG REQUIRED)
9	find_dependency(glm REQUIRED)
10	find_dependency(nanoflann CONFIG REQUIRED)
11	find_dependency(eigen3-nnls CONFIG REQUIRED)
12	
13	include("${CMAKE_CURRENT_LIST_DIR}/eosTargets.cmake")
14	check_required_components("eos")
```

**Comment by ruslo** [comment]
>  I should probably make a local package "installation test" prior to sending the PR to catch this type of thing

You can use `jenkins.py`:
* https://github.com/ruslo/hunter/wiki/dev.hunter.root

Just for your info I found an issue with OpenCV and latest CMake version we are using in testing. Working on it...

**Comment by headupinclouds** [comment]
`TOOLCHAIN=default PROJECT_DIR=examples/eos ./jenkins.py --verbose` ==

```
Generate: 0:01:11.029119s
Build: 0:00:01.657792s
-
Total: 0:01:12.687292s
-
SUCCESS
```

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1803
* https://travis-ci.org/ingenue/hunter/builds/240043876?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
we should expect VERSION < `--std=c++11` or `--std=c++14` will fail.  although i think many recent c++11 compilers will support a subset of c++14 features w/ a warning.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1807
* https://travis-ci.org/ingenue/hunter/builds/240156992?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.6

**Comment by headupinclouds** [comment]
Thanks!

**Pull request merged**
