### PR TITLE
Autobahn cpp

### PR DESCRIPTION
**Pull request by tatraian**
Autobahn-cpp WAMP library. For tests I used 3 of its own.

For testing I propose to start with platforms supported by `msgpack-c` package.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1126
* https://travis-ci.org/ingenue/hunter/builds/170053950

> For testing I propose to start with platforms supported by msgpack-c package.

I will start with the default set, feel free to modify.

**Comment by tatraian** [comment]
Travis results:
- linux default: lack of c++11 support
- two analysis: boost compile error with analyze toolkits
  - command line module
  - system
- clang-libstdcxx: no `std::forward` in libstdcxx (I think it is old) 

AppVeyor:
- all VC except newest -> lack of C++11 support
- mingw: failed compile OpenSSL
- msys: failed compile boost::program_options

**Comment by tatraian** [comment]
And the issue link: #398.

**Comment by ruslo** [comment]
> Travis results

> AppVeyor

Please send pull request with disabling tests and info notes to [pkg.autobahn-cpp](https://github.com/ingenue/hunter/tree/pkg.autobahn-cpp) branch.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1130
* https://travis-ci.org/ingenue/hunter/builds/170138945

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1131
* https://travis-ci.org/ingenue/hunter/builds/170152747

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.16.16

Please create a new wiki page about this package. Like this one https://github.com/ruslo/hunter/wiki/pkg.xgboost

**Pull request merged**
