### PR TITLE
Upgrade libscrypt to 1.21-p1

### PR DESCRIPTION
**Pull request by chfast**
All libscrypt changes from hunter-packages except CMake scripts were merged upstream. The v1.21-p1 is the rebased version that only adds CMake to the recent version of master branch of libscrypt.

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/chfast/hunter/build/1.0.19
  * https://travis-ci.org/chfast/hunter/builds/344341924

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3359
* https://travis-ci.org/ingenue/hunter/builds/344507958?utm_source=github_status&utm_medium=notification

**Comment by chfast** [comment]
Why are you testing it again?

**Comment by ruslo** [comment]
> Why are you testing it again?

Just to be sure.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3362
* https://travis-ci.org/ingenue/hunter/builds/344517194?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.20.10

**Pull request merged**
