### PR TITLE
Add range-v3

### PR DESCRIPTION
**Pull request by dvirtz**
closes https://github.com/ruslo/hunter/issues/1276

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3174
* https://travis-ci.org/ingenue/hunter/builds/324470149?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Skipping upload step since package is not cacheable, released:
* https://github.com/ruslo/hunter/releases/tag/v0.19.217

**Comment by dvirtz** [comment]
Actually I've no idea why it's not cacheable, I only commented this out because it caused Hunter to wait forever trying to download basic-deps.DONE from ingenue/hunter-cache.

**Comment by ruslo** [comment]
Can you show logs?

**Comment by dvirtz** [comment]
I notice there's an "SSL connect error" reported. 

```
Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\dviry\CMakeBuilds\03b06269-ec57-363d-908b-ee1a06e0de75\install\x86-Debug"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Tools/MSVC/14.12.25907/bin/HostX86/x86/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Tools/MSVC/14.12.25907/bin/HostX86/x86/cl.exe" -DHUNTER_STATUS_DEBUG=ON -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "F:\Work\hunter\examples\range-v3"
Working directory: C:\Users\dviry\CMakeBuilds\03b06269-ec57-363d-908b-ee1a06e0de75\build\x86-Debug
Including HunterGate: F:/Work/hunter/gate/cmake/HunterGate.cmake
-- [hunter *** DEBUG *** 2018-01-04T14:42:47] HUNTER_ROOT detected by cmake variable
-- [hunter *** DEBUG *** 2018-01-04T14:42:47] HUNTER_ROOT: F:/Work/hunter
-- [hunter *** DEBUG *** 2018-01-04T14:42:48] Settings (initialize):
-- [hunter *** DEBUG *** 2018-01-04T14:42:48]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2018-01-04T14:42:48]   Cache init (YES)
-- [hunter *** DEBUG *** 2018-01-04T14:42:48] Single-configuration generator
-- [hunter *** DEBUG *** 2018-01-04T14:42:48] Using default cache server
-- [hunter *** DEBUG *** 2018-01-04T14:42:48] List of cache servers:
-- [hunter *** DEBUG *** 2018-01-04T14:42:48]   * https://github.com/ingenue/hunter-cache
-- [hunter *** DEBUG *** 2018-01-04T14:42:48] Settings (finalize):
-- [hunter *** DEBUG *** 2018-01-04T14:42:48]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2018-01-04T14:42:48]   Cache init (YES)
-- [hunter *** DEBUG *** 2018-01-04T14:42:48] Variables from HunterGate:
-- [hunter *** DEBUG *** 2018-01-04T14:42:48]   HUNTER_GATE_ROOT: F:/Work/hunter
-- [hunter *** DEBUG *** 2018-01-04T14:42:48]   HUNTER_GATE_VERSION: xxxxxxxxxx
-- [hunter *** DEBUG *** 2018-01-04T14:42:48]   HUNTER_GATE_SHA1: xxxxxxxxxx
-- [hunter] Calculating Toolchain-SHA1
-- [hunter *** DEBUG *** 2018-01-04T14:42:48] [C:/Users/dviry/CMakeBuilds/03b06269-ec57-363d-908b-ee1a06e0de75/build/x86-Debug/_3rdParty/Hunter/toolchain] > "C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" "-DTOOLCHAIN_INFO_FILE=C:/Users/dviry/CMakeBuilds/03b06269-ec57-363d-908b-ee1a06e0de75/build/x86-Debug/_3rdParty/Hunter/toolchain/toolchain.info" "-DHUNTER_SELF=F:/Work/hunter" "-GNinja" "-HC:/Users/dviry/CMakeBuilds/03b06269-ec57-363d-908b-ee1a06e0de75/build/x86-Debug/_3rdParty/Hunter/toolchain" "-BC:/Users/dviry/CMakeBuilds/03b06269-ec57-363d-908b-ee1a06e0de75/build/x86-Debug/_3rdParty/Hunter/toolchain/_builds" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DCMAKE_RELEASE_POSTFIX=" "-DCMAKE_DEBUG_POSTFIX=d"
-- The C compiler identification is MSVC 19.12.25907.0
-- The CXX compiler identification is MSVC 19.12.25907.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Tools/MSVC/14.12.25907/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Tools/MSVC/14.12.25907/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Tools/MSVC/14.12.25907/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Tools/MSVC/14.12.25907/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/dviry/CMakeBuilds/03b06269-ec57-363d-908b-ee1a06e0de75/build/x86-Debug/_3rdParty/Hunter/toolchain/_builds
-- [hunter *** DEBUG *** 2018-01-04T14:42:54] Already exists: F:/Work/hunter/_Base/xxxxxxx/6d8fd99/toolchain.info
-- [hunter] Calculating Config-SHA1
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] Cache data is up-to-date
-- [hunter] HUNTER_ROOT: F:/Work/hunter
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] HUNTER_TOOLCHAIN_ID_PATH: F:/Work/hunter/_Base/xxxxxxx/6d8fd99
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] HUNTER_CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] HUNTER_BUILD_SHARED_LIBS: 
-- [hunter] [ Hunter-ID: xxxxxxx | Toolchain-ID: 6d8fd99 | Config-ID: 4cea9f2 ]
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] HUNTER_MSVC_VERSION: 15
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] HUNTER_MSVC_YEAR: 2017
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] HUNTER_MSVC_ARCH: x86
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] Environment 'VS150COMNTOOLS': 'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\Tools\'
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] CMAKE_VS_DEVENV_COMMAND: ''
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] vcvarsall.bat file location: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Auxiliary/Build/vcvarsall.bat
-- [hunter *** DEBUG *** 2018-01-04T14:42:56] load: F:/Work/hunter/cmake/projects/range-v3/hunter.cmake
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] range-v3 versions available: [vcpkg5-p;0.3.0-p]
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Install to: F:/Work/hunter/_Base/xxxxxxx/6d8fd99/4cea9f2/Install
-- [hunter] RANGE-V3_ROOT: F:/Work/hunter/_Base/xxxxxxx/6d8fd99/4cea9f2/Install (ver.: vcpkg5-p)
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Default arguments: BUILD_DOCS=FALSE;BUILD_TESTS=FALSE
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] User arguments: 
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Locking directory: F:/Work/hunter/_Base/Download/range-v3/vcpkg5-p/d8b723b
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Lock done
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Already locked: F:/Work/hunter/_Base/Download/range-v3/vcpkg5-p/d8b723b
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Locking directory: F:/Work/hunter/_Base/xxxxxxx/6d8fd99/4cea9f2
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Lock done
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Add extra CMake args: 'BUILD_DOCS' = 'FALSE'
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Add extra CMake args: 'BUILD_TESTS' = 'FALSE'
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Locking directory: F:/Work/hunter/_Base/Cache
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Lock done
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Downloading file (try #0 of 10):
-- [hunter *** DEBUG *** 2018-01-04T14:42:57]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/6d8fd99/range-v3/vcpkg5-p/d8b723b/db4ff52/a49b0e5/da4b923/basic-deps.DONE
-- [hunter *** DEBUG *** 2018-01-04T14:42:57]   -> F:/Work/hunter/_Base/Cache/meta/6d8fd99/range-v3/vcpkg5-p/d8b723b/db4ff52/a49b0e5/da4b923/basic-deps.DONE
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Download error ("SSL connect error")
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Downloading file (try #1 of 10):
-- [hunter *** DEBUG *** 2018-01-04T14:42:57]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/6d8fd99/range-v3/vcpkg5-p/d8b723b/db4ff52/a49b0e5/da4b923/basic-deps.DONE
-- [hunter *** DEBUG *** 2018-01-04T14:42:57]   -> F:/Work/hunter/_Base/Cache/meta/6d8fd99/range-v3/vcpkg5-p/d8b723b/db4ff52/a49b0e5/da4b923/basic-deps.DONE
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Download error ("SSL connect error")
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Downloading file (try #2 of 10):
-- [hunter *** DEBUG *** 2018-01-04T14:42:57]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/6d8fd99/range-v3/vcpkg5-p/d8b723b/db4ff52/a49b0e5/da4b923/basic-deps.DONE
-- [hunter *** DEBUG *** 2018-01-04T14:42:57]   -> F:/Work/hunter/_Base/Cache/meta/6d8fd99/range-v3/vcpkg5-p/d8b723b/db4ff52/a49b0e5/da4b923/basic-deps.DONE
-- [hunter *** DEBUG *** 2018-01-04T14:42:57] Retry after 5 seconds (attempt #2) ...
-- [hunter *** DEBUG *** 2018-01-04T14:43:03] Download error ("SSL connect error")
-- [hunter *** DEBUG *** 2018-01-04T14:43:03] Downloading file (try #3 of 10):
-- [hunter *** DEBUG *** 2018-01-04T14:43:03]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/6d8fd99/range-v3/vcpkg5-p/d8b723b/db4ff52/a49b0e5/da4b923/basic-deps.DONE
-- [hunter *** DEBUG *** 2018-01-04T14:43:03]   -> F:/Work/hunter/_Base/Cache/meta/6d8fd99/range-v3/vcpkg5-p/d8b723b/db4ff52/a49b0e5/da4b923/basic-deps.DONE
-- [hunter *** DEBUG *** 2018-01-04T14:43:03] Retry after 5 seconds (attempt #3) ...
```

**Comment by ruslo** [comment]
This is not directly about been cacheable, I think the problem about CMake/network/certificates. Is this your local machine? What about AppVeyor remote testing?

**Comment by dvirtz** [comment]
works on AppVeyor. Should I open a new PR?

**Comment by ruslo** [comment]
Yes, sure

**Pull request merged**
