### PR TITLE
Make jsoncpp cacheable

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1714
* https://travis-ci.org/ingenue/hunter/builds/232485219?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1715
* https://travis-ci.org/ingenue/hunter/builds/232500888?utm_source=github_status&utm_medium=notification

**Comment by chfast** [comment]
When do you plan to release this?

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/releases/tag/v0.18.57

**Pull request merged**
