### PR TITLE
Fix SHA1 for manually downloaded hunter with git

### PR DESCRIPTION
**Pull request by pretyman**
When using CMake 3.0.x, with manually downloaded Hunter the examples fail with:
```
CMake Error at /home/pretyman/.hunter/gate/cmake/HunterGate.cmake:124
(string):
  string end index: 7 is out of range -1 - 1
Call Stack (most recent call first):
  /home/pretyman/.hunter/gate/cmake/HunterGate.cmake:447
(hunter_gate_self)
  /home/pretyman/.hunter/examples/common.cmake:33 (HunterGate)
  CMakeLists.txt:5 (include)
```

Because the SHA1 passed by examples/common.cmake is too short, so it
was expanded to 7 characters to avoid this error.

### CODE REVIEW

**Comment by ruslo** [comment]
@pretyman Thanks!

**Comment by pretyman** [comment]
I had loads of trouble with CMake 3.0.2 (that comes with Fedora 21) today. 

1. This error
2. Error with cached packages, with some error message along the lines of `cannot lstat .../Cache/.../raw.tar.bz2`. So I disabled the caching
3. `add_custom_command` simply would not generate the rules in the `Makefile` for the commands.

Ended up that I just went to CMake's website and downloaded 3.2.3 to make everything work again.

**Comment by ruslo** [comment]
> I had loads of trouble with CMake 3.0.2 (that comes with Fedora 21) today

If you add a simple example or the exact bug I will add a note to the README about buggy version: https://github.com/ruslo/hunter#notes-about-version-of-cmake

**Comment by pretyman** [comment]
This is what I get with CMake 3.0.2 on Fedora. I searched around to see if this is known bug, but only found references to CPack, but nothing that seemed directly related to this.
```
-- [hunter] Build step successful (dir: /home/pretyman/.hunter/_Base/xxxxxxx/d1a0cd4/e114a76/Build/SQLite3)
-- [hunter *** DEBUG *** 2015-07-11T11:14:59] Try to find stamps in directory: /home/pretyman/.hunter/_Base/xxxxxxx/d1a0cd4/e114a76/Build/SQLite3/Build
-- [hunter *** DEBUG *** 2015-07-11T11:14:59] Stamp 'done' location: /home/pretyman/.hunter/_Base/xxxxxxx/d1a0cd4/e114a76/Build/SQLite3/Build/SQLite3-prefix/src/SQLite3-stamp/SQLite3-done
-- [hunter *** DEBUG *** 2015-07-11T11:14:59] Saving to cache: SQLite3
-- [hunter *** DEBUG *** 2015-07-11T11:14:59] [/home/pretyman/.hunter/_Base/xxxxxxx/d1a0cd4/e114a76/Build/SQLite3/Install] > "/usr/bin/cmake" "-E" "tar" "cvjf" "/home/pretyman/.hunter/_Base/Cache/raw/cache.tar.bz2" "--" "share" "include" "lib" "bin"
--
CMake Error: archive_read_disk_entry_from_file: Can't lstat --
CMake Error: Problem creating tar: /home/pretyman/.hunter/_Base/Cache/raw/cache.tar.bz2

[hunter ** INTERNAL **] Packing failed
[hunter ** INTERNAL **] [Directory:/home/pretyman/.hunter/cmake/projects/SQLite3]
```

CMake 3.2.3 runs fine though.

**Comment by ruslo** [comment]
> This is what I get with CMake 3.0.2 on Fedora

Okay, I've added a note: https://github.com/ruslo/hunter#notes-about-version-of-cmake

**Comment by WesleyCeraso** [comment]
This issue was addressed in https://public.kitware.com/Bug/view.php?id=14677

Fixed in CMake 3.3

**Comment by WesleyCeraso** [comment]
I can reproduce this issue consistently using v0.12.12, but after update to v0.12.17 I can not anymore. It seems that, somehow, hunter is not affected anymore, can someone confirm it?

**Comment by ruslo** [comment]
> can someone confirm it?

@WesleyCeraso I don't see anything between `v0.12.12` and `v0.12.17` that can make such effect. What package are you building, can you provide example so I can try? Also what OS you're using?

> This issue was addressed in https://public.kitware.com/Bug/view.php?id=14677

Hunter is not using CPack for creating Cache archives (`cmake -E tar` used).

> Fixed in CMake 3.3

Alexandre reported that 3.2 works fine for him: ["CMake 3.2.3 runs fine though"][1].

[1]: https://github.com/ruslo/hunter/pull/198#issuecomment-120630877

**Comment by WesleyCeraso** [comment]
Ok, now I know what I did, and I can always reproduce the error, by the way, I'm using CMake 3.0.2.
I had previously configured another project with cmake 3.3 using v0.12.17 in the same machine, then the my .hunter folder was already populated with v0.12.17 stuff and when I changed the hunter version of the current project to v0.12.17 it just worked.

**Pull request merged**
