### PR TITLE
Update opentracing-cpp

### PR DESCRIPTION
**Pull request by isaachier**
* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/isaachier/hunter/build/1.0.369
  * https://travis-ci.org/isaachier/hunter/builds/350479459

* This update will break few old toolchains.
  They are excluded in this pull request: https://github.com/ingenue/hunter/pull/202

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3392
* https://travis-ci.org/ingenue/hunter/builds/351536539?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3393
* https://travis-ci.org/ingenue/hunter/builds/351671972?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Thanks, released: https://github.com/ruslo/hunter/releases/tag/v0.20.15

**Comment by isaachier** [comment]
Thanks again!

**Pull request merged**
