### PR TITLE
Add dlib 19.10-p3

### PR DESCRIPTION
**Pull request by xsacha**
* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "Building":

  ~~* https://ci.appveyor.com/project/xsacha/hunter-h4uji/build/1.0.8~~
  ~~* https://travis-ci.org/xsacha/hunter/builds/380572926~~
      * https://ci.appveyor.com/project/xsacha/hunter-h4uji/build/1.0.9
      * https://travis-ci.org/xsacha/hunter/builds/380577430

### CODE REVIEW

**Comment by xsacha** [comment]
Some Linux builds fail for some unrelated OpenBLAS issue

**Comment by ruslo** [comment]
Set of toolchains changed, testing old version with updated toolchains:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3963
* https://travis-ci.org/ingenue/hunter/builds/380575579?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
Oh sorry, yes. I hadn't updated ingenue.

**Comment by ruslo** [comment]
> testing old version with updated toolchains

I've removed broken toolchains. Old version with new set:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3967
* https://travis-ci.org/ingenue/hunter/builds/380614842?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3968
* https://travis-ci.org/ingenue/hunter/builds/380619515?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3969
* https://travis-ci.org/ingenue/hunter/builds/380628243?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.21.5

**Pull request merged**
