### PR TITLE
Added package xrandr

### PR DESCRIPTION
**Pull request by pretyman**
These are dependencies of package `glfw`

This pull request depends on https://github.com/ruslo/hunter/pull/465

### CODE REVIEW

**Comment by pretyman** [comment]
There a few dependencies for package `glfw`, should I open a pull request for all of them in one go when I finish? 

Or is it easier to review little by little?

**Comment by ruslo** [comment]
> This pull request depends on #465

Merged. Please update this pull request.

> Or is it easier to review little by little?

Yes, one by one. It will be easier to make tests.

**Comment by pretyman** [comment]
> Please update this pull request.
Done, pull request updated.

**Comment by ruslo** [comment]
`xrandr` testing:
* https://travis-ci.org/ingenue/hunter/builds/146919909

We need only Linux, right?

**Comment by ruslo** [comment]
`randrproto` testing:
* https://travis-ci.org/ingenue/hunter/builds/146920284

**Comment by ruslo** [comment]
Seems that `analyze` toolchain doesn't work with autotools. Will exclude.

**Comment by ruslo** [comment]
Uploading:
* https://travis-ci.org/ingenue/hunter/builds/146921459
* https://travis-ci.org/ingenue/hunter/builds/146921369

**Comment by pretyman** [comment]
> We need only Linux, right?

Hum... I cannot tell you for sure. It is definitely `glfw` for linux that depends on this package, but X11 also exists for OSX. I mean, I compiled by mistake package `x11` under OSX, thinking I was on a Linux VM and it all went without problems.

**Comment by ruslo** [comment]
> I cannot tell you for sure

This is up to you.

**Comment by pretyman** [comment]
Leave it for now and wait for the need to come to enable it on OSX

**Pull request merged**
