### PR TITLE
adding CLI11 1.8.0

### PR DESCRIPTION
**Pull request by henryiii**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/HenrySchreiner/hunter/builds/24682884
  * https://travis-ci.org/henryiii/hunter/builds/535025457

Good news: I think I finally followed the right procedure. Bad news: Something is wrong with my setup (package not found). Looking into it. Edit: Typo. Trying again. Edit: I hope that will pass now.

### CODE REVIEW

**Comment by henryiii** [comment]
All passing now.

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/24688031
- https://travis-ci.org/ingenue/hunter/builds/535114676?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/24688180
- https://travis-ci.org/ingenue/hunter/builds/535117254?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.172

**Pull request merged**
