### PR TITLE
PostgreSQL client library libpq

### PR DESCRIPTION
**Pull request by pretyman**

### CODE REVIEW

**Comment by ruslo** [comment]
Just for your information got this configure error on Linux Ubuntu:
```
cd /.../_testing/Hunter/_Base/9d52bb4/4a34a7e/b270781/Build/PostgreSQL/Source && . /.../_testing/Hunter/_Base/Download/Hunter/unknown/9d52bb4/Unpacked/scripts/clear-all.sh && AR=/usr/bin/ar ./configure AR=/usr/bin/ar LD=/usr/bin/ld NM=/usr/bin/nm OBJCOPY=/usr/bin/objcopy OBJDUMP=/usr/bin/objdump RANLIB=/usr/bin/ranlib STRIP=/usr/bin/strip CC=/usr/bin/gcc CXX=/usr/bin/g++ CXXFLAGS=-std=c++11 --disable-shared --enable-static --prefix=/.../_testing/Hunter/_Base/9d52bb4/4a34a7e/b270781/Install
configure: WARNING: unrecognized options: --disable-shared, --enable-static
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking which template to use... linux
checking whether to build with 64-bit integer date/time support... yes
checking whether NLS is wanted... no
checking for default port number... 5432
checking for block size... 8kB
checking for segment size... 1GB
checking for WAL block size... 8kB
checking for WAL segment size... 16MB
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to accept ISO C89... none needed
checking whether /usr/bin/gcc supports -Wdeclaration-after-statement... yes
checking whether /usr/bin/gcc supports -Wendif-labels... yes
checking whether /usr/bin/gcc supports -Wmissing-format-attribute... yes
checking whether /usr/bin/gcc supports -Wformat-security... yes
checking whether /usr/bin/gcc supports -fno-strict-aliasing... yes
checking whether /usr/bin/gcc supports -fwrapv... yes
checking whether /usr/bin/gcc supports -fexcess-precision=standard... yes
checking whether /usr/bin/gcc supports -funroll-loops... yes
checking whether /usr/bin/gcc supports -ftree-vectorize... yes
checking whether /usr/bin/gcc supports -Wunused-command-line-argument... no
checking whether the C compiler still works... yes
checking how to run the C preprocessor... /usr/bin/gcc -E
checking allow thread-safe client libraries... yes
checking whether to build with Tcl... no
checking whether to build Perl modules... no
checking whether to build Python modules... no
checking whether to build with GSSAPI support... no
checking whether to build with PAM support... no
checking whether to build with LDAP support... no
checking whether to build with Bonjour support... no
checking whether to build with OpenSSL support... no
checking whether to build with SELinux support... no
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ld used by GCC... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for ranlib... /usr/bin/ranlib
checking for strip... /usr/bin/strip
checking whether it is possible to strip libraries... yes
checking for ar... /usr/bin/ar
checking for a BSD-compatible install... /usr/bin/install -c
checking for tar... /bin/tar
checking whether ln -s works... yes
checking for gawk... gawk
checking for a thread-safe mkdir -p... /bin/mkdir -p
configure: WARNING:
*** Without Bison you will not be able to build PostgreSQL from Git nor
checking for bison... no
*** change any of the parser definition files.  You can obtain Bison from
*** a GNU mirror site.  (If you are using the official distribution of
*** PostgreSQL then you do not need to worry about this, because the Bison
*** output is pre-generated.)
checking for flex... no
configure: WARNING:
*** Without Flex you will not be able to build PostgreSQL from Git nor
checking for perl... /usr/bin/perl
*** change any of the scanner definition files.  You can obtain Flex from
*** a GNU mirror site.  (If you are using the official distribution of
*** PostgreSQL then you do not need to worry about this because the Flex
*** output is pre-generated.)
configure: using perl 5.18.2
checking for main in -lm... yes
checking for library containing setproctitle... no
checking for library containing dlopen... -ldl
checking for library containing socket... none required
checking for library containing shl_load... no
checking for library containing getopt_long... none required
checking for library containing crypt... -lcrypt
checking for library containing shm_open... -lrt
checking for library containing shm_unlink... none required
checking for library containing fdatasync... none required
checking for library containing sched_yield... none required
checking for library containing gethostbyname_r... none required
checking for library containing shmget... none required
checking for library containing readline... no
configure: error: readline library not found
If you have readline already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-readline to disable readline support.
```

workaround:
```
> sudo apt-get install libreadline-dev
```

**Comment by ruslo** [comment]
Next build error then:
```
'/usr/bin/perl' ./check_keywords.pl gram.y ../../../src/include/parser/kwlist.h
***
ERROR: `bison' is missing on your system. It is needed to create the
file `gram.c'. You can either get bison from a GNU mirror site
or download an official distribution of PostgreSQL, which contains
pre-packaged bison output.
***
```
Workaround:
```
> sudo apt-get install bison
```

**Comment by ruslo** [comment]
Next:
```
/usr/bin/bison -Wno-deprecated  -o bootparse.c bootparse.y
***
ERROR: `flex' is missing on your system. It is needed to create the
file `bootscanner.c'. You can either get flex from a GNU mirror site
or download an official distribution of PostgreSQL, which contains
pre-packaged flex output.
***
```
Workaround:
```
> sudo apt-get install flex
```

**Comment by ruslo** [comment]
New wiki page: https://github.com/ruslo/hunter/wiki/pkg.postgresql

**Comment by pretyman** [comment]
Thanks  for the heads up on linux compilation problems, if you want I can update the wiki on the weekend. Just let me know.

**Comment by ruslo** [comment]
> if you want I can update the wiki on the weekend

Actually it makes sense to update wiki, see: https://github.com/ruslo/hunter/wiki/pkg.postgresql

Note that it's just a workaround, the right way to fix it is to add this packages to Hunter and use them.

**Comment by pretyman** [comment]
My teacher changed the requirements to MySQL instead of PostgreSQL, so I will only available to add these packages to hunter when I finish the semester, likely mid-April.

**Comment by ruslo** [comment]
For the record, [disabling](https://github.com/ruslo/hunter/commit/13d38e4db9a6c1e722b4e0f66e4b51284dfb7329) broken tests:
* [analyze](https://travis-ci.org/ruslo/hunter/jobs/102331041)
```
exec.c:599:1: warning: Potential memory leak
}
^
1 warning generated.
```
* [ios](https://travis-ci.org/ruslo/hunter/jobs/102331040)
```
configure: error: readline header not found
```

**Pull request merged**
