### PR TITLE
add ogles_gpgpu v0.2.1

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2153
* https://travis-ci.org/ingenue/hunter/builds/264240722?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Appveyor and Travis look good.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2156
* https://travis-ci.org/ingenue/hunter/builds/264332683?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.69

**Pull request merged**
