### PR TITLE
add boringssl + test

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by headupinclouds** [comment]
I hit this during an earlier look at boringssl.  I must have installed go on my local machine previously.  If this is a build dependency (similar to a compiler, etc), and not a package dependency, I think it is reasonable to use `apt-get` or `homebrew` to configure this in the CI scripts.  Thoughts?

**Comment by ruslo** [comment]
> I think it is reasonable to use apt-get or homebrew to configure this in the CI scripts. Thoughts?

I've added installation of Go on Linux. On OSX it seems to be installed already.

Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2776
* https://travis-ci.org/ingenue/hunter/builds/300732802?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

```
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
CMake Error at crypto/CMakeLists.txt:59 (enable_language):
  No CMAKE_ASM_NASM_COMPILER could be found.
```

[This patch](https://github.com/ingenue/hunter/commit/c91e2e4291947557a3647bc81c95f7131573377c) should do [the trick](https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2781).

**Comment by headupinclouds** [comment]
boringssl

**Comment by headupinclouds** [comment]
> This patch should do the trick.

Copy and paste: https://github.com/ruslo/hunter/pull/1186/commits/249325380db141b3a54e888117d043220786bf54

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2784
* https://travis-ci.org/ingenue/hunter/builds/301053356?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2785
* https://travis-ci.org/ingenue/hunter/builds/301072168?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Follow up: https://github.com/ruslo/hunter/commit/2a00835c620870fe8b6a6a2cfdd6af6008fb06c9

Released: https://github.com/ruslo/hunter/releases/tag/v0.19.152

Usage of this library raise this issue: https://github.com/ruslo/hunter/issues/1191

**Pull request merged**
