### PR TITLE
add cmcstl2

### PR DESCRIPTION
**Pull request by dvirtz**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/dvirtz/hunter/builds/23545480
  * https://travis-ci.org/dvirtz/hunter/builds/514796795

* I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch,
  see this merged pull request https://github.com/ingenue/hunter/pull/351

---

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/23546603
- https://travis-ci.org/ingenue/hunter/builds/514818340?utm_source=github_status&utm_medium=notification

**Comment by dvirtz** [comment]
Thanks

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/23546689
- https://travis-ci.org/ingenue/hunter/builds/514819801?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.148

**Pull request merged**
