### PR TITLE
Add gcc abi dependency into the toolchain-id

### PR DESCRIPTION
**Pull request by dpantele**
Recently gcc have introduced a [dual abi](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html). Should the `_GLIBCXX_USE_CXX11_ABI` be added into the toolchain-id? Looks like it is orthogonal to `__GXX_ABI_VERSION`:

```
> cat a.cpp 
#include <iostream>
#include <string>
#include <typeinfo>

int main() {
  std::string a = "Hello world";
  std::cout << a << std::endl;
  std::cout << typeid(a).name() << std::endl;
  std::cout << __GXX_ABI_VERSION << std::endl;
}

> g++-5 -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1 a.cpp && ./a.out 
Hello world
NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
1009

> g++-5 -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 a.cpp && ./a.out 
Hello world
Ss
1009
```

### CODE REVIEW

**Comment by ruslo** [comment]
> Should the _GLIBCXX_USE_CXX11_ABI be added into the toolchain-id?

Yes I think.

> ShowPredefined.cpp

This file is autogenerated (see note in header), please add this macro to `predefined.list` file.

Also note that `create-predefined-list.py` script has `--compiler` argument. You can test your version of gcc and see if `_GLIBCXX_USE_CXX11_ABI` added by it (may be some others will be added too).

**Comment by dpantele** [comment]
Ok, I ran
```
create-predefined-list.py --raw predefined.list --compiler g++-5
create-predefined-list.py --raw predefined.list --compiler g++-6
```

and here are all the changes. Actually, I had to add _GLIBCXX_USE_CXX11_ABI manually, `--compiler` does not add it.

**Comment by ruslo** [comment]
Something went wrong:
* https://travis-ci.org/ingenue/hunter/builds/133393990

@dpantele can you please take a look? Thanks.

**Comment by dpantele** [comment]
Ok, one of the build gives the following error:
```
/wd/ingenue/hunter/_testing/Hunter/_Base/Download/Hunter/unknown/3bc32f7/Unpacked/scripts/ShowPredefined.cpp:2371:30: error: 
      __has_include must be used within a preprocessing directive
# pragma message(HUNTER_INFO(__has_include))
                             ^
# pragma message(HUNTER_INFO(__has_include_next))
                             ^
/wd/ingenue/hunter/_testing/Hunter/_Base/Download/Hunter/unknown/3bc32f7/Unpacked/scripts/ShowPredefined.cpp:2375:30: error: 
      __has_include_next must be used within a preprocessing directive
```

I guess that `__has_include` and `__has_include_next` could be removed from the list

**Comment by dpantele** [comment]
Travis has a bad day today: https://travis-ci.org/ruslo/hunter/builds/134772102 failed because of some network issue, rerunning it https://travis-ci.org/ruslo/hunter/builds/134805853

**Comment by ruslo** [comment]
Okay. Can you please add them to list and leave a comment to this discussion:
* https://github.com/ruslo/hunter/blob/0380dbd81b80007f4c9c3d01e309d9820a833619/scripts/create-predefined-list.py#L60

Then regenerate `ShowPredefined.cpp` file and check that it work. Thanks.

**Comment by dpantele** [comment]
Done.

`ShowPredefined.cpp` and `predefined.list` has not changed after running `./create-predefined-list.py --compiler g++-5 --raw predefined.list` since I've manually excluded `__has_include` and `__has_include_next` in https://github.com/ruslo/hunter/pull/425/commits/4dda58464693ce7559c40fd31eeddd69764ca8b7

CI runs:
https://ci.appveyor.com/project/ruslo/hunter/build/1.0.300
https://travis-ci.org/ruslo/hunter/builds/135110300

**Comment by ruslo** [comment]
Thanks, let's see what will happen with the real package, like GTest:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.478
* https://travis-ci.org/ingenue/hunter/builds/135128623

**Comment by ruslo** [comment]
> let's see what will happen with the real package, like GTest

Everything works fine. It's okay to merge it now but this require to do some binary cache update of packages from my side to keep the system consistent (local upload of Qt, OpenCV). I'm not able to do it right now. Will do it as soon as possible.

**Comment by dpantele** [comment]
Ok, that's fine. But I am not sure if toolchain-id changes now for any https://github.com/ruslo/polly platform, since there is no gcc-{5,6}.

**Comment by ruslo** [comment]
> But I am not sure if toolchain-id changes now for any https://github.com/ruslo/polly platform, since there is no gcc-{5,6}

It does, here is `gcc-4.8.4` diff:
```
12d11
< #define _GNU_SOURCE 1
15d13
< #define _STDC_PREDEF_H 1
66d63
< #define __DECIMAL_BID_FORMAT__ 1
70d66
< #define __ELF__ 1
102d97
< #define __GCC_HAVE_DWARF2_CFI_ASM 1
111d105
< #define __GNUC_STDC_INLINE__ 1
116d109
< #define __GXX_EXPERIMENTAL_CXX0X__ 1
203,206d195
< #define __STDC_IEC_559_COMPLEX__ 1
< #define __STDC_IEC_559__ 1
< #define __STDC_ISO_10646__ 201103L
< #define __STDC_NO_THREADS__ 1
253d241
< #define __gnu_linux__ 1
257d244
< #define __linux__ 1
259d245
< #define __unix__ 1
```

I guess I haven't updated it for some time...

**Pull request merged**
