### PR TITLE
Update Eigen to hunter-fork 3.3.1-p2

### LINKED ISSUE #628: Building Eigen when Boost installed
Configuration:
```cmake
hunter_add_package(Boost)
hunter_add_package(Eigen)
```
Will fail on Eigen build step (if Eigen is not taken from cache). The reason is that `find_package(Boost)` called in Eigen code but there is no `hunter_add_package(Boost)`. Conflict is similar to:
* https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#conflict

Fix is to "hunterize" Eigen. Workaround is to add option to exclude tests (`find_package(Boost)` needed only for tests).

New test added:
* https://travis-ci.org/ingenue/hunter/jobs/186519682

@NeroBurner I will revert https://github.com/ruslo/hunter/pull/626 partially. Default version will be `3.2.4-p0`.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40369871-building-eigen-when-boost-installed?utm_campaign=plugin&utm_content=tracker%2F1032790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1032790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by NeroBurner**
I can't find development branch, therefore submitting to master

Edit: should fix #628

### CODE REVIEW

**Comment by NeroBurner** [comment]
please don't yet merge. I got some feedback on https://bitbucket.org/eigen/eigen/pull-requests/287/add-cmake-option-to-enable-disable/diff#comment-29055582

**Comment by ruslo** [comment]
> I can't find development branch, therefore submitting to master

I have updated contributing guide:
* https://github.com/ruslo/hunter/wiki/dev.contribution

It's okay to use `master`.

**Comment by headupinclouds** [comment]
@NeroBurner : What is the latest plan for this?  Thanks!

**Comment by NeroBurner** [comment]
Either we wait for upstream to merge, or (what I prefer) we hope upstream will merge the patch with the next release and this release we use our fork with the same patch

On January 10, 2017 11:54:40 PM GMT+01:00, David Hirvonen <notifications@github.com> wrote:
>@NeroBurner : What is the latest plan for this?  Thanks!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ruslo/hunter/pull/629#issuecomment-271724406

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NeroBurner** [comment]
@headupinclouds I misread your earlier post. Over at our eigen-hunter-fork I've got the pull request open to implement `BUILD_TESTING`.
https://github.com/hunter-packages/eigen/pull/3

I hope eigen-upstream will merge the `BUILD_TESTING`-option. I'm waiting for ruslo to accept the hunter-packages/eigen-pull request and release a `eigen_3.3.1-p1`. This release I would then add to hunter by updating this pull request

**Comment by headupinclouds** [comment]
@NeroBurner : This should work:

```
hunter_add_version(
    PACKAGE_NAME
    Eigen
    VERSION
    "3.3.1-p1"
    URL
    "https://github.com/hunter-packages/eigen/archive/v3.3.1-p1.tar.gz"
    SHA1
    71f7da8c5170ea4500531b5c98a3c3cb871feab2
)
```

I just realized the previous release was in `bz2` format.  I'm guessing @ruslo used [this](https://github.com/ruslo/hunter/issues/643#issuecomment-272205535) script to create a compressed bz2 release.   The current package size is 1.4 MB, which seems reasonable.

**Comment by NeroBurner** [comment]
if you mean the 3.3.1 version then it was the upstream tar.bz2 file.
I'll send the pull request tomorrow

**Comment by NeroBurner** [comment]
rebased on current master, update to hunter-fork 3.3.1-p1

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1318
* https://travis-ci.org/ingenue/hunter/builds/192059813

**Comment by ruslo** [comment]
All tests failed

**Comment by NeroBurner** [comment]
Updated to 3.3.1-p2

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1321
* https://travis-ci.org/ingenue/hunter/builds/192296877

**Comment by ruslo** [comment]
> Testing

The Boost related issue is still present:
* https://travis-ci.org/ingenue/hunter/jobs/192296899

**Comment by NeroBurner** [comment]
I forgot to rename the cmake argument `EIGEN_ENABLE_TESTS` to `BUILD_TESTING`. I hope it works now

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1322
* https://travis-ci.org/ingenue/hunter/builds/192321536

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1323
* https://travis-ci.org/ingenue/hunter/builds/192331868

**Comment by ruslo** [comment]
Released:
* https://github.com/ruslo/hunter/releases/tag/v0.17.15

**Pull request merged**
