### PR TITLE
sse2neon

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1507
* https://travis-ci.org/ingenue/hunter/builds/217767278

**Comment by headupinclouds** [comment]
Thanks.  I'll add a build test next time.

**Comment by headupinclouds** [comment]
This package isa bout SSE to NEON translation and is only expected to work on NEON platforms (i.e., iOS and Android). We should remove all non NEON TOOLCHAINS from CI.

**Comment by ruslo** [comment]
> We should remove all non NEON TOOLCHAINS from CI

Done.

Uploading:
* https://travis-ci.org/ingenue/hunter/builds/217780402

**Comment by headupinclouds** [comment]
Thanks.  For future reference...  In addition to the skeleton build test, Is there some place a list of toolchains should be provided with each PR to make it complete, or is that something you do as needed in `ingenue`?  

Should Appveyor + Travis be enabled by default for `hunter-packages` so that some of the platform build issue tests can be caught early on?

**Comment by ruslo** [comment]
> In addition to the skeleton build test, Is there some place a list of toolchains should be provided with each PR to make it complete, or is that something you do as needed in ingenue?

Yes in `ingenue`, each package has a `pkg.<package-name>` branch with corresponding list of toolchains for testing.

> Should Appveyor + Travis be enabled by default for hunter-packages so that some of the platform build issue tests can be caught early on?

Yes it's possible but `.travis.yml`/`appveyor.yml` configs for Hunter CI and package itself doesn't match, so it should be done separately.

**Comment by ruslo** [comment]
> configs for Hunter CI and package itself doesn't match

Note that also Hunter do integration test (i.e. it tests correctness of `*Config.cmake` file) which is tricky for regular testing. Though as you noticed we will catch errors like unsupported toolchains earlier.

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.18.35
Wiki page: https://github.com/ruslo/hunter/wiki/pkg.sse2neon
List updated: https://docs.hunter.sh/en/latest/packages/all.html

**Comment by headupinclouds** [comment]
>> In addition to the skeleton build test, Is there some place a list of toolchains should be provided with each PR to make it complete, or is that something you do as needed in ingenue?

> Yes in ingenue, each package has a pkg.<package-name> branch with corresponding list of toolchains for testing.

I'd like to sketch the end-to-end process in more detail as a reference for contributions.  Your feedback would be much appreciated.  If the basic structure is in place I can add more details.  Please let me know if this type of thing exists in current documentation.  So a typical PR will consist of:

0) Request `hunter-package` as needed here: https://github.com/ruslo/hunter/issues
   - upstream package is preferable where feasible or where SHA1 is necessary (OpenSSL, etc)
   - a new `hunter-package` is required for packages that
     + lack usable root directory CMakeLists.txt or autoconf files
     + don't have a clean install and package config export in existing CMakeLists.txt
     + have additional dependencies (that should be managed by `hunter_add_package()`)

1) Initial `hunter-package` PR ; Role: GitHub account; ex: https://github.com/hunter-packages/sse2neon/pull/1
    - TODO: sample git commands here

2) TODO: Optional CI  build testing here (and possible unit testing via `PACKAGE_BUILD_TEST=ON` w/ `polly --test`)
  - Setup : Role = Appveyor/Travis config administrator of `hunter-packages`?  
  - Testing (after initial setup) : Role = Github account (testing is automated once CI hooks are setup)
Note: I'm not sure if this would be more or less work for you.  

3) Create a `hunter-package` release/tag:
Role: A `hunter-package` member 
ex: https://github.com/hunter-packages/sse2neon/releases
  - Copy "Source code (tar.gz)" link in release page above (right click + copy)
  - `> URL=https://github.com/hunter-packages/sse2neon/archive/v1.0.0-p0.tar.gz`
  - `> wget ${URL}`
  - `> SHA=$(shasum v1.0.0-p0.tar.gz | awk '{print $1}')`
  - `> ./some_create_package_script.sh sse2neon 1.0.0-p0 ${URL} ${SHA} > hunter.sse2neon..cmake` to produce entry like this:

hunter.sse2neon.cmake:
```
hunter_add_version(
    PACKAGE_NAME
    sse2neon
    VERSION
    1.0.0-p0
    URL
    "https://github.com/hunter-packages/sse2neon/archive/v1.0.0-p0.tar.gz"
    SHA1
    1a3104782526ea6aba9e5429dc64414e91b4cf1c
)
```

TODO: additional automation?

  - Add formatted entry to hunter cmake project (copy and paste above text): https://github.com/ruslo/hunter/blob/v0.18.35/cmake/projects/sse2neon/hunter.cmake

3) Create the `hunter` PR  : 
  - add package: https://github.com/ruslo/hunter/blob/v0.18.35/cmake/projects/sse2neon/hunter.cmake
  - update default hunter version for package https://github.com/ruslo/hunter/blob/v0.18.35/cmake/configs/default.cmake#L187
  - add the skeleton build test https://github.com/ruslo/hunter/tree/master/examples/sse2neon
     + https://github.com/ruslo/hunter/blob/master/examples/sse2neon/CMakeLists.txt
     + https://github.com/ruslo/hunter/blob/master/examples/sse2neon/foo.cpp
  - TODO: local testing via ${HUNTER_ROOT} (TODO...)
  - send the PR https://github.com/ruslo/hunter/pull/741

4) How does a user provide necessary `ingenue` testing here?

@ruslo :point_up:  I'm unclear on how users can help provide the `ingenue` testing here.

**Comment by ruslo** [comment]
> How does a user provide necessary ingenue testing here?

I'm creating `ingenue/pkg.<package>` branch for testing with independent `.travis.yml`/`appveyor.yml`. If the tests failed user have to investigate the problems and fix/exclude toolchains.

>  I guess this relates to the automation service: #449

Yes, related, also I've openned https://github.com/ruslo/hunter/issues/743

**Pull request merged**
