### PR TITLE
type_safe 0.2.1

### PR DESCRIPTION
**Pull request by dvirtz**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/dvirtz/hunter/builds/22439437
  * https://travis-ci.org/dvirtz/hunter/builds/494614194

pending PR on CI fork: https://github.com/ingenue/hunter/pull/336

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22441371
- https://travis-ci.org/ingenue/hunter/builds/494651202?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22441620
- https://travis-ci.org/ingenue/hunter/builds/494654331?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.109

**Comment by ruslo** [comment]
`pkg.type_safe` is failing after upload:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22441979
- https://travis-ci.org/ingenue/hunter/builds/494659331?utm_source=github_status&utm_medium=notification

That's because full path saved in configs, e.g. in archive:
- https://github.com/ingenue/hunter-cache/releases/download/cache-1ca4144/1ca414440d0d2168929a71531a73df96795b3c08.tar.bz2

In file `lib/cmake/type_safe/type_safe-targets.cmake` (see `INTERFACE_SOURCES`):
```
set_target_properties(type_safe PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "TYPE_SAFE_ENABLE_ASSERTIONS=1;TYPE_SAFE_ENABLE_PRECONDITION_CHECKS=1;TYPE_SAFE_ENABLE_WRAPPER=1;TYPE_SAFE_ARITHMETIC_UB=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "debug_assert"
  INTERFACE_SOURCES "/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/f7ef7e7/9b6134b/a41f4bb/Build/type_safe/Source/"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```

**Comment by dvirtz** [comment]
I assume the problematic line is https://github.com/hunter-packages/type_safe/blob/hunter/CMakeLists.txt#L98 but as it uses `BUILD_INTERFACE` shouldn't it be empty on installation?

When I look at the contents of `lib/cmake/type_safe/type_safe-targets.cmake` in the place where I ran `jenkins.py` the `INTERFACE_SOURCES` line is not there.

**Comment by ruslo** [comment]
> I assume the problematic line is https://github.com/hunter-packages/type_safe/blob/hunter/CMakeLists.txt#L98 but as it uses BUILD_INTERFACE shouldn't it be empty on installation?

Variable is a list and there is a space, maybe something went wrong in such configuration.

> When I look at the contents of lib/cmake/type_safe/type_safe-targets.cmake in
> the place where I ran jenkins.py the INTERFACE_SOURCES line is not there

Are you sure? On my Linux machine:

```
> cmake --version
cmake version 3.13.3

> TOOLCHAIN=gcc PROJECT_DIR=examples/type_safe ./jenkins.py

> grep -IR SOURCES /.../hunter/_testing/Hunter/_Base/9c421bd/427fd52/a41f4bb/Install/lib/cmake/type_safe
/.../hunter/_testing/Hunter/_Base/9c421bd/427fd52/a41f4bb/Install/lib/cmake/type_safe/type_safe-targets.cmake:
  INTERFACE_SOURCES "/.../hunter/_testing/Hunter/_Base/9c421bd/427fd52/a41f4bb/Build/type_safe/Source/"
```

**Comment by dvirtz** [comment]
fixed in #1766

**Pull request merged**
