### PR TITLE
Added package xcursor

### PR DESCRIPTION
**Pull request by pretyman**
Dependency of `glfw`

### CODE REVIEW

**Comment by ruslo** [comment]
Testing: https://travis-ci.org/ingenue/hunter/builds/148498138

**Comment by ruslo** [comment]
Uploading: https://travis-ci.org/ingenue/hunter/builds/148499644

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.15.4

**Comment by pretyman** [comment]
Thanks!

**Pull request merged**
