### PR TITLE
OpenCV 3.2.0-p0

### PR DESCRIPTION
**Pull request by Ubiquite**
release OpenCV 3.2.0-p0

### CODE REVIEW

**Comment by ruslo** [comment]
Travis CI behaves strangely, I can't load build logs properly. Let's wait 🕐

**Comment by Ubiquite** [comment]
seems fine now

**Comment by ruslo** [comment]
I've updated 3.1.0 version, now we have conflict here. Can you please resolve it. Thanks.

**Comment by Ubiquite** [comment]
done

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1399
* https://travis-ci.org/ingenue/hunter/builds/207390204

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1401
* https://travis-ci.org/ingenue/hunter/builds/207606238

**Comment by ruslo** [comment]
Released https://github.com/ruslo/hunter/releases/tag/v0.18.10

**Pull request merged**
