### PR TITLE
Added package glm

### PR DESCRIPTION
**Pull request by pretyman**
This is a header only package, how should it be treated `CONFIGURATION_TYPES` wise, as it doesn't really build?

Looking at the CMakeLists.txt (https://github.com/g-truc/glm/blob/master/CMakeLists.txt) of this package, there seems to be toolchain settings in it, is there anything to be done about it, or rather leave the original to be?

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.768
* https://travis-ci.org/ingenue/hunter/builds/150604225

> This is a header only package, how should it be treated CONFIGURATION_TYPES wise, as it doesn't really build?

Keep it as is. In fact even if library is header only it can have dependencies and can have usage requirements that differs for different build types, e.g. FOO_DEBUG=1 for Debug. If you worry about performance then build/install procedure of header only library is just copying of files - pretty fast.

> there seems to be toolchain settings in it, is there anything to be done about it, or rather leave the original to be?

Like what? Rules as usual - respect defaults and user's settings: https://github.com/ruslo/hunter/wiki/usr.adding.new.package#default-behaviour. It would be nice to do cleanups but on practice we can wait until something bad happen :)

**Comment by pretyman** [comment]
> It would be nice to do cleanups but on practice we can wait until something bad happen :)

Cool, if tests pass, then merge please ;-)

**Comment by ruslo** [comment]
> Cool, if tests pass, then merge please ;-)

Some of them fail. Need to investigate, please send fix/patches with excludes. As usual.

**Comment by pretyman** [comment]
> If you worry about performance then build/install procedure of header only library is just copying of files - pretty fast.

I was worried about unnecessary copies of the header files over each other, as it wears down the SSD I've paid one kidney for.

> Some of them fail. Need to investigate, please send fix/patches with excludes. As usual.

Ok, tonight I'll look at it

**Comment by ruslo** [comment]
> I was worried about unnecessary copies of the header files over each other, as it wears down the SSD I've paid one kidney for

You can set only one build type by modifying CONFIGURATION_TYPES of the package but I really don't think it will make any significant difference. If package built from source there are much more unoptimal procedures. Also from my experience SSD has pretty good reserve about writes, my directory with Hunter is on SSD for example and it seems good. I think this is kind of spooky tale about SSD :)

**Comment by pretyman** [comment]
Linux is failing because in:
```CMake
# install pkg-config file
install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/glm.pc"
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/pkgconfig"
)
```
`${CMAKE_INSTALL_LIBDIR}/pkgconfig` is expanding to: root-id/Build/glm/Install/lib/**x86_64-linux-gnu**/pkgconfig

Then patching unrelocatable files does not take **x86_64-linux-gnu** into account and fails with: 
```
[hunter ** FATAL ERROR **] File not exists:
[hunter ** FATAL ERROR **]   /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/6710c06/5c4580a/8928885/Build/glm/Install/lib/pkgconfig/glm.pc
```

Gonna need some minor patching in `glm`'s CMake scripts to have install to destination `lib/pkgconfig`.

Can you please create a hunter-package repo for it?

**Comment by pretyman** [comment]
> In fact even if library is header only it can have dependencies and can have usage requirements that differs for different build types, e.g. FOO_DEBUG=1 for Debug.

I think I will set `glm`'s build configuration type to Release because (as far as I understood) the pkgconfig file does not understand multiple builds, what do you think?

**Comment by ruslo** [comment]
> Can you please create a hunter-package repo for it?

Done: https://github.com/hunter-packages/glm

> I think I will set glm's build configuration type to Release because (as far as I understood) the pkgconfig file does not understand multiple build configuration, what do you think?

But CMake does. If somebody need one build type configuration he can always set it locally.

**Comment by pretyman** [comment]
Updated. 

Please re-run tests.

**Comment by ruslo** [comment]
> Please re-run tests

Sorry, can't do it right now. It seems that Travis Linux images updated recently carrying some bugs :( It breaks all builds that use python requests module. Probably it's related to [this](https://www.traviscistatus.com/incidents/2p40l49r3yxd), hope it will be fixed soon or I will able to find some workaround.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.770
* https://travis-ci.org/ingenue/hunter/builds/151414053

**Comment by ruslo** [comment]
> Testing

Failed. Need to investigate.

**Comment by pretyman** [comment]
Updated this pull request with a tagged version of `hunter-packages/glm`. 

Failing tests were removed from ingenue, please merge that first ;-)

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.776
* https://travis-ci.org/ingenue/hunter/builds/151742822

**Comment by pretyman** [comment]
Thanks!

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.777
* https://travis-ci.org/ingenue/hunter/builds/151841451

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.15.10

**Pull request merged**
