### PR TITLE
Added package glew

### PR DESCRIPTION
**Pull request by pretyman**
Contains a workaround for patching unrelocatable x11 libraries while https://github.com/ruslo/hunter/issues/486 is not implemented

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.782
* https://travis-ci.org/ingenue/hunter/builds/152047376

**Comment by ruslo** [comment]
> Testing

Failed. Cleanup needed.

**Comment by pretyman** [comment]
> Failed. Cleanup needed.

Ok, will remove broken tests.

I'm having issues with namespace "glew", guess I will have to remove it. Maybe you will have a suggestion how to deal with this: in emscripten I need that targets that use the glew package to add `-s LEGACY_GL_EMULATION=1` linking flag.

So I tried:

```CMake
  add_library(glew::glew IMPORTED INTERFACE)
  set_target_properties(glew::glew PROPERTIES
      IMPORTED_LINK_INTERFACE_LIBRARIES "-s LEGACY_GL_EMULATION=1"
  )
```
Results in:
```
CMake Error at /Users/discipline/Development/emsdk_portable/emscripten/incoming/cmake/Modules/Findglew.cmake:6 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_LINK_INTERFACE_LIBRARIES" is not allowed.
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)
```

So I tried to make an IMPORTED STATIC target:
```CMake
  add_library(glew::glew IMPORTED STATIC)
  set_target_properties(glew::glew PROPERTIES
      IMPORTED_LOCATION ""
      IMPORTED_LINK_INTERFACE_LIBRARIES "-s LEGACY_GL_EMULATION=1"
  )
```

Which results in:
```
-- Build files have been written to: /Users/discipline/Development/comp371-opengl-skeleton/_builds/emscripten-cxx11-Debug
/Users/discipline/Development/cmake-patched/bin/cmake -E cmake_progress_start /Users/discipline/Development/comp371-opengl-skeleton/_builds/emscripten-cxx11-Debug/CMakeFiles /Users/discipline/Development/comp371-opengl-skeleton/_builds/emscripten-cxx11-Debug/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/comp371-opengl-skeleton.dir/build.make CMakeFiles/comp371-opengl-skeleton.dir/depend
CMakeFiles/comp371-opengl-skeleton.dir/build.make:97: *** target pattern contains no `%'.  Stop.
make[1]: *** [CMakeFiles/comp371-opengl-skeleton.dir/all] Error 2
make: *** [all] Error 2
Command exit with status "2": [/Users/discipline/Development/comp371-opengl-skeleton]> "cmake" "--build" "/Users/discipline/Development/comp371-opengl-skeleton/_builds/emscripten-cxx11-Debug" "--config" "Debug" "--"
```

So then I went without IMPORTED, but that has problems with the double colon:
```CMake
  add_library(glew::glew INTERFACE)
  set_target_properties(glew::glew PROPERTIES
      IMPORTED_LINK_INTERFACE_LIBRARIES "-s LEGACY_GL_EMULATION=1"
  )
```

Results in:
```
CMake Error at /Users/discipline/Development/emsdk_portable/emscripten/incoming/cmake/Modules/Findglew.cmake:5 (add_library):
  The target name "glew::glew" is reserved or not valid for certain CMake
  features, such as generator expressions, and may result in undefined
  behavior.
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)
```

Trying to use `target_link_libraries(... INTERFACE ..)` on the imported target:
```CMake
  add_library(glew::glew INTERFACE IMPORTED)
  target_link_libraries(glew::glew INTERFACE "-s LEGACY_GL_EMULATION=1")
```

Resulted in:
```
CMake Error at /Users/discipline/Development/emsdk_portable/emscripten/incoming/cmake/Modules/Findglew.cmake:6 (target_link_libraries):
  Cannot specify link libraries for target "glew::glew" which is not built by this
  project.
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)
```

The **only** way I got this target to work was:
```CMake
  add_library(glew INTERFACE)
  target_link_libraries(glew INTERFACE "-s LEGACY_GL_EMULATION=1")
```

I will update the code to remove the namespace, if there is no objection. The `glew` CMakeLists.txt was made from scratch using your package-example, so its not like we are going to cause some havoc and break everything.

**Comment by ruslo** [comment]
> Maybe you will have a suggestion how to deal with this: in emscripten I need that targets that use the glew package to add -s LEGACY_GL_EMULATION=1 linking flag

I haven't used that toolchain so I'm not sure that is happening here and what you're trying to do. As far as I remember you said that emscripten has it's own glew library, so installation of package glew will not happen in fact, right? So you're trying to add glewConfig.cmake with target glew::glew from emscripten environment? I guess it will be similar to [Boost](https://github.com/ruslo/hunter/blob/master/cmake/templates/BoostConfig.cmake.in) then:

```cmake
add_library(${_boost_lib} STATIC IMPORTED)

set_property(
    TARGET "${_boost_lib}" APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG
)

set_target_properties(
    "${_boost_lib}"
    PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
    IMPORTED_LOCATION_DEBUG "${_lib_debug}"
)
```

> CMakeFiles/comp371-opengl-skeleton.dir/build.make:97: *** target pattern contains no `%'.  Stop.

This is happening because of `IMPORTED_LOCATION ""` - put the real path here.

**Comment by pretyman** [comment]
> so installation of package glew will not happen in fact, right?

Yeah, there is no file to install, its all built in. What is happening is that I can't set INTERFACE link flags on IMPORTED targets, so the only solution seems to be to do drop namespace qualifiers and use:

```CMake
add_library(glew INTERFACE)
target_link_libraries(glew INTERFACE "-s LEGACY_GL_EMULATION=1")
```

Like this I can get the same CMakeLists.txt to compile on OSX and JavaScript with `target_link_libraries(MyApp PUBLIC glew ...)`

**Comment by ruslo** [comment]
> Yeah, there is no file to install, its all built in

Just to clarify, there is no library installed by Hunter **and** there is no library in emscripten environment - instead of library we have just additional options. Then yes, from the CMake point of view it's not a static library, it's an interface library, just like header-only libraries. This should work:

```cmake
add_library(glew::glew INTERFACE IMPORTED)
set_target_properties(
    glew::glew
    PROPERTIES
    INTERFACE_LINK_LIBRARIES "-s LEGACY_GL_EMULATION=1"
)
```

**Comment by pretyman** [comment]
Thanks, tried what you suggested, but I guess CMake won this time:

```
CMake Error at /Users/discipline/Development/emsdk_portable/emscripten/incoming/cmake/Modules/Findglew.cmake:7 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "LINK_INTERFACE_LIBRARIES" is not allowed.
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)
```

**Comment by pretyman** [comment]
Updated this pull request.

Commented failing tests on https://github.com/ingenue/hunter/pull/28, please merge that first.

**Comment by ruslo** [comment]
> The  property "LINK_INTERFACE_LIBRARIES" is not allowed.

It's not `LINK_INTERFACE_LIBRARIES`, it's `INTERFACE_LINK_LIBRARIES` :)

**Comment by ruslo** [comment]
As a hint you can take some header only library, e.g. https://github.com/ruslo/leathers and add `target_link_libraries(... INTERFACE "-something")` and see what will happen after it installed.

**Comment by pretyman** [comment]
> It's not LINK_INTERFACE_LIBRARIES, it's INTERFACE_LINK_LIBRARIES :)

Jesus, I'm completely retarded, that **worked**, let me undo the changes related to namespace, thanks ALOT.

**Comment by pretyman** [comment]
Ok, updated this pull request, thanks for all the help, I was going crazy here

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.789
* https://travis-ci.org/ingenue/hunter/builds/152138608

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.790
* https://travis-ci.org/ingenue/hunter/builds/152139840

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.15.13

**Comment by headupinclouds** [comment]
@pretyman (+ @ruslo): Thanks for your work on this.  We were able to use this to add MSVC functionality to the https://github.com/hunter-packages/ogles_gpgpu shader framework.  It was such a relief to see this was available in hunter after realizing MSVC required this functionality.

**Pull request merged**
