### PR TITLE
update dmlc-core

### PR DESCRIPTION
**Pull request by headupinclouds**
dmlc-core @ 0.0.0-p1

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3214
* https://travis-ci.org/ingenue/hunter/builds/326862555?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
All passed

**Comment by ruslo** [comment]
> All passed

?

Waiting for OSX:
* https://travis-ci.org/ingenue/hunter/builds/326862555?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Ooops.  Different window.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3219
* https://travis-ci.org/ingenue/hunter/builds/326923524?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.225

**Pull request merged**
