### PR TITLE
Android-apk update (fix for "armv7a with NEON" ANDROID_ABI); Added OpenCV 3.0.0 package and set ENABLE_NEON=ON for Android by default (same as is_ios); Added patch to cvmatio (temporary fix for finding OpenCV w/ Android) to get things building

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by ruslo** [comment]
@headupinclouds I see no actual difference between your version of OpenCV and `hunter-packages/OpenCV`. So does Debug build works fine for you?

**Comment by headupinclouds** [comment]
The hunter-packages one was just posted this morning, right?  This was just the result of merging your hunter changes into the full 3.0.0 release, so there isn't anything special about this one.  In general I think centralized hunter-packages hosting is cleaner, but since there isn't a way of pushing new packages upstream right now, and I didn't see an OpenCV 3.0.0 in hunter, I just created a release in my account to get it working in the develop branch.  

The Debug build is working with the OpenCV 3.0.0 package with the addition of 
```
BUILD_ANDROID_EXAMPLES=OFF
```
```
[100%] Built target OpenCV-Debug
/usr/local/bin/cmake -E cmake_progress_start /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/9aed0f2/a23c9fa/Build/OpenCV/Build/CMakeFiles 0
-- [hunter] Build step successful (dir: /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/9aed0f2/a23c9fa/Build/OpenCV)
```

I also saw BUILD_ANDROID_SERVICE and turned that off as well.  I'll need to add that to the pull request, or we can merge it and apply that on top of it.

```
if(ANDROID)
  set(_android_args 
    ENABLE_NEON=ON
    BUILD_ANDROID_SERVICE=OFF
    BUILD_ANDROID_EXAMPLES=OFF
    )
else()
  set(_android_args "")
endif()
```

**Comment by ruslo** [comment]
> The hunter-packages one was just posted this morning, right?

Yep, just created it after you open this pull request.

> The Debug build is working with the OpenCV 3.0.0 package with the addition of BUILD_ANDROID_EXAMPLES=OFF

That's where I stopped last time when testing it.

> I also saw BUILD_ANDROID_SERVICE and turned that off as well

Okay, I'll take a look. Probably will add this too, thanks

> In general I think centralized hunter-packages hosting is cleaner, but since there isn't a way of pushing new packages upstream right now, and I didn't see an OpenCV 3.0.0 in hunter, I just created a release in my account to get it working in the develop branch. 

I guess you can use your releases while testing/customizing then send me pull requests when everything good. Also I've added you to `hunter-packages/OpenCV` collaborators.

**Comment by headupinclouds** [comment]
Added BUILD_ANDROID_EXAMPLES=OFF to this pull request.  Feel free to rework as you see fit.

**Comment by ruslo** [comment]
> Added BUILD_ANDROID_EXAMPLES=OFF to this pull request. Feel free to rework as you see fit

Applied as: https://github.com/ruslo/hunter/commit/7935bdd5756b034db8ad2fec3c87036ac59aebb0

> I also saw BUILD_ANDROID_SERVICE and turned that off as well

By default this option is turned off. You can verify it by configure logs of OpenCV:

```
  Android:
    ...
    Google Play manager: OFF
```

**Comment by headupinclouds** [comment]
That pull request also enabled neon for Android by default (just mirroring the _ios_args you already had in there).


```
if(ANDROID)
  set(_android_args 
    ENABLE_NEON=ON
    BUILD_ANDROID_SERVICE=OFF
    BUILD_ANDROID_EXAMPLES=OFF
    )
else()
  set(_android_args "")
endif()
```

**Comment by ruslo** [comment]
> That pull request also enabled neon for Android by default (just mirroring the _ios_args you already had in there)

I saw it, just want to check. I see that there is some logic in OpenCV already:
```cmake
if (ANDROID)
  if (ANDROID_ABI MATCHES "NEON")
    set(ENABLE_NEON ON)
  endif()
  # ...
endif()
```

So do you think it's not enough? Also I guess we can build Android with `x86` architecture so there is no need to add `ENABLE_NEON` in such case. By the way we can set this option in toolchain (i.e. for all projects).

**Comment by ruslo** [comment]
> -hunter_config(Android-Apk VERSION 1.1.1)
> +hunter_config(Android-Apk VERSION 1.1.3)

I've merged [your patches](https://github.com/hunter-packages/android-apk/commits?author=headupinclouds) into [hunter-packages/android-apk](https://github.com/hunter-packages/android-apk).

Applied as: https://github.com/ruslo/hunter/commit/9159255e248e29f2b01a202fe84d2154ad32f470

**Comment by ruslo** [comment]
> -hunter_config(OpenCV VERSION 3.0.0-rc1-p0)
> +hunter_config(OpenCV VERSION 3.0.0-p0)

Applied as: https://github.com/ruslo/hunter/commit/81388c07f46bff6dd2c981363153b12e505b8045

**Comment by ruslo** [comment]
> -hunter_config(cvmatio VERSION 1.0.12)
> +hunter_config(cvmatio VERSION 1.0.26)

Your patches merged into [hunter-packages/cvmatio](https://github.com/hunter-packages/cvmatio).

Applied as: https://github.com/ruslo/hunter/commit/7e4b6c45fb85df2ec5603a66c91d93d895060ade

**Comment by ruslo** [comment]
@headupinclouds everything from this pull request merged to branch `develop`. The only change left is about [ENABLE_NEON](https://github.com/ruslo/hunter/pull/171#issuecomment-111685635)

**Comment by headupinclouds** [comment]
You are right regarding non ARM/Neon Android platforms, and thanks for finding the neon toolchain test:

```
if (ANDROID)
  if (ANDROID_ABI MATCHES "NEON")
    set(ENABLE_NEON ON)
  endif()
  # ...
endif()
```

I think that should be sufficient and I expect that should be fairly constant, so it seems better not to merge the _android_flags neon part.

While we're discussing this.  I wonder how often the other OpenCV defaults in CMakeLists.txt change... whether it is better to model the CMAKE_ARG differences for each release (which may be subject to change) or just define the full set of options explicitly somewhere.

**Comment by headupinclouds** [comment]
BTW, did you have any thoughts on the ANDROID find_package(opencv) failure?  I fixed that internally in cvmatio (the only hunter package with internal opencv dependencies) using this hack:

```
if(ANDROID) ### Temporary hack for OpenCV Android builds
  set(OpenCV_DIR "${HUNTER_TOOLCHAIN_ID_PATH}/Install/sdk/native/jni") 
endif()
hunter_add_package(OpenCV)
find_package(OpenCV REQUIRED HINTS ${OpenCV_DIR})
```

**Comment by ruslo** [comment]
> BTW, did you have any thoughts on the ANDROID find_package(opencv) failure?

I remember this problem but haven't look at it yet. I've added note to the main issue:
* https://github.com/ruslo/hunter/issues/153#issuecomment-111807605

**Comment by ruslo** [comment]
> whether it is better to model the CMAKE_ARG differences for each release (which may be subject to change) or just define the full set of options explicitly somewhere

I think we can add everything to the CMAKE_ARGS for now. I mean let's have `BUILD_ANDROID_EXAMPLES=OFF` even if it not used in `iOS`. In general it's possible to have different flags for different platforms/versions. We just need to add checks like:
```
if(WIN32)
  set(_opencv_args ...) # windows specific
endif()

if(HUNTER_OpenCV_VERSION MATCHES "^3.0")
  set(_opencv_args ...) # 3.0 specific
endif()
```

**Pull request closed without merging**
