### PR TITLE
Added OpenCV-Qt example

### PR DESCRIPTION
**Pull request by pretyman**
Enables building OpenCV WITH_QT=YES to enable to Qt backend

### CODE REVIEW

**Comment by pretyman** [comment]
Ah, only now I've noticed that OpenCV has been updated.

Qt with OpenCV 3.3.1 is not working and I still need to investigate the cause, I will update this pull request by the weekend likely, when I understand what is wrong with 3.3.1 that works with 3.3.0.

Thanks

**Comment by pretyman** [comment]
Pull request updated, everything is good now

**Comment by ruslo** [comment]
OpenCV testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2837
* https://travis-ci.org/ingenue/hunter/builds/303714580?utm_source=github_status&utm_medium=notification

OpenCV-extra testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2838
* https://travis-ci.org/ingenue/hunter/builds/303714873?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
OpenCV upload:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2840
* https://travis-ci.org/ingenue/hunter/builds/303983607?utm_source=github_status&utm_medium=notification

OpenCV-extra upload:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2841
* https://travis-ci.org/ingenue/hunter/builds/303983755?utm_source=github_status&utm_medium=notification

**Comment by pretyman** [comment]
Thank you!

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.162

**Pull request merged**
