### PR TITLE
Added package MySQL-client

### PR DESCRIPTION
**Pull request by pretyman**
Hi Ruslan,

I named this package MySQL-client and not only MySQL to leave the door open to whoever wants to contribute MySQL the embedded server library in the future.

Note that in the MySQL website they call it "MySQL connector", and the library goes by the name of `libmysqlclient`.

Just let me know if you would like different names for the Hunter package and CMake Find script. 

Note that MySQL does not install a Find or Config scripts.

### CODE REVIEW

**Comment by pretyman** [comment]
There is a C++ connector as well: https://dev.mysql.com/downloads/connector/cpp/ so I guess I should somehow reflect that on the name, what do you think?

**Comment by ruslo** [comment]
Test works for me.

@pretyman Should I merge that or you want to make some updates?

**Comment by pretyman** [comment]
I think its best not to merge. I will update the CMake scripts. Would be great if anyone with experience with MySQL could help to give names for this package :-)
I'll sleep over it and update it in the morning. 
Thanks!

**Comment by ruslo** [comment]
> Would be great if anyone with experience with MySQL could help to give names for this package

@pretyman I see no standard FindMySQL module so I guess you can name it as you like :)

**Pull request closed without merging**
