### PR TITLE
Boost pba

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1474
* https://travis-ci.org/ingenue/hunter/builds/215807070

**Comment by ruslo** [comment]
Example updated, looks like we need Boost 1.58. Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1476
* https://travis-ci.org/ingenue/hunter/builds/215815056

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1479
* https://travis-ci.org/ingenue/hunter/builds/215880322

**Comment by headupinclouds** [comment]
Thanks for the fixes.

**Comment by ruslo** [comment]
Released:
* https://github.com/ruslo/hunter/releases/tag/v0.18.28

Wiki:
* https://github.com/ruslo/hunter/wiki/pkg.boost-pba

**Pull request merged**
