### PR TITLE
clang build fix

### PR DESCRIPTION
**Pull request by tatraian**
Protocol buffers backported fix can be access through hunter. The default version is also changed to this.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.365
* https://travis-ci.org/ingenue/hunter/builds/121672468

**Comment by ruslo** [comment]
> Testing

passed

**Comment by tatraian** [comment]
Cool, thanks!

**Comment by ruslo** [comment]
Cache uploaded:
* https://travis-ci.org/ingenue/hunter/builds/121676789

Released:
* https://github.com/ruslo/hunter/releases/tag/v0.14.11

**Pull request merged**
