### PR TITLE
Add ethash package

### PR DESCRIPTION
**Pull request by chfast**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/chfast/hunter/build/1.0.42
  * https://travis-ci.org/chfast/hunter/builds/377661799

* I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch,
  see this merged pull request https://github.com/ingenue/hunter/pull/247

### CODE REVIEW

**Comment by chfast** [comment]
Work in progress.

**Comment by chfast** [comment]
I disabled ios-nocodesign-11-3-dep-9-3 (https://github.com/ingenue/hunter/pull/247).
Should be ready to review.

**Comment by chfast** [comment]
Wait. Testing additional arm toolchains...

**Comment by chfast** [comment]
Done.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3885
* https://travis-ci.org/ingenue/hunter/builds/377679701?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3886
* https://travis-ci.org/ingenue/hunter/builds/377690239?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.20.73

**Pull request merged**
