### PR TITLE
Add latest GTest release.

### PR DESCRIPTION
**Pull request by Knitschi**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2696
* https://travis-ci.org/ingenue/hunter/builds/295394889?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2698
* https://travis-ci.org/ingenue/hunter/builds/295454621?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.143

**Comment by Knitschi** [comment]
Thank you for the quick release.

**Comment by xsacha** [comment]
This version requires CMake 3.7 to work.
https://github.com/hunter-packages/googletest/issues/24

**Pull request merged**
