### PR TITLE
Add ARM_NEON_2_x86_SSE

### PR DESCRIPTION
**Pull request by ruslo**
Fix for https://github.com/ruslo/hunter/issues/724

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1496
* https://travis-ci.org/ingenue/hunter/builds/217698533

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1499
* https://travis-ci.org/ingenue/hunter/builds/217732900

**Comment by ruslo** [comment]
Released https://github.com/ruslo/hunter/releases/tag/v0.18.32

**Comment by headupinclouds** [comment]
Thanks.

**Pull request merged**
