### PR TITLE
Improving regex search in finding MSVC arch and vcvarsall.bat

### PR DESCRIPTION
**Pull request by sumedhghaisas**
* Regex search in hunter_setup_msvc_arch.cmake and hunter_setup_msvc_vcvarsall.cmake improved

### CODE REVIEW

**Comment by ruslo** [comment]
Something wrong with regex (Log https://travis-ci.org/ruslo/hunter/jobs/95553382):
```
Run test
  generator: Visual Studio 8 2005
  expected arch: x86
[hunter ** INTERNAL **] Can't detect generator arch: Visual Studio 8 2005
```

Just for your information here is instruction of easy testing: https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy

**Comment by ruslo** [comment]
In general I'm okay with this change but must to note that `"^Visual Studio [0-9]+ [0-9]+ (Win64|ARM|)"` is not the same as previous code. E.g. it will pass test even if `CMAKE_GENERATOR` will be set to some wrongly value like `Visual Studio 001230 9293912 Win64`.

**Comment by ruslo** [comment]
Also here is the code from qt scheme:
```
  set(env_cmd "@HUNTER_MSVC_VCVARSALL@" "@HUNTER_MSVC_ARCH@")

  # Find the year of Visual Studio
  string(REPLACE " " ";" msvc_year "${CMAKE_GENERATOR}")
  list(GET msvc_year 3 msvc_year)

  hunter_status_debug("CMake generator: ${CMAKE_GENERATOR}")
  hunter_status_debug("Year: ${msvc_year}")

  string(COMPARE EQUAL "${msvc_year}" "" is_empty)
  if(is_empty)
    hunter_internal_error("Can't detect error of Visual Studio generator")
  endif()

  hunter_status_debug("Environment command: ${env_cmd}")
```
so this function also can set `HUNTER_MSVC_YEAR` variable.

Just an idea for further improvement.

**Comment by ruslo** [comment]
Just for your information this version fails too:
```
Run test
  generator: Visual Studio 8 2005
  expected arch: x86
CMake Error at CMakeLists.txt:19 (message):
  Syntax error in cmake code at
    /Users/travis/build/ruslo/hunter/tests/hunter_setup_msvc/CMakeLists.txt:19
  when parsing string
      expected version: ${expected version}
  syntax error, unexpected cal_SYMBOL, expecting } (39)
```

**Comment by sumedhghaisas** [comment]
Ohh thats the problem of the test changes I made. Stupid mistake. But rather than running tests on local its faster to run tests on travis. My local machine is very slow and if I run these tests on background it becomes slower. Sorry for the inconvenience.

**Comment by ruslo** [comment]
Related fixes https://github.com/ruslo/hunter/compare/e83cc0d3b6...20af3c1139

**Pull request merged**
