### PR TITLE
Add v0.40-p4 xgboost: install both *.h and *.hpp

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1065
* https://travis-ci.org/ingenue/hunter/builds/165185981

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1069
* https://travis-ci.org/ingenue/hunter/builds/165194504

**Comment by headupinclouds** [comment]
Thanks.

**Comment by ruslo** [comment]
> Uploading

Done.

Released: https://github.com/ruslo/hunter/releases/tag/v0.16.7

**Pull request merged**
