### PR TITLE
update glog to 0.3.5-p0

### PR DESCRIPTION
**Pull request by NeroBurner**
- update to new tag 0.3.5
- patch for mingw support

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1920
* https://travis-ci.org/ingenue/hunter/builds/250708241?utm_source=github_status&utm_medium=notification

**Comment by NeroBurner** [comment]
the build for apple with clang-libstdcxx is failing
```
In file included from /Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/1ba8256/40f3814/3ede738/Build/glog/Source/src/demangle.cc:38:

In file included from /Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/1ba8256/40f3814/3ede738/Build/glog/Source/src/demangle.h:74:

/Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/1ba8256/40f3814/3ede738/Build/glog/Build/glog-Release-prefix/src/glog-Release-build/glog/logging.h:1336:14: error: no member named 'forward' in namespace 'std'

 return std::forward<T>(t);
```

`std::forward` is defined with c++11. Does the toolchain support c++11?
http://www.cplusplus.com/reference/utility/forward/

the conflicting line was introduced roughly 3 months ago
https://github.com/hunter-packages/glog/blame/hunter_v0.3.5/src/glog/logging.h.in#L1336

**Comment by ruslo** [comment]
> std::forward is defined with c++11. Does the toolchain support c++11?

Yes, C++11 flag added to compiler. I think all parts of standard library are not implemented. Feel free to exclude.

**Comment by NeroBurner** [comment]
PR over here https://github.com/ingenue/hunter/pull/87

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1926
* https://travis-ci.org/ingenue/hunter/builds/251072062?utm_source=github_status&utm_medium=notification

**Comment by NeroBurner** [comment]
passed :+1:

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1930
* https://travis-ci.org/ingenue/hunter/builds/251441446?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.25

**Pull request merged**
