### PR TITLE
Update Catch to v2.7.0

### PR DESCRIPTION
**Pull request by kaihowl**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/kaihowl/hunter/builds/22946807
  * https://travis-ci.com/kaihowl/hunter/builds/103770802

### CODE REVIEW

**Comment by kaihowl** [comment]
Marked as WIP as the builds are still running

**Comment by kaihowl** [comment]
Both builds have passed. Ready to go.

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22948061
- https://travis-ci.org/ingenue/hunter/builds/503982961?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22948271
- https://travis-ci.org/ingenue/hunter/builds/503987684?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.128

**Pull request merged**
