### PR TITLE
Updated Protobuf

### PR DESCRIPTION
**Pull request by fwinnen**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2420
* https://travis-ci.org/ingenue/hunter/builds/276886736?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

Something wrong with `Protobuf-legacy` example.

I've recently updated instructions how you can test it yourself before making pull request:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#ci-testing

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2431
* https://travis-ci.org/ingenue/hunter/builds/277364926?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

Android stop working. Please test new version before sending updates, details here:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#ci-testing

**Comment by fwinnen** [comment]
Sorry, i tested with the archive uploaded to my fork and then... yeah, lets say i am too dump to generate the  archive from the right branch :D. 3.1.0-hunter-2 is pointing to 3.3.0 (which has the problem in the tests).

You will see in commits soon.

**Comment by fwinnen** [comment]
sec, wrong branch

**Comment by ruslo** [comment]
Is it ready for testing now?

**Comment by fwinnen** [comment]
yep, thx

**Comment by ruslo** [comment]
> yep, thx

Have you tested with these instructions?
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#ci-testing

**Comment by fwinnen** [comment]
i tried, didn't get it to work, but it's a long day for me, so that could be the problem, i tested all toolchains with the example locally.

**Comment by ruslo** [comment]
> i tried, didn't get it to work, but it's a long day for me, so that could be the problem, i tested all toolchains with the example locally.

I've just added testing documentation so it would be nice to have some feedback. Basically you need to register in Travis/AppVeyor and push one branch, that's all. Currently testing part is the longest one because I have to retest pull request again and again. It's a waste of time.

**Comment by fwinnen** [comment]
It's 21:00 here, but ill have a look at this tomorow morning. I'll give you feedback!

**Comment by fwinnen** [comment]
Ok I guess my tests are running:

[](https://ci.appveyor.com/project/fwinnen/hunter)
[](https://travis-ci.org/fwinnen/hunter/builds/277813837)

Is there an option to setup appveyor to respect the test.* convention?

**Comment by ruslo** [comment]
> Ok I guess my tests are running

Looks good, congrats! :tada:

> Is there an option to setup appveyor to respect the test.* convention?

What do you mean?

**Comment by fwinnen** [comment]
I had to select the branch in my config on the site, it defaults to master branch. Thought there is an option to select all test.* branches. But maybe it picks every branch up and I just didn't wait long enough ...

Von meinem iPhone gesendet

**Comment by ruslo** [comment]
> I had to select the branch in my config on the site, it defaults to master branch. Thought there is an option to select all test.* branches. But maybe it picks every branch up and I just didn't wait long enough ...

Not sure I understand. Select for what? Select where?

**Comment by fwinnen** [comment]
Never mind, I just need to read into the AppVeyor docs.

For feedback to your testing documentation:
It is kind of hard to get into it, because you explain it on an abstract level and mix in an example of a new package. I think the document would be a lot simpler if you describe the process with two examples. One for package updates and one for new packages. I imagine something like:

### Prepare:
1. Sign in to AppVeyor and Travis with your GitHub Account, and enable your hunter fork for testing. (Note: Those services are free to use with public repos)
2. $git remote add ci https://github.com/ingenue/hunter

### Package Update: GTest (assumes no test needs to be changed)
1. $git fetch ci
2. $git checkout pkg.gtest
3. $git checkout pr.gtest (your branch where you requested the pull)
4. $git checkout -b test.gtest
5. $git merge pkg.gtest
6. <Accept the test files from pkg.gtest>
7. $git push -u origin test.gtest

#### What happens:
+ 1-2 checking out branch for ci repo to get the current test configs
+ 3-4 create a tmp branch to run tests against from your pull request
+ 5-6 get the test configs from 1-2 into your tmp test branch
+ 7 push test branch to *your* hunter fork to trigger tests in AppVeyor and Travis

### New Package: MyPackage
1. ...

#### What happens:
+ ....

### Advanced
#### Disable specific tests
#### ...


So it would easy to get up and running with a single glance, and you'd still be able to dig deeper.

**Comment by ruslo** [comment]
> Prepare 
> Sign in to AppVeyor and Travis ...
> git remote add ci https://github.com/ingenue/hunter

This part is the same as `Create: CI testing`, I've already added a note:
* https://docs.hunter.sh/en/latest/creating-new/update.html#testing

> Package Update: GTest (assumes no test needs to be changed)

So it's the same as current documentation (?)

> What happens

I've added few notes to documentation:
* https://docs.hunter.sh/en/latest/creating-new/update.html#testing

**Comment by fwinnen** [comment]
:D Wow, i just looked at the site you linked earlier for new packages. Yeah now it makes sense, and is exactly what I was looking for.

**Comment by fwinnen** [comment]
One small point: First point should say that you explain update with hunter_box as an example. Due to the 'hunter' in it, it could be a bit confusing (could be something special for tests...). Otherwise its a very nice doc and should be foolproof!

**Comment by ruslo** [comment]
> Due to the 'hunter' in it, it could be a bit confusing

You mean like renaming it to `my_cool_package`? Something without `hunter`?

**Comment by isaachier** [comment]
Did @fwinnen ever update the Hunter config to add Protobuf 3.1 and 3.3? This might answer #1091 for me.

**Comment by ruslo** [comment]
@isaachier Not sure I understand the question. Current version is 3.0.0:
https://github.com/ruslo/hunter/blob/ce2637526f3ad3d1e6f1cd64e02bd002ea6d0e21/cmake/configs/default.cmake#L107

**Comment by isaachier** [comment]
Right but I don't think I am able to access any upstream version (meaning 3.1 and 3.3) even when overriding the config. I believe those releases are available on hunter-packages/protobuf, but @fwinnen did not add them to the Protobuf Hunter file for use.

**Comment by ruslo** [comment]
> I don't think I am able to access any upstream version (meaning 3.1 and 3.3) even when overriding the config

@isaachier They are in this pull request which is opened and not merged. Feel free to work on it.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/pull/1096

**Pull request closed without merging**
