### PR TITLE
update aglet to v1.1.0

### PR DESCRIPTION
**Pull request by headupinclouds**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1980
* https://travis-ci.org/ingenue/hunter/builds/255436512?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1981
* https://travis-ci.org/ingenue/hunter/builds/255551367?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.36
Wiki page: https://github.com/ruslo/hunter/wiki/pkg.aglet
All packages updated: https://docs.hunter.sh/en/latest/packages/all.html
Added to `Graphics 2D/3D` section: https://docs.hunter.sh/en/latest/packages/graphics.html

**Comment by headupinclouds** [comment]
Thanks!

**Comment by headupinclouds** [comment]
> Added to Graphics 2D/3D section

We could add ogels_gpgpu here as well, although that one sits between graphics and computer vision.

**Comment by ruslo** [comment]
Added: https://docs.hunter.sh/en/latest/packages/graphics.html

**Pull request merged**
