### PR TITLE
Add units 2.3.1 / replace default version

### PR DESCRIPTION
**Pull request by kaihowl**
This is the latest, released version and will replace the alpha 3.x as
the default version in hunter.

This is a follow up to #1602.

* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/kaihowl/hunter/builds/22781532
  * https://travis-ci.com/kaihowl/hunter/builds/102945693

### CODE REVIEW

**Comment by kaihowl** [comment]
@achary Let me know if this is also fine by you or if I overlooked something.

**Comment by ruslo** [comment]
@achary If I will merge this PR you can switch to the alpha version using custom config feature:
- https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-package-version

At this moment there are no strict rules about what version should be a default, just for your info:  https://github.com/ruslo/hunter/issues/1106

**Comment by achary** [comment]
I'm also good. Thanks.

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22782105
- https://travis-ci.org/ingenue/hunter/builds/501069966?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22782175
- https://travis-ci.org/ingenue/hunter/builds/501071532?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.125

**Pull request merged**
