### PR TITLE
Patching HUNTER_INSTALL_PREFIX in unrelocatable text files

### PR DESCRIPTION
**Pull request by pretyman**
Fix for https://github.com/ruslo/hunter/issues/472

Should I bump `PACKAGE_INTERNAL_DEPS_ID` of all autotools packages?

### CODE REVIEW

**Comment by ruslo** [comment]
Thanks, looks good. Please add some comments with link to the bug. This is kind of not obvious.

> Should I bump PACKAGE_INTERNAL_DEPS_ID of all autotools packages?

Yes, otherwise nothing will be changed and full paths will stuck on servers. You can do ++DEPS_ID for packages with PACKAGE_UNRELOCATABLE_TEXT_FILES.

Also we can think about improvement of DEPS_ID updates. For example we can add modifying of DEPS_ID variable in ``hunter_pick_scheme`` module. E.g. it's possible to check the name of the scheme and set DEPS_ID accordingly.

**Comment by pretyman** [comment]
> For example we can add modifying of DEPS_ID variable in hunter_pick_scheme module. E.g. it's possible to check the name of the scheme and set DEPS_ID accordingly.

Sorry, I did not follow, can you elaborate on this topic?

**Comment by pretyman** [comment]
Updated this pull request with comments in  `cmake/modules/hunter_save_to_cache.cmake` and `PACKAGE_INTERNAL_DEPS_ID` incremented by one

**Comment by ruslo** [comment]
> Sorry, I did not follow, can you elaborate on this topic?

If you don't want to make an update of `PACKAGE_INTERNAL_DEPS_ID` of every package (i.e. every `hunter.cmake`) there some optimization possible. For now `hunter_pick_scheme` set variables:
* HUNTER_DOWNLOAD_SCHEME - name of the used scheme
* HUNTER_PACKAGE_SCHEME_{DOWNLOAD,UNPACK,INSTALL} - booleans describing type of the scheme

You can add one more variable:
* HUNTER_PACKAGE_SCHEME_INTERNAL_DEPS_ID

in this case there is no need to update `PACKAGE_INTERNAL_DEPS_ID` of every `hunter.cmake` - you can update DEPS_ID only once in `hunter_pick_scheme`:

```cmake
string(
      COMPARE
      EQUAL
      "${HUNTER_DOWNLOAD_SCHEME}"
      "url_sha1_autotools"
      is_autotools
)
if(is_autotools)
  set(HUNTER_PACKAGE_SCHEME_INTERNAL_DEPS_ID "2") # 1 -> 2
endif()
```

**Comment by ruslo** [comment]
Test `drm`: https://travis-ci.org/ingenue/hunter/builds/147964336

**Comment by ruslo** [comment]
Test `xrandr`: https://travis-ci.org/ingenue/hunter/builds/147964900

**Comment by ruslo** [comment]
Do you want any packages to be uploaded or there will be more patches?

**Comment by pretyman** [comment]
> You can add one more variable:

Oh ok, I get you now, yeah, next time there is a big update to packages, I'll take that into account.

> Do you want any packages to be uploaded or there will be more patches?

No more patches are planned, so yes, they can be uploaded if you think is best :-)

Thanks!

**Comment by ruslo** [comment]
Uploading `drm`: https://travis-ci.org/ingenue/hunter/builds/148024684
Uploading `xrandr`: https://travis-ci.org/ingenue/hunter/builds/148024874

**Pull request merged**
