### PR TITLE
glog: update to version 0.3.4-p2

### PR DESCRIPTION
**Pull request by NeroBurner**
- imported target glog::glog by glog-config.cmake (target renamed from glog)

need to update Wiki entry

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1315
* https://travis-ci.org/ingenue/hunter/builds/191927600

**Comment by ruslo** [comment]
> /home/travis/build/ingenue/hunter/examples/glog/foo.cpp:1:26: fatal error: glog/logging.h: No such file or directory

Looks like something wrong with include headers.

> /usr/bin/g++     -O3 -DNDEBUG   -o CMakeFiles/foo.dir/foo.cpp.o -c /home/travis/build/ingenue/hunter/examples/glog/foo.cpp

I see no `-I/path/to/install`, seems that `INCLUDE DESTINATION` missing in `install` directive.

**Comment by NeroBurner** [comment]
I forgot to update the example cmake file. Needed to link against `glog::glog`

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1325
* https://travis-ci.org/ingenue/hunter/builds/192361478

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1326
* https://travis-ci.org/ingenue/hunter/builds/192382225

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.17.16

**Comment by NeroBurner** [comment]
updated wiki with new `glog::glog` target

**Pull request merged**
