### PR TITLE
Patch add pugixml

### PR DESCRIPTION
**Pull request by rusdevops**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2033
* https://travis-ci.org/ingenue/hunter/builds/257435266?utm_source=github_status&utm_medium=notification

**Comment by rusdevops** [comment]
```
ci: Travis
build: 1984
job: 5
warnings:
- 
  log:    https://travis-ci.org/ingenue/hunter/jobs/257435271#L1368
  source: https://github.com/rusdevops/pugixml/blob/v1.8.1-hunter/src/pugixml.cpp#L673
  check:  https://github.com/rusdevops/pugixml/blob/v1.8.1-hunter/src/pugixml.cpp#L670

- 
  log:    https://travis-ci.org/ingenue/hunter/jobs/257435271#L1371
  source: https://github.com/rusdevops/pugixml/blob/v1.8.1-hunter/src/pugixml.cpp#L2223
  check:  https://github.com/rusdevops/pugixml/blob/v1.8.1-hunter/src/pugixml.cpp#L2220
```

**Comment by rusdevops** [comment]
```
build: 1984
job: 14
warnings:
- 
  log:    https://travis-ci.org/ingenue/hunter/jobs/257435271#L1368
  source: https://github.com/rusdevops/pugixml/blob/v1.8.1-hunter/src/pugixml.cpp#L673
  check:  https://github.com/rusdevops/pugixml/blob/v1.8.1-hunter/src/pugixml.cpp#L670
-
  log:    https://travis-ci.org/ingenue/hunter/jobs/257435280#L1019
  source: https://github.com/rusdevops/pugixml/blob/v1.8.1-hunter/src/pugixml.cpp#L9503
  check:  https://github.com/rusdevops/pugixml/blob/v1.8.1-hunter/src/pugixml.cpp#L9486
```

**Comment by ruslo** [comment]
> Testing

`analyze` failed. You can submit new version with fix or exclude `analyze` from testing. To exclude toolchain submit patch to `pkg.pugixml`:
* https://github.com/ingenue/hunter/tree/pkg.pugixml

Pull request shoud contains only `.travis.yml` change, example:
* https://github.com/ingenue/hunter/pull/56/files

**Comment by rusdevops** [comment]
@ruslo, thanks for recommending.
https://github.com/ingenue/hunter/pull/98

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2040
* https://travis-ci.org/ingenue/hunter/builds/257476199?utm_source=github_status&utm_medium=notification

**Comment by rusdevops** [comment]
@ruslo, if you can, please stop build 1990 on travis.
https://travis-ci.org/ingenue/hunter/builds/257475187

**Comment by rusdevops** [comment]
@ruslo, I am sorry, but I forgot to discard the build for `macOS`.
https://github.com/ingenue/hunter/pull/99

**Comment by rusdevops** [comment]
@ruslo, I reopen final pull request with all changes. 
https://github.com/ingenue/hunter/pull/100

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2046
* https://travis-ci.org/ingenue/hunter/builds/257588301?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2047
* https://travis-ci.org/ingenue/hunter/builds/257592454?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.45

**Pull request merged**
