### PR TITLE
ZeroMQ now can be used as CMake package

### PR DESCRIPTION
**Pull request by tatraian**
I updated the hunter scripts and patched libzmq, so now I hope we can use it with find_package CMake command.

### CODE REVIEW

**Comment by ruslo** [comment]
Thanks, I've enables all CI matrix back to see if it fix some failures. Testing now:
* https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=pkg.zeromq.pr-337

**Comment by tatraian** [comment]
It's not looking good. As I see linux builds failed because statically linked version doesn't find librt. That was not problem on my ubuntu box... I will fix this tomorrow.

Looks like ZeroMQ cannot be compiled on android. I think it is independent from me and it is better to extract mobile platforms from CI matrix...

On Windows I don't know what is the problem currently, and I don't have Windows environment. But this must be built on Windows. I hope in the next week I have VS2015 and then I try to figure out what is the problem.

**Comment by ruslo** [comment]
> As I see linux builds failed because statically linked version doesn't find librt

Not "find" but "link". I think if you add `rt` as a usage requirement then it will work, i.e.
```cmake
if(UNIX AND NOT APPLE)
    target_link_libraries(libzmq PUBLIC rt)
endif()

**Comment by tatraian** [comment]
The library itself was correctly linked, so there is no problem with libzmq. But I added two example applications. The first is dynamically linked to libzmq and the second is statically linked to libzmq-static. The compile error happened at the second. Now I add a huge amount of code to the example CMakeLists.txt to find and link the same libraries to the static version that are linked to libzmq.so as well. But if you prefer I can eliminate the static version.

**Comment by ruslo** [comment]
> The library itself was correctly linked, so there is no problem with libzmq

The logic is next: if `main.cpp` of example is not using any function from `rt` library then the reason of link errors is that `libzmq` use something from `rt` => must provide `rt` as a usage requirement => `CMakeLists.txt` of `libzmq` should be patched.

I guess static version of `libzmq` installed fine because it's okay to have unresolved symbols for library, the real error occurs when you try to link everything into final executable.

Dynamic version of `libzmq` works fine because dynamic libraries contain info about dependency (run `ldd libzmq.so`), so it can be loaded automatically.

**Comment by tatraian** [comment]
Ok. Then I don't understand (know) the next: When you create a static library (libzmq-static) then it is just an archive of compiled objects. In this case does the archive itself contain any information about libraries that required for final linking (As I know it doesn't)? And If the static archive does not give you this dependency, then can CMake provide it (for ZeroMQ::libzmq-static target)? I proposed not. So in the example I searched all libraries that were linked to libzmq.so and I linked them to statically linked example binary.

**Comment by tatraian** [comment]
Sorry. I think I understood... In case of static libraries the `target_link_libraries` command does not make real linking but the target will know its dependencies. In the deep that means that the CMake will generate `set_target_properties(IMPORTED_LINK_INTERFACE_LIBRARIES_* ...)` property for the target in the ProjectTarget-*.cmake files.

Please restart the test on this version. On Windows it will fail, but I hope I fixed the compile error on linux.

**Comment by ruslo** [comment]
>Please restart the test on this version

Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.151
* https://travis-ci.org/ingenue/hunter/builds/113713499

**Comment by ruslo** [comment]
> Testing

Much better! Now only android, ios and analyze fail.

**Pull request merged**
