### PR TITLE
Update 'ros_environment' to 1.2.1-p0

### PR DESCRIPTION
**Pull request by kgeorgiev93**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html) step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/kgeorgiev93/hunter/builds/25007853
  * https://travis-ci.com/kgeorgiev93/hunter/builds/114133018

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/25008980
- https://travis-ci.org/ingenue/hunter/builds/540850466?utm_source=github_status&utm_medium=notification

**Comment by kgeorgiev93** [comment]
We need a release of hunter in order to progress with https://github.com/ruslo/hunter/issues/1397.

**Comment by ruslo** [comment]
Released:
- https://github.com/ruslo/hunter/releases/tag/v0.23.186

just for your info you can pick a random commit like this:

```cmake
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/76c3fd69bbe742859a006bd28415eeb76093b091.zip"
    SHA1 "9c8c28c56036bea0d3df78268867dfd128a1a076"
)
```

**Comment by kgeorgiev93** [comment]
> Released:
> 
> * https://github.com/ruslo/hunter/releases/tag/v0.23.186
> 
> just for your info you can pick a random commit like this:
> 
> ```cmake
> HunterGate(
>     URL "https://github.com/ruslo/hunter/archive/76c3fd69bbe742859a006bd28415eeb76093b091.zip"
>     SHA1 "9c8c28c56036bea0d3df78268867dfd128a1a076"
> )
> ```

Ok, thanks!

**Pull request merged**
