### PR TITLE
add SDL_image package

### PR DESCRIPTION
**Pull request by wheybags**
Some windows toolchains will fail, as they fail to build SDL2. They are already disabled in CI for SDL2

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2262
* https://travis-ci.org/ingenue/hunter/builds/269128891?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
All OSX toolchains failed.

**Comment by wheybags** [comment]
I think this change should fix that?

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2265
* https://travis-ci.org/ingenue/hunter/builds/269589687?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2270
* https://travis-ci.org/ingenue/hunter/builds/269613094?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.86

**Pull request merged**
