### PR TITLE
Add 'hunter_box_1' package

### PR DESCRIPTION
**Pull request by hunterbox**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2413
* https://travis-ci.org/ingenue/hunter/builds/276810989

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2416
* https://travis-ci.org/ingenue/hunter/builds/276824988

**Comment by ruslo** [comment]
Released https://github.com/ruslo/hunter/releases/tag/v0.19.103

**Comment by dvirtz** [comment]
What is this package?

**Comment by ruslo** [comment]
@dvirtz I'm working on new "Create new package" section in documentation. It's a dummy user with dummy package.

**Comment by dvirtz** [comment]
That'll be a great addition.
Thanks

**Pull request merged**
