### PR TITLE
Check for presence of msys when configuring boost and redirect to boo…

### PR DESCRIPTION
**Pull request by cdglove**
…ststrap.sh in that case.

Under MSYS, trying to use boost from hunter results in an error message that;

/bin/sh bootstrap.bat is inavlid.

Checking for the presence of MSYS and redirecting to bootstrap.sh, as under cygwin and linux, resolves the issue.

### CODE REVIEW

**Comment by cdglove** [comment]
Nevermind, appears to be fixed at head on master.

**Comment by jgillich** [comment]
Is it? I'm getting:

```
/bin/sh: bootstrap.bat: command not found
```

Full log: https://ci.appveyor.com/project/JakobGillich/autominer/build/66

Using hunter v0.19.213 and cmake -G "MSYS Makefiles". Do I need to update hunter? The version is only 10 days old so I assume not.

@ruslo

**Comment by ruslo** [comment]
I don't know. I'm not using MSYS daily and MSYS + Boost is not regularly tested:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3146
* https://github.com/ingenue/hunter/blob/pkg.boost/appveyor.yml#L46-L48

**Comment by jgillich** [comment]
Alright thanks, I think it should just switch to plain mingw. God I hate Windows. :(

**Pull request closed without merging**
