### PR TITLE
Update libjson-rpc-cpp 0.7.0-p0 to 0.7.0-p3

### PR DESCRIPTION
**Pull request by smurfy**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2236
* https://travis-ci.org/ingenue/hunter/builds/268400126?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
I guess `find_package(Threads REQUIRED)` is missing somewhere:
```
  Target "client" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by smurfy** [comment]
Hm strange, i did not change anything regarding this in version 0.7.0-p2
Also the code changes there are not in the default build. 
The default build only builds the client part. There is a special cmake arg to compile the different server parts.

I also tested compilation with THIS PR as manual huntergate url. And it did compile just fine on windows. I can test later on linux too, but this should not be the problem, as my changes are not part of the build.

**Comment by ruslo** [comment]
> Hm strange, i did not change anything regarding this in version 0.7.0-p2

It seems so. I guess dependency changed, I'm running tests with old 0.7.0-p0 version:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2237
* https://travis-ci.org/ingenue/hunter/builds/268409024?utm_source=github_status&utm_medium=notification

> There is a special cmake arg to compile the different server parts

This can be controlled with `hunter_cmake_args` in `hunter.cmake`. Feel free to add.

> And it did compile just fine on windows

Doesn't work for me. Try to bebase your change against latest `master`.

**Comment by smurfy** [comment]
Hm i rebased and it works in the project i'm using it just fine.
I'm to much of a noob to figure out whats actually wrong and how to fix it 😢 
@chfast Maybe you can chip in. 
Thanks

**Comment by ruslo** [comment]
> I'm running tests with old 0.7.0-p0 version

All failed with the same reason. Meaning something changed in dependencies.

>  it works in the project i'm using it just fine

You should try isolated example from Hunter, probably `Threads::Threads` issue masked by some code (e.g. if you use `find_package(Threads)` explicitly).

**Comment by ruslo** [comment]
I've found the reason. They have added local copy of `FindThreads` module which doesn't introduce imported target `Threads::Threads`. I guess OpenSSL was not using `Threads::Threads` before (which is no correct and was fixed).

Simply removing local `FindThreads` do the trick:
* https://github.com/hunter-packages/libjson-rpc-cpp/commit/f0948f1a58b3299339e255b5097d02c8622129b5

@smurfy Please update pull request with this release:
* https://github.com/hunter-packages/libjson-rpc-cpp/releases/tag/v0.7.0-p3

**Comment by smurfy** [comment]
Updated PR

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2266
* https://travis-ci.org/ingenue/hunter/builds/269591120?utm_source=github_status&utm_medium=notification

**Comment by smurfy** [comment]
Yay!. thank you very much!

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2271
* https://travis-ci.org/ingenue/hunter/builds/269625352?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.86

**Pull request merged**
