### PR TITLE
Update SDL2 package to remove separate SDL2-static target

### PR DESCRIPTION
**Pull request by wheybags**
see https://github.com/hunter-packages/SDL2/commit/8926da202eb67c85fd4acc8ecd6438469df20e16

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2001
* https://travis-ci.org/ingenue/hunter/builds/256646633?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Something wrong with CMake code:
```
CMake Error at /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/bfe716a/7c86f54/266cf4a/Build/SDL2/Build/SDL2-Release-prefix/src/SDL2-Release-stamp/SDL2-Release-install-.cmake:16 (message):
  Command failed: 1

   '/home/travis/build/ingenue/hunter/_ci/cmake/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/bfe716a/7c86f54/266cf4a/Build/SDL2/Build/SDL2-Release-prefix/src/SDL2-Release-stamp/SDL2-Release-install--impl.cmake'

  See also

    /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/bfe716a/7c86f54/266cf4a/Build/SDL2/Build/SDL2-Release-prefix/src/SDL2-Release-stamp/SDL2-Release-install-*.log


make[2]: *** [SDL2-Release-prefix/src/SDL2-Release-stamp/SDL2-Release-install] Error 1
make[1]: *** [CMakeFiles/SDL2-Release.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by wheybags** [comment]
should be working now

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2003
* https://travis-ci.org/ingenue/hunter/builds/256690855?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
All toolchains except `vs-14-2015` failed on Windows.

**Comment by wheybags** [comment]
Guess which toolchain I tested with locally? :P
will fix

**Comment by wheybags** [comment]
Ok, should work now

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2008
* https://travis-ci.org/ingenue/hunter/builds/256860415?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2014
* https://travis-ci.org/ingenue/hunter/builds/256914867?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.39

**Pull request merged**
