### PR TITLE
Bump PocoCpp to 1.7.9

### PR DESCRIPTION
**Pull request by shekharhimanshu**
Updated hunter-packages: https://github.com/hunter-packages/poco/releases/tag/v1.7.9-p0
Add PocoCpp 1.7.9 and bumped default.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2551
* https://travis-ci.org/ingenue/hunter/builds/288988041?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2552
* https://travis-ci.org/ingenue/hunter/builds/289032662?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.124

**Comment by shekharhimanshu** [comment]
Thank you!

**Pull request merged**
