### PR TITLE
Cctz

### PR DESCRIPTION
**Pull request by isaachier**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/isaachier/hunter/build/1.0.372
  * https://travis-ci.org/isaachier/hunter/builds/350807996

* I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch,
  see this merged pull request https://github.com/ingenue/hunter/pull/201

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3394
* https://travis-ci.org/ingenue/hunter/builds/351675679?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3397
* https://travis-ci.org/ingenue/hunter/builds/351683007?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Thanks, released: https://github.com/ruslo/hunter/releases/tag/v0.20.15

**Comment by isaachier** [comment]
Thank you!

**Pull request merged**
