### PR TITLE
Add OpenCV 3.4.2 and update config

### PR DESCRIPTION
**Pull request by xsacha**
Can't find the Visual Studio issue

### CODE REVIEW

**Comment by ruslo** [comment]
> https://ci.appveyor.com/project//hunter/build/
> https://travis-ci.org//hunter/builds/

? No real link here...

Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.4167
* https://travis-ci.org/ingenue/hunter/builds/400524814?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
I don't understand the Visual Studio error. Any ideas?

Android one is easily fixed.

**Comment by ruslo** [comment]
> Any ideas?

Hard to say from only logs, something wrong with generated `*Config.cmake`?

**Comment by xsacha** [comment]
I'm giving up on this one sorry.

**Pull request closed without merging**
