### PR TITLE
-Werror has been removed from msgpack-c

### PR DESCRIPTION
**Pull request by tatraian**
toolchain  `sanitize-thread` should work.

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1091
* https://travis-ci.org/ingenue/hunter/builds/169190784

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1094
* https://travis-ci.org/ingenue/hunter/builds/169208804

**Comment by tatraian** [comment]
I think you can enable `sanitize-thread` toolchain target now.

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.16.12

**Comment by ruslo** [comment]
> I think you can enable sanitize-thread toolchain target now

Yes, please send pull request to [pkg.msgpack](https://github.com/ingenue/hunter/tree/pkg.msgpack) branch.

**Pull request merged**
