### PR TITLE
Add corrade v2019.01

### PR DESCRIPTION
**Pull request by pthom**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/pthom/hunter/builds/22131988
  * https://travis-ci.org/pthom/hunter/builds/488952434?utm_source=github_status&utm_medium=notification

If all goes well, a PR for magnum should follow.

### CODE REVIEW

**Comment by mosra** [comment]
@pthom thank you!

Random idea: to have *both* the backwards compatibility *and* the new versioning scheme, would it be possible to do this?

```cmake
hunter_add_version(
    PACKAGE_NAME
    corrade
    VERSION
    2018.10
    URL
    "https://github.com/mosra/corrade/archive/v2018.10.tar.gz"
    SHA1
    240c68bfe89a0cc86411b6854358b1607c06d90d
)

# For backwards compatibility, to be removed later
hunter_add_version(
    PACKAGE_NAME
    corrade
    VERSION
    v2018.10
    URL
    "https://github.com/mosra/corrade/archive/v2018.10.tar.gz"
    SHA1
    240c68bfe89a0cc86411b6854358b1607c06d90d
)
```

I.e., exposing both `v2018.10` and `2018.10`. Not sure if such stuff is valid according to Hunter packaging guidelines, though ;)

**Comment by pthom** [comment]
I just added 2018.10 as a synonym for v2018.10

**Comment by mosra** [comment]
Thanks! :+1: 

This is now just waiting for @ruslo to approve and merge, right? :)

**Comment by pthom** [comment]
CI Tests after adding synonym:
https://ci.appveyor.com/project/pthom/hunter/builds/22189071
https://travis-ci.org/pthom/hunter/builds/489926483

**Comment by ruslo** [comment]
Testing:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22248818
- https://travis-ci.org/ingenue/hunter/builds/491038012?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
- https://ci.appveyor.com/project/ingenue/hunter/builds/22249098
- https://travis-ci.org/ingenue/hunter/builds/491045201?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.100

**Pull request merged**
