### PR TITLE
Add new dlib versions

### PR DESCRIPTION
**Pull request by xsacha**
18.17 and 19.0 options added to dlib project
~~19.0 set to default~~
18.17 set to default so it builds on Apple clang and VS2012

### CODE REVIEW

**Comment by ruslo** [comment]
Please set branch to `develop`, see wiki: https://github.com/ruslo/hunter/wiki/dev.contribution

**Comment by xsacha** [comment]
Sorry, updated.

**Comment by ruslo** [comment]
> Sorry, updated

Hm... you've changed target branch without closing pull request. Looks like it's a new GitHub feature. I think it was not possible before, I guess I can even do it myself now. Cool.

Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.803
* https://travis-ci.org/ingenue/hunter/builds/152814682

**Comment by xsacha** [comment]
As dlib 19.0 includes initialiser_list that does not work on Apple clang and VS2012, I've reverted the default dlib to 18.17 so it can pass those tests.
This seems like the most sensible option.

**Comment by ruslo** [comment]
Thanks, testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.804
* https://travis-ci.org/ingenue/hunter/builds/152891127

**Comment by ruslo** [comment]
> testing

Looks better now. Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.805
* https://travis-ci.org/ingenue/hunter/builds/152894594

**Comment by ruslo** [comment]
> Uploading

Done, will wait for https://github.com/ruslo/hunter/pull/492 testing and make a release

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.15.17

**Pull request merged**
