### PR TITLE
Boost 1.66.0

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3099
* https://travis-ci.org/ingenue/hunter/builds/318140393?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
@Ubiquite the Visual Studio 2017 problem I had before:
```
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/tools\msvc.jam:1266: in default-path
*** argument error
* rule path.exists ( location )
* called with: (  )
* missing argument location
(builtin):see definition of rule 'path.exists' being called
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/tools\msvc.jam:735: in auto-detect-toolset-versions
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/tools\msvc.jam:1710: in load
C:\...\hunter\_testing\Hunter\_Base\81ef1a7\3be1296\83deb53\Build\Boost\Source\tools\build\src/kernel\modules.jam:295: in import
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/build\toolset.jam:41: in toolset.using
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src/build\project.jam:1052: in using
project-config.jam:3: in modules.load
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src\build-system.jam:249: in load-config
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src\build-system.jam:412: in load-configuration-files
C:/.../hunter/_testing/Hunter/_Base/81ef1a7/3be1296/83deb53/Build/Boost/Source/tools/build/src\build-system.jam:524: in load
C:\...\hunter\_testing\Hunter\_Base\81ef1a7\3be1296\83deb53\Build\Boost\Source\tools\build\src/kernel\modules.jam:295: in import
C:\...\hunter\_testing\Hunter\_Base\81ef1a7\3be1296\83deb53\Build\Boost\Source\tools\build\src/kernel/bootstrap.jam:139: in boost-build
C:\...\hunter\_testing\Hunter\_Base\81ef1a7\3be1296\83deb53\Build\Boost\Source\boost-build.jam:17: in module scope
```

Seems to be fixed in 1.66.0 release but another problem introduced (from my local machine):
```
error: Name clash for '<pstage\lib>libboost_system-mt-gd.lib'
error: 
error: Tried to build the target twice, with property sets having 
error: these incompatible properties:
error: 
error:     -  <address-model>32
error:     -  <address-model>64
error: 
error: Please make sure to have consistent requirements for these 
error: properties everywhere in your project, especially for install
error: targets.
```

Meaning we still stuck with Boost 1.64 with Visual Studio at this moment. Feel free to send the patch if you know the fix.

**Comment by xsacha** [comment]
@ruslo Those issues you have are only affecting VS2017? I see VS2015 is working in AppVeyor.

**Comment by ruslo** [comment]
> I see VS2015 is working in AppVeyor.

I haven't touched default version, it's Boost 1.64 for Visual Studio:
* https://github.com/ruslo/hunter/blob/41ac50bef470f05b6e7f82432a4bf7536a488616/cmake/configs/default.cmake#L44-L49

> Working fine for me in VS2017

@xsacha Are you sure you're building Boost 1.66.0? Also it's possible that unfortunately b2 build may produce error depending on environment (I think the problem with 1.65 was about Python).

**Comment by xsacha** [comment]
@ruslo Definitely sure it's Boost 1.66.
I checked out pr.boost and then changed the default config to use Boost 1.66 for every OS.

Pastebin of build here: https://pastebin.com/wsEqWWXL

**Comment by ruslo** [comment]
> Pastebin of build here

> -G"Visual Studio 15 2017 Win64"

@xsacha Adding `Win64` works for me too. Try `-G"Visual Studio 15 2017"` without `Win64`.

**Comment by xsacha** [comment]
Oh right. I only ever build for 64-bit.
I guess something broke with address-model.

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3111
* https://travis-ci.org/ingenue/hunter/builds/319151118?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.207

**Pull request merged**
