### PR TITLE
Add libxml2 v2.9.4.

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by xsacha** [comment]
This doesn't support Windows yet. You are meant to run cscript win32/configure.js on Windows but not sure of the best way to do it.

**Comment by ruslo** [comment]
Testing:
* https://travis-ci.org/ingenue/hunter/builds/201561653

**Comment by xsacha** [comment]
Looks like $LIBXML2_INCLUDE_DIRS fails on OSX/iOS
On Android it is missing glob.h

**Comment by ruslo** [comment]
Please exclude broken tests or apply fixes. Branch:
* https://github.com/ingenue/hunter/tree/pkg.libxml2

**Comment by xsacha** [comment]
Ok, I did both. excluded two tests and applied fix for rest.

**Comment by ruslo** [comment]
Testing:
* https://travis-ci.org/ingenue/hunter/builds/202466789

**Comment by ruslo** [comment]
> excluded two tests

iOS test still doesn't work

**Comment by ruslo** [comment]
https://github.com/ingenue/hunter/pull/50 applied, testing:
* https://travis-ci.org/ingenue/hunter/builds/204036957

**Comment by ruslo** [comment]
Uploading:
* https://travis-ci.org/ingenue/hunter/builds/204070065

**Comment by ruslo** [comment]
Released:
* https://github.com/ruslo/hunter/releases/tag/v0.18.2

Feel free to add new wiki/docs page.

**Pull request merged**
