### PR TITLE
Thrift

### LINKED ISSUE #391: Add `Apache Thrift` package
GitHub repo:
- https://github.com/apache/thrift

Note: CMake based
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33051778-add-apache-thrift-package?utm_campaign=plugin&utm_content=tracker%2F1032790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1032790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by isaachier**
Please fork Apache Thrift for hunter-packages. Resolves #391.

Build works:

https://travis-ci.org/isaachier/hunter/builds/280851478
https://ci.appveyor.com/project/isaachier/hunter/build/1.0.41

### CODE REVIEW

**Comment by ruslo** [comment]
> Please fork Apache Thrift for hunter-packages.

Done: https://github.com/hunter-packages/thrift

Also I think it make sense to do it before opening pull request. You can contact me by email or public/private Gitter:
* https://docs.hunter.sh/en/latest/contacts.html

**Comment by isaachier** [comment]
Thanks. Will do for next package. Updating docs/links now.

**Comment by isaachier** [comment]
You can test this when you want. My build seems to be going fine: https://travis-ci.org/isaachier/hunter/builds/280927035.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2487
* https://travis-ci.org/ingenue/hunter/builds/280938595?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2488
* https://travis-ci.org/ingenue/hunter/builds/280969504?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Upload tests failed because all dependencies should be cacheable too but `bison` package is not:
```
-- [hunter *** DEBUG *** 2017-09-28T17:36:02] Cache file not found: /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/a71099b/266cf4a/8913be5/Build/bison/cache.sha1
-- [hunter *** DEBUG *** 2017-09-28T17:36:02] Cache miss (entry for package: bison/)
```

**Comment by isaachier** [comment]
I see. That is a pain. I wonder how I can fix bison to be cachable. How do other libraries deal with resource files without hard-coding the path in code? Using a config file?

**Comment by ruslo** [comment]
> How do other libraries deal with resource files without hard-coding the path in code?

First of all it's responsibility of the package itself and should be fixed in package sources/install instructions. As for Hunter there is workaround module that can patch text files, you can use `PACKAGE_UNRELOCATABLE_TEXT_FILES` option, see `x11` example:
* https://github.com/ruslo/hunter/blob/7ad3c9ee774e8e929dc3e78b8e1e8d23f5de639a/cmake/projects/x11/hunter.cmake#L42-L50

Those files will be saved to cache with special text string Hunter can recognize. This will make archive movable. Then on install step this string will be replaced back with real path.

**Comment by isaachier** [comment]
So that is fine if the files are not themselves compiled. The problem with bison is the use of macros to embed the path in C code. I think it can be overridden using an environment variable, but the default path is compiled into the binary.

**Comment by isaachier** [comment]
Found a handy link that answers the question: https://lists.gnu.org/archive/html/help-bison/2015-03/msg00000.html.

**Pull request merged**
