### PR TITLE
Add Boost 1.59.0 and 1.60.0 and set 1.60.0 as the default version

### PR DESCRIPTION
**Pull request by novocodev**

### CODE REVIEW

**Comment by ruslo** [comment]
Thanks.

Sorry for delays, I'm trying to upgrade testing (apply CMake 3.5 + new script) but hit some bugs like:
* https://github.com/travis-ci/travis-ci/issues/3563#issuecomment-195285755
* https://public.kitware.com/Bug/view.php?id=16013

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.202
* https://travis-ci.org/ingenue/hunter/builds/115620388

**Comment by ruslo** [comment]
New testing with [fix](https://github.com/ruslo/hunter/commit/5bf6c56b6149902c3efe8ba5139cb9207f1d26d3):
* https://travis-ci.org/ingenue/hunter/builds/115628596
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.213

**Comment by ruslo** [comment]
> New testing with fix

One build failed on Travis:
* https://travis-ci.org/ingenue/hunter/jobs/115628636

Was working fine before:
* https://travis-ci.org/ingenue/hunter/jobs/115628541

@novocodev Can you investigate what is the reason of failure? Probably it's Boost regression bug.

**Comment by novocodev** [comment]
The errors all appear to be:

```
./boost/filesystem/operations.hpp:286:22: error: no member named 'move' in namespace 'std'

      m_value = std::move(rhs.m_value);

                ~~~~~^
```

[This SO question](http://stackoverflow.com/questions/22149118/building-llvm-examples) about the error has the following suggestion:

```
LLVM (and clang) recently switched to C++ 11. So, you need to have reasonable compiler (e.g. clang or gcc 4.7+) and compile everything with -std=c++11 flag.
```

But it looks like this is the case, below is the the first build command where the error is generated:

```
"/usr/bin/clang++" "-std=c++11" "-stdlib=libstdc++"  -ftemplate-depth-128 -O0 -fno-inline -Wall -g -gdwarf-2 -fexceptions -arch x86_64  -DBOOST_ALL_NO_LIB=1 -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_SYSTEM_STATIC_LINK=1  -I"." -c -o "bin.v2/libs/filesystem/build/darwin-4.2.1/debug/link-static/threading-multi/operations.o" "libs/filesystem/src/operations.cpp"
```

And this is the identical command from the previous working build:
```
"/usr/bin/clang++" "-std=c++11" "-stdlib=libstdc++"  -ftemplate-depth-128 -O0 -fno-inline -Wall -g -gdwarf-2 -fexceptions -arch x86_64  -DBOOST_ALL_NO_LIB=1 -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_SYSTEM_STATIC_LINK=1  -I"." -c -o "bin.v2/libs/filesystem/build/darwin-4.2.1/debug/link-static/threading-multi/operations.o" "libs/filesystem/src/operations.cpp"
```

There a number of other tickets / issues that suggest it is related to e.g. [RVALUE References support](https://svn.boost.org/trac/boost/ticket/11815). 

This is beyond my current knowledge level, so I'm not sure how that would be resolved.

**Comment by ruslo** [comment]
> This is beyond my current knowledge level, so I'm not sure how that would be resolved

@novocodev You can open issue in boost bugtracker with logs and descriptions. Probably somebody can suggest fix which can be applied to hunterized fork.

**Comment by ruslo** [comment]
Here is a code which produce error:
```cpp
#if !defined(BOOST_NO_CXX11_RVALUE_REFERENCES)
  directory_entry(directory_entry&& rhs) BOOST_NOEXCEPT
  {
    m_path = std::move(rhs.m_path);
    m_status = std::move(rhs.m_status);
    m_symlink_status = std::move(rhs.m_symlink_status);
  }
  directory_entry& operator=(directory_entry&& rhs) BOOST_NOEXCEPT
  { 
    m_path = std::move(rhs.m_path);
    m_status = std::move(rhs.m_status);
    m_symlink_status = std::move(rhs.m_symlink_status);
    return *this;
  }
#endif
```

`std::move` protected with `BOOST_NO_CXX11_RVALUE_REFERENCES`

**Comment by novocodev** [comment]
Looking at the failing build log again, the build server reports g++ --version as:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

On my  local dev Mac which builds Boost 1.60.0 without error it reports:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

Is it possible this issue is related to LLVM version?

One caveat , with the 7.0.2  version of LLVM I have experienced [issues](https://github.com/ruslo/polly/issues/70) with using Boost in a project using the iOS toolchain

**Comment by ruslo** [comment]
> Is it possible this issue is related to LLVM version?

Not LLVM I guess but in standard library since `libcxx` works and `libstdcxx` not. I'm okay with removing this test (send PR to https://github.com/ingenue/hunter to branch `pkg.boost`) because it's not a Hunter error but it would be nice to figure out what is the problem. It can be so it's a bug in c++11's feature detection in Boost.

**Comment by ruslo** [comment]
Want to test `std::move` on Travis OSX server but wait for job to start for several hours already:
* https://travis-ci.org/travis-ci-tester/travis-test-clang-mac-cxx-11/builds/14943709

**Comment by ruslo** [comment]
MinGW is broken too:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.216/job/twgm1vpxgn6w6dds

**Comment by ruslo** [comment]
OSX + clang-libstdcxx has poor c++11 support, no `std::move`:
* https://github.com/travis-ci-tester/travis-test-clang-mac-cxx-11
* https://travis-ci.org/travis-ci-tester/travis-test-clang-mac-cxx-11/builds/116380109

Removed: https://github.com/ingenue/hunter/commit/8a21e12ad0e9d29ab1863babad8de10649925b1e

**Comment by ruslo** [comment]
> MinGW is broken too

Works fine on my local machine

**Comment by ruslo** [comment]
> Works fine on my local machine

Have tried some variants but with no luck. Will merge this and add a condition:
```
if(MINGW)
  hunter_config(Boost VERSION 1.58)
else()
  hunter_config(Boost VERSION 1.60)
endif()
```

@novocodev Thanks!

**Pull request merged**
