### PR TITLE
Add cryptopp package

### PR DESCRIPTION
**Pull request by chfast**
Continuation of https://github.com/ruslo/hunter/pull/576.
Resolves https://github.com/ruslo/hunter/issues/575.

### CODE REVIEW

**Comment by chfast** [comment]
Can you test it @ruslo ?

**Comment by chfast** [comment]
Added.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2385
* https://travis-ci.org/ingenue/hunter/builds/275438526?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2386
* https://travis-ci.org/ingenue/hunter/builds/275472360?utm_source=github_status&utm_medium=notification

**Comment by chfast** [comment]
How to disable failing toolchains?

**Comment by ruslo** [comment]
> How to disable failing toolchains?

`pkg.cryptopp` pushed (I was waiting for tests to finish, Travis still running).

**Comment by chfast** [comment]
You mean i should propose the changes to pkg.cryptopp branch?

**Comment by ruslo** [comment]
Yes, if you want to exclude toolchains. Just like the last time:
* https://github.com/ingenue/hunter/pull/110/files

**Comment by chfast** [comment]
https://github.com/ingenue/hunter/pull/124

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2415
* https://travis-ci.org/ingenue/hunter/builds/276823689?utm_source=github_status&utm_medium=notification

**Comment by chfast** [comment]
Sorry, I messed AppVeyor: https://github.com/ingenue/hunter/pull/127.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2419
* https://travis-ci.org/ingenue/hunter/builds/276873145?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.105

**Pull request merged**
