### PR TITLE
Update 'fmt' to v4.1.0

### PR DESCRIPTION
**Pull request by headupinclouds**
* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/headupinclouds/hunter-8w0rs/build/1.0.62
  * https://travis-ci.org/headupinclouds/hunter/builds/373746992

+ I reversed the order of release versions in the hunter.cmake file based on the recommendation in hunter doc (will provide cleaner diff in future PR's)
+ This is an initial step to an spdlog update (which currently bundles fmt 4.1.0)

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3825
* https://travis-ci.org/ingenue/hunter/builds/373847610?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3826
* https://travis-ci.org/ingenue/hunter/builds/373859182?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.20.64

**Comment by headupinclouds** [comment]
Thanks!  I'll follow up with an spdlog update.

**Pull request merged**
