### PR TITLE
Catch v1.8.2-po 

### PR DESCRIPTION
**Pull request by x10mind**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1562
* https://travis-ci.org/ingenue/hunter/builds/220543816

**Comment by ruslo** [comment]
> Testing

Looks like new version of Catch use more c++11 stuff than previous one. `clang-libstdcxx` build is broken now because of missing c++11 features ("no type named 'nullptr_t' in namespace 'std'"). Feel free to exclude toolchain from testing, please send pull request to branch [pkg.catch](https://github.com/ingenue/hunter/tree/pkg.catch).

**Comment by dvirtz** [comment]
What's up with this? Can I send a PR to https://github.com/ingenue/hunter/tree/pkg.catch myself to exclude the failing toolchain?

**Comment by ruslo** [comment]
@dvirtz Yes, please send

**Comment by ruslo** [comment]
Please resolve conflict.

**Comment by ruslo** [comment]
Please squash all changes into one commit.

**Comment by rusdevops** [comment]
@x10mind 
```ShellSession
$ git clone https://github.com/x10mind/hunter
$ cd hunter
$ git pull origin develop
$ git checkout develop
$ git reset HEAD~2
$ git add .
$ git commit -m"updated catch package"
$ git push origin develop
```

**Comment by x10mind** [comment]
Ok, thanks. But after that I need resolve a conflict, therefore it was easier to do it again.

**Pull request closed without merging**
