### PR TITLE
add farmhash + test

### PR DESCRIPTION
**Pull request by headupinclouds**
Note: Won't be merged until after 11/9
@xsacha, @d4nst, @roscopecoltran : for tensorflow

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2710
* https://travis-ci.org/ingenue/hunter/builds/299724435?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2721
* https://travis-ci.org/ingenue/hunter/builds/299880369?utm_source=github_status&utm_medium=notification

**Comment by headupinclouds** [comment]
Thanks

**Comment by ruslo** [comment]
Follow-up: https://github.com/ruslo/hunter/commit/e88fbcd704299f3a7d1a878996dab4b144b8f0d8

Released: https://github.com/ruslo/hunter/releases/tag/v0.19.145

**Pull request merged**
