### PR TITLE
add spdlog version 0.11.0 from upstream

### PR DESCRIPTION
**Pull request by sv99**

### CODE REVIEW

**Comment by sv99** [comment]
changed

**Comment by ruslo** [comment]
Thanks, testing
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.987
* https://travis-ci.org/ingenue/hunter/builds/162476567

**Comment by ruslo** [comment]
> https://ci.appveyor.com/project/ingenue/hunter/build/1.0.987

Some toolchains stop working. Looks like new version use more new c++11 stuff which are not available for old Visual Studio version. There are next options:
* you can set old version for old visual studio in `config.cmake`, like
```cmake
if(MSVC_VERSION VERSION_LESS ...)
  hunter_config(... VERSION <old-version>)
else()
  hunter_config(... VERSION <new-version>)
endif()
```
* you can send patches with fixed to spdlog upstream, then repeat release/update procedure
* you can remove broken toolchains from appveyor.yml, please send patches to [pkg.spdlog](https://github.com/ingenue/hunter/tree/pkg.spdlog) branch

**Comment by sv99** [comment]
changed

**Comment by ruslo** [comment]
Thanks, new testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.995
* https://travis-ci.org/ingenue/hunter/builds/162604972

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.996
* https://travis-ci.org/ingenue/hunter/builds/162620958

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.15.33

**Pull request merged**
