### PR TITLE
Added package xinerama

### PR DESCRIPTION
**Pull request by pretyman**
I did this change on top of https://github.com/ruslo/hunter/pull/466 

I wonder if when you merge https://github.com/ruslo/hunter/pull/466 , the commits related to package `xrandr` will disappear from this pull request

### CODE REVIEW

**Comment by ruslo** [comment]
> I wonder if when you merge #466 , the commits related to package xrandr will disappear from this pull request

Unfortunatelly not as far as I know :(

**Comment by ruslo** [comment]
> Unfortunately not as far as I know :(

Yes, looks quite the same...

**Comment by pretyman** [comment]
> Yes, looks quite the same...

Ok, I updated the pull request and the commits from the other package went away.

I'll just wait for you to merge and open the pull requests accordingly then. I'm a little stuck on package `mesa`, but should be able to work it out. 

Package `glfw` seems to be quite troublesome :|

**Comment by ruslo** [comment]
> I'm a little stuck on package mesa, but should be able to work it out

`mesa` is for OpenGL drivers, right? I have tried that one but decide to use system OpenGL because there are too much packages :) It would be really nice to have that one in Hunter.

**Comment by ruslo** [comment]
Testing `xinerama`: https://travis-ci.org/ingenue/hunter/builds/146953761 (everything failed)
Testing `xineramaproto`: https://travis-ci.org/ingenue/hunter/builds/146953893

**Comment by pretyman** [comment]
> Testing xinerama: https://travis-ci.org/ingenue/hunter/builds/146953761 (everything failed)

That's odd, I cannot reproduce on my VM (it's a bare naked fedora with basically only gcc + cmake + autoconf + build essentials + vim).

In my test I run inside 
`examples/xinerama`
the command 
`rm -rf ~/.hunter/_Base/Cache/ ~/.hunter/_Base/xxxxxxx/ _*` 
Then build it with `polly` with: 
`~/polly/bin/build.py --fwd HUNTER_USE_CACHE_SERVERS=NO --verbose --jobs 3`

My local test compiles successfully 
```
make[2]: Entering directory '/home/builder/.hunter/_Base/xxxxxxx/8593cd5/d17a7ab/Build/xinerama/Source/src'
  CC     Xinerama.lo
  CCLD   libXinerama.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/builder/.hunter/_Base/xxxxxxx/8593cd5/d17a7ab/Build/xinerama/Source/src'
```

While Travis fails with:
```
make[2]: Entering directory `/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/056ddf7/8593cd5/c07028d/Build/xinerama/Source/src'
  CC     Xinerama.lo
  CCLD   libXinerama.la
/bin/grep: /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/e57d113/6d7617a/c07028d/Install/lib/libxcb.la: No such file or directory
/bin/sed: can't read /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/e57d113/6d7617a/c07028d/Install/lib/libxcb.la: No such file or directory
libtool: link: `/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/e57d113/6d7617a/c07028d/Install/lib/libxcb.la' is not a valid libtool archive
make[2]: Leaving directory `/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/056ddf7/8593cd5/c07028d/Build/xinerama/Source/src'
```

What it is strange is that the `<root-id>` is different for searching `libxcb.la` then the build source for `xinerama`: 

/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/**e57d113/6d7617a/c07028d**/Install/lib/libxcb.la 
/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/**056ddf7/8593cd5/c07028d**/Build/xinerama/Source/src

Do you have any insights in this scenario?

**Comment by ruslo** [comment]
> I cannot reproduce on my VM

You can use Docker to reproduce environment exactly: https://github.com/ruslo/hunter/wiki/Uploading-binaries-to-server#environment-notes

> Do you have any insights in this scenario? Something related to cache, it seems

Yep, looks like full path stored in cache.

**Comment by pretyman** [comment]
> mesa is for OpenGL drivers, right?

yep

> I have tried that one but decide to use system OpenGL because there are too much packages :)

I will have to give in as well, `mesa` depends on `libudev` which was incorporated into `systemd`, and `systemd` doesn't pass `./autogen.sh` stage on my VM:

```
[ 62%] Performing configure step for 'systemd'
cd /home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Build/systemd/Source && . /home/builder/.hunter/scripts/clear-all.sh && AR=/usr/bin/ar PATH=/home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Install/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin PKG_CONFIG_PATH=/home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Install/lib/pkgconfig:/home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Install/share/pkgconfig ./autogen.sh && ./configure AR=/usr/bin/ar LD=/usr/bin/ld NM=/usr/bin/nm OBJCOPY=/usr/bin/objcopy OBJDUMP=/usr/bin/objdump RANLIB=/usr/bin/ranlib STRIP=/usr/bin/strip CC=/usr/bin/cc CXX=/usr/bin/c++ CPPFLAGS=-I/home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Install/include "CFLAGS=-O3 -DNDEBUG" "CXXFLAGS=-O3 -DNDEBUG" LDFLAGS=-L/home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Install/lib --disable-shared --enable-static --prefix=/home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Build/systemd/Install
configure.ac:73: warning: macro 'AM_NLS' not found in library
configure.ac:74: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
configure.ac:74: the top level
configure.ac:74: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
configure.ac:74: the top level
configure.ac:74: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
configure.ac:74: the top level
configure.ac:74: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
configure.ac:74: the top level
configure.ac:73: error: possibly undefined macro: AM_NLS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
CMakeFiles/systemd.dir/build.make:111: recipe for target 'systemd-prefix/src/systemd-stamp/systemd-configure' failed
gmake[2]: *** [systemd-prefix/src/systemd-stamp/systemd-configure] Error 1
gmake[2]: Leaving directory '/home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Build/systemd/Build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/systemd.dir/all' failed
gmake[1]: *** [CMakeFiles/systemd.dir/all] Error 2
gmake: *** [all] Error 2
gmake[1]: Leaving directory '/home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Build/systemd/Build'
Makefile:86: recipe for target 'all' failed

[hunter ** FATAL ERROR **] Build step failed (dir: /home/builder/.hunter/_Base/xxxxxxx/978e8cc/d17a7ab/Build/systemd
[hunter ** FATAL ERROR **] [Directory:/home/builder/.hunter/cmake/projects/systemd]
```

**Comment by pretyman** [comment]
> You can use Docker to reproduce environment exactly

I don't think Docker wants to cooperate with me or maybe there is a problem with quay.io, because I get stuck during downloads, even killing it and trying again,
 takes me to a frozen:

```
builder@builder:~/docker$ sudo docker pull quay.io/ruslo/hunter-travis
Using default tag: latest
latest: Pulling from ruslo/hunter-travis
74db925ddbf2: Already exists
853f1765820a: Already exists
2611725f8677: Already exists
a5eba8ff97a5: Already exists
a3ed95caeb02: Pulling fs layer
fe61e9a4adde: Already exists
e643e8b6b815: Already exists
3dfcbc97cb52: Already exists
e211bff5afa9: Already exists
682371da473f: Already exists
3702f741f02a: Already exists
9bc54eafbbcd: Already exists
13bcbf325e33: Already exists
eed17e28cc1f: Already exists
4fb85d2662ba: Already exists
d5d27e9923e6: Already exists
3222cef56ef9: Already exists
cc5bbd24aa84: Already exists
2e0530937d8f: Already exists
1b42bbbdb920: Already exists
a86fe10493d0: Downloading [===>                                               ] 89.58 MB/1.378 GB
13672fdd2da8: Downloading [=================>                                 ] 270.9 MB/766.5 MB
6c9e224695f8: Download complete
40240b993179: Download complete
e34e270f97fb: Download complete
737c08b83e0d: Download complete
5e8757cfbf12: Download complete
fb7d4249d624: Download complete
a78eff490f34: Download complete
ea23602a7bee: Download complete
a191521868a6: Download complete
23f3bf961140: Download complete
59aef3b68a7c: Download complete
96d2fad7ddbc: Downloading [=>                                                 ] 28.06 MB/1.402 GB
```

Have you ever come across this situation? This is my first time using Docker, maybe I missed something

**Comment by pretyman** [comment]
> You can use Docker to reproduce environment exactly: https://github.com/ruslo/hunter/wiki/Uploading-binaries-to-server#environment-notes

Thanks, I've manage to reproduce it, it seems that the package `xcb` from the ingenue cache has been uploaded with `*.la` files with those paths. I'm having trouble finding the exact file in the ingenue cache repository to download it myself and extract it to look inside, can you tell me link? ;-)

**Comment by ruslo** [comment]
From [logs](https://travis-ci.org/ingenue/hunter/jobs/146953764):

```
-- [hunter *** DEBUG (CACHE RUN) *** 2016-07-24T06:48:58] Downloading file (try #0 of 10):
-- [hunter *** DEBUG (CACHE RUN) *** 2016-07-24T06:48:58]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/8928885/xcb/1.11.1/28e47aa/da39a3e/d41f56c/356a192/62fa460/CACHE.DONE
-- [hunter *** DEBUG (CACHE RUN) *** 2016-07-24T06:48:58]   -> /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/Cache/meta/8928885/xcb/1.11.1/28e47aa/da39a3e/d41f56c/356a192/62fa460/CACHE.DONE
-- [hunter *** DEBUG (CACHE RUN) *** 2016-07-24T06:48:59] Downloading file (try #0 of 10):
-- [hunter *** DEBUG (CACHE RUN) *** 2016-07-24T06:48:59]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/8928885/xcb/1.11.1/28e47aa/da39a3e/d41f56c/356a192/62fa460/cache.sha1
-- [hunter *** DEBUG (CACHE RUN) *** 2016-07-24T06:48:59]   -> /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/Cache/meta/8928885/xcb/1.11.1/28e47aa/da39a3e/d41f56c/356a192/62fa460/cache.sha1
-- [hunter *** DEBUG (CACHE RUN) *** 2016-07-24T06:48:59] Cache HIT: xcb
-- [hunter *** DEBUG (CACHE RUN) *** 2016-07-24T06:48:59] Cache info: /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/Cache/meta/8928885/xcb/1.11.1/28e47aa/da39a3e/d41f56c/356a192/62fa460/cache.sha1
```

File with archive name (just SHA1):
* https://github.com/ingenue/hunter-cache/blob/master/8928885/xcb/1.11.1/28e47aa/da39a3e/d41f56c/356a192/62fa460/cache.sha1

By doing [blame](https://github.com/ingenue/hunter-cache/blame/master/8928885/xcb/1.11.1/28e47aa/da39a3e/d41f56c/356a192/62fa460/cache.sha1) you can find [more info](https://github.com/ingenue/hunter-cache/commit/60880a2d5ad92ec7cac603dae7ce702d748e62c5) like job from where is was uploaded:
* https://travis-ci.org/ingenue/hunter/jobs/146921462

Anyway here is the link to archive:
* https://github.com/ingenue/hunter-cache/releases/download/cache/f2f8743ac1bf356178153a36a3103daa2c41dfa8.tar.bz2

**Comment by pretyman** [comment]
> Anyway here is the link to archive

Thanks, I don't think I would have been able by myself at 2 AM.

So the patching of the of the cache build directory is properly patched: 
```
libdir='__HUNTER_PACKAGE_INSTALL_PREFIX__/lib'
```

However, when building the cacheable package, it links to libraries in `@HUNTER_INSTALL_PREFIX@/lib` which is not considered in the patching, and this information went into the `dependency_libs`. 

```
dependency_libs=' -L/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/2a647da/6d7617a/8928885/Install/lib /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/2a647da/6d7617a/8928885/Install/lib/libXau.la'
```

Tonight I will open an issue and have a look at this.

**Comment by pretyman** [comment]
Can you re-test this pull request? It should be working after the merge of https://github.com/ruslo/hunter/pull/473

**Comment by ruslo** [comment]
Testing:
* https://travis-ci.org/ingenue/hunter/builds/148055188
* https://travis-ci.org/ingenue/hunter/builds/148055054

**Comment by ruslo** [comment]
Uploading:
* https://travis-ci.org/ingenue/hunter/builds/148060536
* https://travis-ci.org/ingenue/hunter/builds/148060251

**Comment by pretyman** [comment]
Thanks, I deleted the comment because I realised I must comment out the failing tests. It seems like you've done it, thank you very much. Tonight I'll look at appveyor tests and comment them out, if they still need to be.

**Pull request merged**
