### PR TITLE
Autotools: clear CONFIG_SITE environment variable as Linux distros can override it

### PR DESCRIPTION
**Pull request by pretyman**
An example of a distribution that overrides it is OpenSuse:
https://github.com/ruslo/hunter/issues/503

Tested this change in OSX 10.11.2 and OpenSuse. Could be good idea to run tests for pkg.glfw as it compiles a lot of x11 packages which rely on autotools.

### CODE REVIEW

**Comment by pretyman** [comment]
Meh, I think this will (further) break iOS Autotools integration, need to test more, don't merge :|

Sorry, will have a look at this better over the week.

**Comment by pretyman** [comment]
Best solution would be to package a `config.site` file together with hunter: https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Site-Defaults.html#Site-Defaults and set the environment variable CONFIG_SITE pointing to it.

**Comment by ruslo** [comment]
> Could be good idea to run tests for pkg.glfw as it compiles a lot of x11 packages which rely on autotools.

We will test nothing until you change INTERNAL_DEPS_ID of affected packages :)

**Comment by pretyman** [comment]
> We will test nothing until you change INTERNAL_DEPS_ID of affected packages :)

I expect that this change does not alter the contents of the compiled packages, change anyway?

**Comment by ruslo** [comment]
> I expect that this change won't alter the contents of the compiled packages

No need if you're 100% sure. But in this case there make no sense to run tests as you suggested before: "pkg.glfw as it compiles a lot of x11 packages which rely on autotools" - they all will be taken from cache.

**Comment by pretyman** [comment]
Updated this pull request.

For now the less intrusive fix is to clear `CONFIG_SITE` that is set in OpenSuse. If such issue pops up again in the future, then we can take more drastic measures and create hunter's down `config.site`.

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.15.23

**Pull request merged**
