### PR TITLE
Add c-ares package

### PR DESCRIPTION
**Pull request by isaachier**

### CODE REVIEW

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2559
* https://travis-ci.org/ingenue/hunter/builds/289655214?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Testing

iOS is not working.

**Comment by isaachier** [comment]
Just saw. Will remove.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2564
* https://travis-ci.org/ingenue/hunter/builds/289984792?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2569
* https://travis-ci.org/ingenue/hunter/builds/290052828?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.126

**Pull request merged**
